### ISSUE TITLE
Error “internally linking to , which does not exist”

### ISSUE THREAD

**Issue by doktorbro** [gjtorikian/html-proofer#104]
@lurch reported the issue in https://github.com/raspberrypi/documentation/issues/104#issuecomment-53555771. Looks similar to #102.

I can reproduce the issue on my clone https://github.com/penibelst/documentation/commit/6787d65531891c4c231502c6d0482eab1134acaf

**Comment by envygeeks** [comment]
I get this problem when the link doesn't have a "/" at the end to a full domain.  I don't think that's how it should work, unless I am missing something, but since the browser handles that problem, it shouldn't be enforced.

**Comment by envygeeks** [comment]
The reason I think it shouldn't work this way is because the only way to normalize URL's is with Ruby (in Jekyll) and of course I can in my own plugin, but within another authors plugin this becomes a PITA see:

```
- site/2013/06/24/mocking-activerecord-to-test-concerns.html
  *  internally linking to https://envygeeks.io//, which does not exist (line 79)
     <a href="https://envygeeks.io//">Jordon Bedwell</a>
```
```liquid
    <p class="author">
      <a href="{{ post.stat.author.website }}/">
        {{ post.stat.author.name }}
      </a>
    </p>
```

It becomes even more strenuous when dealing with data from another domain.

**Comment by envygeeks** [comment]
To add, I guess this could be a mixture of `internal_domains` and otherwise.
