### ISSUE TITLE
Namespace Typhoeus options

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/html-proofer#114]
As noted in https://github.com/gjtorikian/html-proofer/pull/113#issuecomment-55334811, Typhoues is real picky about what it take in. I'll need to make a breaking release in order to namespace Typhoeus (and other libs!) options. So rather than

```
HTML::Proofer.new("out/", {:ext => ".htm", :verbose => true, :ssl_verifyhost => 2 })
```

It should be

```
HTML::Proofer.new("out/", {:ext => ".htm", :verbose => true, :typhoeus => {:ssl_verifyhost => 2 }})
```

**Comment by holic** [comment]
:+1:
