### ISSUE TITLE
Ignore <a href="#"> when checking internal links

### ISSUE THREAD

**Issue by akoeplinger** [gjtorikian/html-proofer#118]
Using such anchors is quite a common practice (e.g. by [Bootstrap Dropdowns](http://getbootstrap.com/components/#btn-dropdowns)) and generates the following error:

> index.html: linking to internal hash # that does not exist

I think they shouldn't trigger an error as they are just used as a placeholder and not for linking to a specific part of the document.

**Comment by ssbarnea** [comment]
I think that this bug should be reopen, Jekyll should ignore this one by default, because as already pointed, that's valid, and also quite common. Default settings should be friendly.

**Comment by penibelst** [comment]
> Jekyll should ignore this one by default.

You mean Proofer, right?

**Comment by jacebrowning** [comment]
I think `htmlproof <site> --href-ignore "#"` should be the default.

**Comment by einverne** [comment]
It seems in version 3.0.5 there is no option `--href-ignore "#"`. However, after I add `--allow-hash-href` or `--url-ignore "#"`. I still got error like this:

    linking to internal hash #left that does not exist (line 205)

**Comment by einverne** [comment]
After I lot of search, I figure I have to write RegExps like `--url-ignore "/#.*/` to ignore "#left" etc internal hash.

**Comment by fulldecent** [comment]
I'm just writing a note here to clarify since I see other people are linking to this page. To set the record straight: 

> If you use `<a href="#xxx">` when `#xxx` does not exist, then you are doing it wrong.

A lot of people do it, but it's wrong. Usually the correct solution is to have `<span class=...>` or `<div class=...>`. The Bootstrap people are pretty smart. Their examples are full of `"#"` but those represent links for content you still need to make.

*Exception*: if you have something like Gmail where the fragment is `#inbox-message-12546` and it intentionally changes to reflect page state then maybe that is special. But in that case, I would argue that you should have `<body id="inbox-message-12546">`.

**Comment by aduth** [comment]
While true that empty anchor fragment `#` is often misused, it is considered in the HTML specification as a valid value referencing the top of the current document:

>If fragment is the empty string, then the indicated part of the document is the top of the document; return.

https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-the-fragment-identifier

It could be used this way for "Back to Top" links shown at the bottom of a page, for example.

See also #421, which added explicit support for `#top` links (which pass currently using `htmlproofer`).

**Comment by fulldecent** [comment]
There may be some confusion in WHATWG as to what is a *null* fragment and what is an *empty string* fragment.

But here is the authoritative text:

> **A URL’s fragment** is either null or an ASCII string that can be used for further processing on the resource the URL’s other components identify. **It is initially null.**
>
> https://url.spec.whatwg.org/#concept-url-fragment

> If c is U+0023 (#), then **set url’s fragment to the empty string** and state to fragment state.
>
> https://url.spec.whatwg.org/#path-state

And also, for the relative URL "#", here is the respective line:

> Otherwise, if base’s cannot-be-a-base-URL flag is set and c is U+0023 (#), set url’s scheme to base’s scheme, url’s path to a clone of base’s path, url’s query to base’s query, **url’s fragment to the empty string**, set url’s cannot-be-a-base-URL flag, and set state to fragment state.
>
> https://url.spec.whatwg.org/#no-scheme-state

And then as you note:

> If fragment is the empty string, then the indicated part of the document is the top of the document; return.
> 
> https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-the-fragment-identifier

---

Therefore, a link to "#" is always valid. Thank you, I stand corrected. Issue is valid.

**Comment by yktoo** [comment]
For those ended up here via search, passing `--allow-hash-href` causes `htmlproofer` to ignore `href="#"`.

**Comment by gjtorikian** [comment]
Closing this out as an old issue. I'm working on [the next major upgrade for HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) and guaranteed that `allow-hash-href` does still work.
