### ISSUE TITLE
Error: Could not load 'libcurl'

### ISSUE THREAD

**Issue by SeanKilleen** [gjtorikian/html-proofer#135]
Hi all, 

I'm new to this, so apologies if it's not really an issue.

Encountering an issue using this with my Jekyll blog to test the output. 
## Background/Setup

I'm on Windows, in case that makes a difference.

I'm using `v1.5.4` (also tried with `v1.4.0`), and my `RakeFile` is the example from the documentation in the README: 

```
require 'html/proofer'

task :test do
  sh "bundle exec jekyll build"
  HTML::Proofer.new("./_site").run
end
```

I have placed `gem 'html-proofer', '>=1.5.4'` in my gemfile.
## The Issue

When running `bundle exec rake test`, I see the following output: 

```
DL is deprecated, please use Fiddle
rake aborted!
LoadError: Could not open library 'libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.
C:/users/sean/Repositories/Github/seankilleen.github.io/RakeFile:1:in `require'
C:/users/sean/Repositories/Github/seankilleen.github.io/RakeFile:1:in `<top (required)>'
```

Only submitting here because it seems like it might be an issue with dependencies, etc. (since I was unaware of any requirement for curl, though the requirement makes sense). 

I added curl to my gemfile as well, with the same result.

Any pointers on what I'm doing wrong or potential solutions would be greatly appreciated.

**Comment by fulldecent** [comment]
On linux I use this before installing htmlproofer

```sh
sudo apt-get install ruby-dev build-essential libxml2 libxslt-dev 
```

However, I'm still not sure which curl is needed.
