### ISSUE TITLE
Is there a way to only perform the "Links" and "Scripts" checks and not the "Images" check?

### ISSUE THREAD

**Issue by csu** [gjtorikian/html-proofer#138]
tag: question

**Comment by parkr** [comment]
@csu You can't use the `htmlproof` executable, but you can monkey patch in your own script:

```ruby
require 'html/proofer'

module HTML
  class Proofer
    def get_checks
      %w{Links Scripts}
    end
  end
end 

# Construct path & options
HTML::Proofer.new(path, options).run
```

**Comment by csu** [comment]
Just tried it. Totally worked! Thanks!

**Comment by gjtorikian** [comment]
I think this is a good candidate for 2.0 (which I just started this week), so I'll reopen this.

**Comment by csu** [comment]
Cool! Yeah, I was trying to figure out a way to disable a check through the options and couldn't find anything, so I figured I would ask :stuck_out_tongue:.

**Comment by csu** [comment]
:bow: Thanks!
