### ISSUE TITLE
Cannot test HTTPS URLs on travis

### ISSUE THREAD

**Issue by Floppy** [gjtorikian/html-proofer#140]
I'm guessing Travis boxes have some missing certificates or something, but links that pass locally fail there with something like:

```
External link https://democracyclub.org.uk/ failed: 0 Peer certificate cannot be authenticated with given CA certificates
```

See https://travis-ci.org/Floppy/floppy.github.io/builds/46205870 for an example.

Perhaps an option to disable SSL verification might help?

**Comment by Floppy** [comment]
Ignore me, I think I can fix this with the Typhoeus options. Sorry!

**Comment by Floppy** [comment]
Yes, that's right. For the benefit of google, my configuration was:

```
HTML::Proofer.new("./_site", ssl_verifypeer: false).run
```

**Comment by parkr** [comment]
Thanks for adding that benefit for Google, @Floppy! Were you able to fix it without removing SSL verification?
