### ISSUE TITLE
Failures on urlencoded hrefs

### ISSUE THREAD

**Issue by mweinelt** [gjtorikian/html-proofer#143]
```
  *  internally linking to /2014/erstiebegr%C3%BC%C3%9Fung.html, which does not exist
  *  internally linking to /2014/cradar-%C3%BCber-paypa.html, which does not exist
  *  internally linking to /2014/demokratie-statt-%C3%BCberwachung.html, which does not exist
```
created by Jekyll that way. The files are called:
```
cradar-über-paypa.html
demokratie-statt-überwachung.html
erstiebegrüßung.html
```
which browsers usually handle just fine.

**Comment by gjtorikian** [comment]
@parkr Is this expected behavior, though, in Jekyll?

**Comment by gjtorikian** [comment]
Oh, I misunderstood I think, sorry--Jekyll's spitting out the proper filename (eg. erstiebegrüßung.html).

**Comment by gjtorikian** [comment]
This should be fixed by https://github.com/gjtorikian/html-proofer/pull/144, to be released :soon:
