### ISSUE TITLE
file_ignore list only looks at first argument ?

### ISSUE THREAD

**Issue by ahgittin** [gjtorikian/html-proofer#145]
is there a bug in the way multiple entries in the `file_ignore` list are handled?  it looks like only the first item in the list is respected.

(then again it's entirely possible i've misunderstood how regex arrays are written in ruby -- apologies if so)

the issue is that this works to exclude ../catalog/.. items:

      :file_ignore => [ /.*\/(javadoc|catalog)\/.*/ ]

but this does not:

      :file_ignore => [ /.*\/javadoc\/.*/, /.*\/catalog\/.*/ ]

**Comment by gjtorikian** [comment]
Nope, it looks like `file_ignore` definitely iterates over each item: https://github.com/gjtorikian/html-proofer/blob/f2d3b576800fae45828ef08d591021a0285c7e5b/lib/html/proofer.rb#L234-L240

Your regexp also looks right to me. I just noticed [my test](https://github.com/gjtorikian/html-proofer/pull/136/files) doesn't check for a list of ignore patterns, it only has a first item--so let me add a new test and see how that goes.

**Comment by gjtorikian** [comment]
@ahgittin Well, you were right! The array wasn't iterating for some reason. A fix is made in https://github.com/gjtorikian/html-proofer/pull/153, and should be released in HTML-Proofer 2.0 :soon:
