### ISSUE TITLE
No line numbers in error output

### ISSUE THREAD

**Issue by mietek** [gjtorikian/html-proofer#146]
When using `htmlproof` from the command-line, the error output for my sites consists mostly of the following messages:

```
  *  anchor has no href attribute
  *  anchor has no href attribute
  *  anchor has no href attribute
...
```

Please add line numbers to error output in order to assist with fixing these errors.

**Comment by gjtorikian** [comment]
I am pretty sure this is impossible to do, as html-proofer is using Nokogiri, and Nokogiri just looks at nodes, not content.

**Comment by mietek** [comment]
It seems like Nokogiri can, in fact, keep track of the line numbers while parsing:

> ### [Nokogiri::XML::Node#line](http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Node:line)
> 
> ```
> #line ⇒ Object
> ```
> Returns the line for this Node

**Comment by gjtorikian** [comment]
Huh. I'll look into it.

**Comment by mietek** [comment]
Thanks.
