### ISSUE TITLE
srcset raising error

### ISSUE THREAD

**Issue by nlhkabu** [gjtorikian/html-proofer#149]
I am using picturefill in my html.  The markup is:
```html
<picture>
    <!--[if IE 9]><video style="display: none;"><![endif]-->
    <source srcset="examples/images/extralarge.jpg" media="(min-width: 1000px)">
    <source srcset="examples/images/large.jpg" media="(min-width: 800px)">
    <!--[if IE 9]></video><![endif]-->
    <img srcset="examples/images/medium.jpg" alt="A giant stone face at The Bayon temple in Angkor Thom, Cambodia">
</picture>
```

In this instance, html-proofer is raising an error because the img tag has a srcset rather than a src:
`  *  image has no src attribute`

Is this the correct behaviour?   MDN: ["On browsers supporting srcset, src is ignored if this one is provided."](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)

**Comment by gjtorikian** [comment]
Huh. I never knew about `srcset`. This is definitely a bug, thanks for reporting! Will get to it :soon:.

**Comment by nlhkabu** [comment]
Thanks! In the meantime, is there a way to tell html-proofer to ignore all `<img>` tags within `<picture>` elements?  I'm currently adding `data-proofer-ignore` to each img, but it would be better not to have to do this each time.

**Comment by gjtorikian** [comment]
I'm afraid not. :frowning: I'm [in the midst of a 2.0 release](https://github.com/gjtorikian/html-proofer/pull/147), and I'll make sure `srcset` support is in there. Probably within the next day or two!

**Comment by penibelst** [comment]
> Huh. I never knew about srcset.

@gjtorikian You have forgotten the #70.
