### ISSUE TITLE
HTML base tag

### ISSUE THREAD

**Issue by bertrand-caron** [gjtorikian/html-proofer#166]
Hi,

I have not yet come up with a test for it, but I have the feeling html-proofer does not implement the [HTML base tag](http://www.w3schools.com/tags/tag_base.asp).

I myself only discovered the existence of the tag recently, which is really useful for not hardcoding too much in your site's URL.

Do you want to comment on that ?

Cheers, B.

**Comment by gjtorikian** [comment]
Wow, that's new to me too. No, Proofer doesn't handle this yet...but it should.

**Comment by penibelst** [comment]
The base tag is not widely used. Bertrand, can you provide a public website made by you with the base tag?

**Comment by bertrand-caron** [comment]
Hi Anatole,

I am using for a corporate website that I would not like to advertise here, but basically any website that is sitting in a subdirectory could use the `<base>` tag to avoid hardcodding this subdirectory path anywhere else than on the base tag. 

For instance if you are building a blog on your domain name 'hello.me/blog/2010-03-10-my-blog-post.html', I think you are better off setting `<base href='hello.me/blog'>` and referencing your links as `<a href='2010-03-10-my-blog-post.htm'`.

Am I making sense ?

Regardless of that, shouldn't the fact that it exists in the standard be enough to make its implementation worthwhile ?

PS : Of course, I would have used subdomains if I could.

**Comment by lurch** [comment]
> Do you know another corporate website which uses the base tag?

We use the base tag on e.g. http://www.interballoon.com/cgi-bin/order.pl and http://www.interrose.co.uk/flowers/20_pink_freesias.shtml as it allows us to keep using relative links to the files in the root directory, even though the current page is being served from a subdirectory. It means the page in the subdirectory doesn't have to get cluttered with '../' everywhere.
