### ISSUE TITLE
fix support of urls in link rel="canonical"

### ISSUE THREAD

**Issue by pkozelka** [gjtorikian/html-proofer#170]
Currently, htmlproof fails when the url in canonical link does not exist, and reports it as invalid external url.
But it is quite common, when adding or renaming a page, that the page does not exist on remote side yet. 
Therefore this case should be IMHO excluded, because
* it does not introduce a reference of the page to another page
* instead, it defines how *this* page should be referenced from others

**Comment by penibelst** [comment]
So you create a new page `new.html` in your development environment and set the canonical url in the head section.

```html
<link rel="canonical" href="http://example.org/new.html" />
```

It doen’t exist yet and Proofer fails. I propose to define the canonical url as a relative url.

```html
<link rel="canonical" href="/new.html" />
```

Could you live with this solution?

**Comment by penibelst** [comment]
For the sake of completeness I link to [Google’s guidelines](https://support.google.com/webmasters/answer/139066).

**Comment by pkozelka** [comment]
yes, thanks, I have found this option just a while ago, thanks. So far I visited several pages discussing canonical urls and all were showing only usage with complete URLs, so I supposed it is required.

So yes, I can live with this; however, philosophically, I still believe that the current behavior is not good, for reasons I mentioned - this link does not add *reference to another page*, instead it defines kind of *preferred ID* of current page. 

Maybe this link should be checked for different things; like if it corresponds to the filename where it occurs.

**Comment by penibelst** [comment]
> So yes, I can live with this

Glad to hear it.

**Comment by doismellburning** [comment]
I was about to file the same issue and then I saw this. I'd say it was entirely reasonable (and indeed conventional) for the `canonical` link to include a domain part, so this should be ignored when checking...

**Comment by doismellburning** [comment]
Have just hit the same issue on another project I work on - see https://github.com/PyconUK/pyconuk.github.io/pull/19 / https://travis-ci.org/PyconUK/pyconuk.github.io/builds/57180787 for an example

**Comment by abethcrane** [comment]
I'm also running into this issue. The Google guidelines linked above specifically say to use absolute paths: "Avoid errors: use absolute paths rather than relative paths with the rel="canonical" link element" - is there a reason to prefer relatives?

**Comment by penibelst** [comment]
The Google guidelines *recommends* to use absolute paths.

> is there a reason to prefer relatives?

Yes. They are

* short, so you save band wide.
* valid, while you create the page, so you can use tools like Proofer.

BTW, you don’t need canonical elements at all if don’t duplicate content. They only exist “for content available through multiple URL structures”.

**Comment by tongueroo** [comment]
@pkozelka @abethcrane I ran into the same issue. worked around this by using href_swap and removing the domain, covered it [here](http://tongueroo.com/articles/getting-html-proofer-to-work-with-canonical-url-for-google-seo/) 

Summary: basically, I have a task that does this:

```ruby
task :test do
  sh "bundle exec jekyll build"
  HTML::Proofer.new(
    "./_site",
    href_swap: {
      'http://tongueroo.com' => '', # canonical link in head
    },
  ).run
end
```

Hope that helps.

**Comment by fwoelm** [comment]
I just added `data-proofer-ignore` to the tag specifying the canonical url:

**General:**
`<link rel="canonical" href="http://www.some-absolute-url.com/some-post/" data-proofer-ignore>`

**For Jekyll:**
`<link rel="canonical" href="{{ page.url | replace:'index.html','' | prepend: site.baseurl | prepend: site.url }}" data-proofer-ignore>`

Works like a charm!

**Comment by tongueroo** [comment]
@fwoelm Awesome.  Thanks!

**Comment by iBobik** [comment]
Improved example from @tongueroo and rewritten for CLI:
```
htmlproofer _site --url-swap "https?\:\/\/(localhost\:4000|example\.com):"
```

**Comment by keymon** [comment]
Using middleman, we fixed adding `url_swap` (note, that is the new name of this option, not `href_swap`):

```ruby
require 'govuk_tech_docs'
require 'html-proofer'

activate :directory_indexes
after_build do |builder|
  begin
    HTMLProofer.check_directory(config[:build_dir], {
        :assume_extension => true,
        :allow_hash_href => true,
        :disable_external => true,
        :url_swap => { /#{config[:tech_docs]['host']}/ => '' },
    }).run
  rescue RuntimeError => e
    puts e
  end
end       
```
`:tech_docs` refers to our config file in `config/tech_docs.yml`
