### ISSUE TITLE
Using --file_ignore from command line

### ISSUE THREAD

**Issue by jflasher** [gjtorikian/html-proofer#177]
I am using v2.0.2 and trying to run from command line while ignoring certain directories. I am using the following command to try and ignore everything inside of the /blog/ directory but it is still being checked. 
```
htmlproof _site/ --file-ignore '.*\/blog\/.*' --verbose
```
I am sure I am just missing something simple, could you point me in the right direction?

**Comment by penibelst** [comment]
```
htmlproof _site --file-ignore /blog/ --verbose
```

**Comment by jflasher** [comment]
Thanks @penibelst knew it was something simple I was missing.
