### ISSUE TITLE
Warn about size of a downloaded page?

### ISSUE THREAD

**Issue by parkr** [gjtorikian/html-proofer#183]
I have the feeling when checking links, HTML Proofer downloads the entire thing. If you link out to a big archive, therefore, then HTML Proofer has to download the whole archive. Are we checking the `Content-Length` header to ensure it's not too large? Are we limiting downloading to HTML pages only?

Thanks :)

**Comment by parkr** [comment]
Typhoeus timeout and connecttimeout options are crucial to happiness. The default is 300 seconds. Why.

**Comment by gjtorikian** [comment]
> I have the feeling when checking links, HTML Proofer downloads the entire thing.

FWIW it actually doesn't do this. First a `HEAD` request is made to see if a link is valid. If that fails, it moves on to making a `GET`. Some servers are not properly configured to `HEAD`, so it might fail as a false negative: https://github.com/gjtorikian/html-proofer/blob/019a4108ebccddda245b8a3b1dbe9b3535f81e0f/lib/html/proofer/url_validator.rb#L32-L35
