### ISSUE TITLE
Check for images on a CDN

### ISSUE THREAD

**Issue by jacobtomlinson** [gjtorikian/html-proofer#184]
Hi,

I want to add a test to this to check whether all images are hosted on a CDN by checking the domain name specified. Partly to keep all images in the same place and partly to stop hotlinks which may break in the future.

Is this the kind of feature you want adding to the main project in a pull request or shall I just write it for myself locally? 

Jacob

**Comment by gjtorikian** [comment]
Eh, it's probably best to write this locally. I can see this becoming a configuration nightmare if it were brought into core.

Writing additional tests is super easy: https://github.com/gjtorikian/html-proofer#custom-tests

Thanks for checking in!
