### ISSUE TITLE
Problems with --href-swap 

### ISSUE THREAD

**Issue by eksperimental** [gjtorikian/html-proofer#192]
i found a real case that i need to use that has several issue when trying to set --href-swap from the command line
` --href-swap "/docs/:http://website.com/docs/" `
1st, it will take it as a regular expression because its surrounded by //, and there is not way to escape it properly, without giving up the original intention,
2nd, the colon, escaping doesn't work and it splits the strings into whatever amount of colons are there (I'll be submitting a patch for this).

i tried to hack around a little bit but I couldn't do much.
Maybe it escaping need to be implemented, 
also assigning regular expressions only with literals to avoid confusion with a situation like the one above.

**Comment by gjtorikian** [comment]
Fixed by https://github.com/gjtorikian/html-proofer/pull/193.
