### ISSUE TITLE
HTML-Proofer should follow clientside redirects

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/html-proofer#208]
As an option, if possible. This would involve GETing the page, parsing it with Nokogiri, and following any redirect info. This would be super useful for Jekyll sites, at the cost of slowing the run down.

**Comment by fulldecent** [comment]
To be clear, are we only talking about finding

    <meta http-equiv="refresh" content="0; url=otherPage.html" />

And interpreting that the same as 

    <a href="otherPage.html">.</a>

**Comment by gjtorikian** [comment]
No, it would mean finding

```
<meta http-equiv="refresh" content="0; url=otherPage.html" />
```

And then following `otherPage.html` and checking those links.

I actually no longer thing this is within the project's scope (a lot changes in two years) since I don't want it to be a general link crawler. Plus a directory that's filled with files should already find `otherPage.html` so I'm not really sure what I was thinking here.
