### ISSUE TITLE
Exclude references via RegEx?

### ISSUE THREAD

**Issue by anselmh** [gjtorikian/html-proofer#211]
Hi,

is it possible to exclude some references via RegEx? It seems `file_ignore` only is for files and `href_ignore` for `href` attributes. 

But there’s no way to achieve the same for `src` attributes. Is that possible though or are you able to add this?

Thanks for your help in advance,
Anselm

**Comment by penibelst** [comment]
I'm surprised the "href-ignore" option doesn't affect the "src" attribute. I think it should work on *any* attribute with references: href,src, srcset, …

**Comment by anselmh** [comment]
Ah, sorry. Was a bit unclear on that and got confused myself. So that’s the actual status/issue:

- `href_ignore` seems not to accept regex (at least a valid ruby regex is not recognized/applied)

I also think it would be great to be able to ignore hrefs and src/srcset attributes separately as I might want to exclude src errors but still test on the href. But the main issue is I have no way of excluding a whole directory from the tests.

**Comment by penibelst** [comment]
Could you please show your parameters?

**Comment by anselmh** [comment]
This is my `Rakefile`. Actually other options work and the google reference works as well but regex is not working.

	require "html/proofer"

	task :test do
	    HTML::Proofer.new("./_site", {
	        :href_ignore => [
	            "http://fonts.googleapis.com/",
	            /\/assets\/.*(js|css|png|svg)/
	        ]
	    }).run
	end

**Comment by penibelst** [comment]
Your parameters look correct to me. Can you please show a HTML element where the ignoring doesn’t work?

**Comment by anselmh** [comment]
Oh, sure:

    <script src="/assets/main.js"></script>
