### ISSUE TITLE
Ignore attributes other than href

### ISSUE THREAD

**Issue by GarthDB** [gjtorikian/html-proofer#213]
I'm getting errors on pages that haven't been published yet. Turns out it's the meta tag for the twitter card. I tried adding `data-proofer-ignore` to the meta tag, but it doesn't seem to ignore the `content` attribute.
```html
<meta name="twitter:url" data-proofer-ignore content="http://example.com/soon-to-be-published-url" />
```

**Comment by penibelst** [comment]
I’m already working on a global solution in #212.

But you also bring to our attention that `data-proofer-ignore` doesn’t work on Twitter’s meta elements. This is definitely a bug.

**Comment by GarthDB** [comment]
Excellent, I look forward to the pull request then. 

Closing because it is a duplicate issue to https://github.com/gjtorikian/html-proofer/pull/212
