### ISSUE TITLE
Include sitemap.xml in validation

### ISSUE THREAD

**Issue by jonbartlett** [gjtorikian/html-proofer#218]
As far as I can tell, sitemap.xml is not validated at present. Would be good to have this feature included.

**Comment by penibelst** [comment]
The sitemap is a tool to help robots do their work. It’s not an improvement for humans who are using HTML pages. Therefore I don’t see the sitemap validation as a feature inside Proofer.

@benbalter, is your [sitemap parser](https://github.com/benbalter/sitemap-parser) the right tool for @jonbartlett?

**Comment by benbalter** [comment]
It doesn't validate it, per se, but would at least give you a smoke test, for larger parse errors.

**Comment by jonbartlett** [comment]
Ok thanks @penibelst. Will close.
