### ISSUE TITLE
Introduce url_swap as companion for url_ignore

### ISSUE THREAD

**Issue by penibelst** [gjtorikian/html-proofer#219]
The new option `url_ignore` needs a companion that transforms links in every attribute. It should be an extended version of `href_swap`. I propose the name `url_swap`.

Related to #178, #214.

**Comment by mdotasia** [comment]
Do you have road map for `url_ignore`?

**Comment by penibelst** [comment]
@mdotasia `url_ignore` is available since version 2.3.0.

**Comment by nasht00** [comment]
Reading this, do I understand that currently, `href_swap` does not replace in every element?

What's the current workaround to make it work with images, and script sources?

**Comment by penibelst** [comment]
@nasht00, yes `href_swap` does replace only in elements with a `href` attribute. Therefore it’s for `a` elements only. The current workaround is to ignore those URLs you would swap.

**Comment by nasht00** [comment]
Every single URL on my site needs to be swapped (they all start with a virtual `/subdomain/` which does not really exist in the file system).

**Comment by nasht00** [comment]
Is there a roadmap for `url_swap`?

**Comment by penibelst** [comment]
@nasht00 No, there is no roadmap.

**Comment by gjtorikian** [comment]
Closed by HTMLProofer 3.0: https://github.com/gjtorikian/html-proofer/releases/tag/v3.0.0
