### ISSUE TITLE
Empty alt tag

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#228]
Code like this is being flagged:

```
<img alt="" src="images/spacer.gif">
```

I do not think it should be: http://www.w3.org/QA/Tips/altAttribute

**Comment by gjtorikian** [comment]
By default, I think it should l. But you can pass in the `empty_alt_ignore` option to avoid these errors; https://github.com/gjtorikian/html-proofer/blob/master/README.md#configuration

**Comment by fulldecent** [comment]
I read up a little more on this today.

---

This issue is also supported by the HTML5 specification.

Not generally under [4.8.1.1.1 General guidelines](https://dev.w3.org/html5/spec-LC/embedded-content-1.html#alt), but specifically under: 

1. [4.8.1.1.4 A short phrase or label with an alternative graphical representation: icons, logos](https://dev.w3.org/html5/spec-LC/embedded-content-1.html#a-short-phrase-or-label-with-an-alternative-graphical-representation:-icons-logos)

2. [4.8.1.1.6 A graphical representation of some of the surrounding text](https://dev.w3.org/html5/spec-LC/embedded-content-1.html#a-graphical-representation-of-some-of-the-surrounding-text)

3. And several other situations.

You can search that page for alt="" to show examples of encouraged usage of the empty (but not omitted!) `alt` property.

---

However there is one situation where there is no excuse for empty alt tags:

> When an [a](https://dev.w3.org/html5/spec-LC/text-level-semantics.html#the-a-element) element that creates a [hyperlink](https://dev.w3.org/html5/spec-LC/links.html#hyperlink), or a [button](https://dev.w3.org/html5/spec-LC/the-button-element.html#the-button-element) element, has no textual content but contains one or more images, the [alt](https://dev.w3.org/html5/spec-LC/embedded-content-1.html#attr-img-alt) attributes must contain text that together convey the purpose of the link or button.
>
> [4.8.1.1.2 A link or button containing nothing but the image](https://dev.w3.org/html5/spec-LC/embedded-content-1.html#a-link-or-button-containing-nothing-but-the-image)

---

A lighter requirement, html-proofer does not need to support accessibility standards to have this issue be in-scope. Instead html-proofer only needs to support HTML standards (which it does) to have this issue be in-scope.

Therefore, flagging `alt=""` indiscriminately as an error is incorrect.

**Comment by gjtorikian** [comment]
I consulted with a friend on the accessibility concerns and have come to conclude that I agree with you.
