### ISSUE TITLE
External Link Checking - Timeouts

### ISSUE THREAD

**Issue by fniephaus** [gjtorikian/html-proofer#231]
Hi folks,

I'm using `html-proofer` to test a website automatically on [Travis CI](https://travis-ci.org/).
Unfortunately, the builds are timing out because the external link checking process is taking to long.
Here's an example:
https://travis-ci.org/squeak-smalltalk/squeak.org/builds/72423569#L236

There are two possible solutions that I can think of:
1. Display progress information (Travis builds fail if there's no output being generated in 10min)
2. Add a `--timeout` option. If a web requests takes longer, print a warning but continue.

Feedback?

Best,
Fabio

**Comment by penibelst** [comment]
Proofer includes Typhoeus which already provides a `timeout` (seconds) and a `verbose` option.

```ruby
HTML::Proofer.new("out/", {
  :typhoeus => { 
    :timeout => 5,
    :verbose => true }
}).run
```

**Comment by fniephaus** [comment]
Thanks!

**Comment by fulldecent** [comment]
Are there any tricks, like environmental variables, to do this configuration on the command line?
