### ISSUE TITLE
Ignore script templates

### ISSUE THREAD

**Issue by akshayrawat** [gjtorikian/html-proofer#233]
Is it possible to ignore script templates just like HTML5 tags which aren't supported by Nokogiri/libxml2? Or is there another workaround to ignore errors on these snippets?

```html
<script type="text/html">
   <li></li>
</script>

<script type="text/x-handlebars-template">
   <li></li>
</script>
```

Error:

>  *  Element script embeds close tag

Its very common for frameworks ([Ember](http://guides.emberjs.com/v1.10.0/templates/handlebars-basics/#toc_defining-templates), [Knockout](http://knockoutjs.com/documentation/template-binding.html#note-1-rendering-a-named-template) etc.) to have html fragments as script text templates.

**Comment by gjtorikian** [comment]
You can add the `data-proofer-ignore` attribute to any tag to ignore it: https://github.com/gjtorikian/html-proofer/blob/master/README.md#ignoring-content

Would that work?

**Comment by akshayrawat** [comment]
I tried a few things, and that doesn't work

```html
<script type="text/html" id="navbar-logged-in" data-proofer-ignore>
    <li><a href="https://www.clerky.com/features">Home</a></li>
</script>
```

and

```html
<script type="text/html" id="navbar-logged-in" data-proofer-ignore>
    <li><a href="https://www.clerky.com/features" data-proofer-ignore>Home</a></li>
</script>
```

**Comment by penibelst** [comment]
@akshayrawat What are the options you pass to Proofer?

**Comment by akshayrawat** [comment]
```ruby
task :html_proofer do
  HTML::Proofer.new(
    "./build",
    {
      check_favicon: true,
      check_html: true #Yep

      parallel: {
        in_processes: 3
      }
    }
  ).run
end
```

**Comment by gjtorikian** [comment]
Well hot diggity. I can reproduce this.

**Comment by publicarray** [comment]
Has something changed? I received `Element script embeds close tag (line 129)` with `htmlproof ./_site --check-html --ignore-script-embeds --disable-external --url-ignore "#"` and with
```
<script data-proofer-ignore>
window.onload = function init() {
    var quiz1 = new dragDropQuiz({
        trailMode: false,
        alertResult: true,
        infoWrong: 'You can catch up on the Solar System <a href="/solar-system.html">here</a>.',
    });
};
</script>
```
