### ISSUE TITLE
Tests take long when checking external links

### ISSUE THREAD

**Issue by msh100** [gjtorikian/html-proofer#237]
Hello,

We have 300 external links at the moment, ergo our HTML proofer test takes a few minutes, is there a way of including a list of known working links? Extending that, can we produce a list of working links when we run HTML proofer?

The idea is once a link has been tested, it is then "known" to be working for X hours before we test that specific link again.

Thanks!

**Comment by gjtorikian** [comment]
> The idea is once a link has been tested, it is then "known" to be working for X hours before we test that specific link again.

Indeed, I've been wanting this myself. I can't promise when I'll get around to implementing it but I think it's a great idea.

**Comment by penibelst** [comment]
This would be a huge step towards regular monitoring of web sites.

I have another proposal for fast dayly checks. We could introduce a random sample option that accepts integers or percentage values. It's easy to implement.

Example: I have a folder with 1000 HTML documents. I run Proofer with `:random=>0.05`. It peaks randomly 50 documents and checks only those.

External links break in an unpredictable way, you never know what happens next. Random samples seams good enough to me.

**Comment by dsernst** [comment]
What about writing the results to file like `.htmlproof_log` with the date the link was checked? Then the user can pass an option like `--check-links-after 30-days`

**Comment by penibelst** [comment]
@dsernst An url log file would make the results shareable. I like it.

**Comment by penibelst** [comment]
What I like about the random sample method is its independence. It's important for public Travis users, who cannot easily cache results between runs.

**Comment by msh100** [comment]
For me, I feel like random would be quite useless. The aim is to catch links as they break or to check newly added links. By being random it could skip both and I therefore would not use it.

**Comment by penibelst** [comment]
I think it's time to calculate some probabilities. I will be back with numbers.

**Comment by dsernst** [comment]
@penibelst: Travis can read from a log file no problem. Writing to the log file without it being blown away each time when the container destroys itself is a bit harder, but [not](http://stackoverflow.com/a/23321942/2348750) [impossible](http://stackoverflow.com/a/18029286/2348750).

**Comment by msh100** [comment]
@penibelst it doesn't matter if it is as high as 50/50 in my opinion. It's still dependant on chance.

**Comment by akoeplinger** [comment]
Caching the `.htmlproof_log` would be pretty easy on Travis: http://docs.travis-ci.com/user/caching

I'd prefer that solution over a random sample just based on the fact that I'd constantly think "what if the random picker didn't check this one important link for a long time?" => unreliable tests are the worst.

**Comment by gjtorikian** [comment]
There is no way I will include support for a random sampling of documents. If one wanted a random sampling, they could use [`sample`](http://ruby-doc.org/core-2.1.0/Array.html#method-i-sample):

``` ruby
HTML::Proofer.new(Dir.glob("**/*.html").sample(10)).run
```

@akoeplinger: caching on Travis only works for private repositories at this time.

I was chatting with @msh100 about this early last week and came upon a different caching strategy, using gists. For example, your .travis.yml could look like

``` yml
env:
  - HTML_PROOFER_GIST_ID=123456
```

And the HTML-Proofer configuration might be:

``` ruby
proofer.new("./out", { :gist_id => ENV['HTML_PROOFER_GIST_ID'])
```

From [GitHub's API docs on gists](https://developer.github.com/v3/gists/):

> You can read public gists and create them for anonymous users without a token

There's still a bit of work to be done, but I think that using gists to share "state" between builds make the most sense.

**Comment by akoeplinger** [comment]
> @akoeplinger: caching on Travis only works for private repositories at this time.

@gjtorikian It works on the public [container-based](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) infrastructure too, which is the new default environment afaik so unless you rely on sudo in your build there's no blocker there. The gist solution sounds interesting but a little complicated compared to the file cache to me.

**Comment by gjtorikian** [comment]
Interesting, that's good news. The only problem there then is the outright dependency on using Travis. I'd prefer the feature not to be tied to just one CI system.

Anyway, rest assured I'm looking into this.

**Comment by dsernst** [comment]
Cool, that's fantastic. 

Is the idea that `GIST_ID` would act like an index for that user? Then `proofer` will update the log by [forking the gist](https://developer.github.com/v3/gists/#fork-a-gist), and read from the log by [looking for the newest fork](https://developer.github.com/v3/gists/#list-gist-forks)?

**Comment by penibelst** [comment]
@gjtorikian If one passes an array to the constructor, Proofer treats it as an array of links.

**Comment by msh100** [comment]
As I said to @gjtorikian before: It may be possible to not only sent a Gist ID, but also API credentials.

That way the Gist can be private (for whatever reason) and it also allows HTML proofer to edit said Gist, ergo a new Gist ID would not need to be provided to HTML Proofer on subsequent tests.

**Comment by penibelst** [comment]
What about making the caching functionality a plugin? We can introduce an option `url_cache`, that accepts an object with methods:

* load
* save
* add(url)
* contains?(url)

Then users can pass such an instance to Proofer:

```ruby
require "html/proofer"
require "gist-url-cache" #plugin
gist = GistUrlCache.new(:id => 123)
HTML::Proofer.new("./out", {:url_cache => gist}).run
```

**Comment by gjtorikian** [comment]
@akoeplinger I've been playing around with Travis' cache, and you're right: sudoless projects can use the feature as well. @msh100 Does that work for y'all?

Jenkins also keeps build artifacts around, so writing to a file works for us here at GitHub too. I've got some basic mechanisms in place; I think I'll try that format first, and then switch to experimenting with gists down the road.

**Comment by akoeplinger** [comment]
@gjtorikian sounds great :) if you have the file in place, uploading that one as a gist should be relatively easy.

**Comment by msh100** [comment]
@gjtorikian the only issue I can see with this is we'd have to trigger a build with travis in order to link check. If that isn't done for a couple of days (for example over the weekend), the first build on Monday will take a while. If all the links become stale at the same time, of course it helps if a lot of builds go on but there's always going to be that time where a build takes a while.

Having somewhere "remote" to Travis optional so that we can keep testing these links in the background somewhere eliminates this potential issue.

I am sure there's a way of grabbing the file from Travis, and over-writing the cache in order to handle link checking elsewhere - so maybe my concerns don't really matter too much.

As @akoeplinger said, it's also possible to do this and think about a Gist style feature in the future.
