### ISSUE TITLE
Drop `verbose` in a future release

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/html-proofer#240]
The way it's implemented right now is dumb:

``` ruby
log_level = verbose ? :debug : :info
```

Proofer can now only log in `:debug` or `:info`. Instead the user should be able to dictate the logging level. If no level is given, stick to `:info`. Otherwise, take what you're asked.

**Comment by fulldecent** [comment]
TL;DR:

Replace

`htmlproof --verbose`

with

`htmlproof --verbosity=debug`

Other options are `:debug` `:info` `:warn` `:error` `:fatal`

**Comment by gjtorikian** [comment]
Closed by HTMLProofer 3.0: https://github.com/gjtorikian/html-proofer/releases/tag/v3.0.0
