### ISSUE TITLE
Error:  `@shot.' is not allowed as an instance variable name

### ISSUE THREAD

**Issue by wjdp** [gjtorikian/html-proofer#245]
Getting error when running on my site

```
bundle exec htmlproof _site
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] checks on _site on *.html... 


htmlproof 2.5.1 | Error:  `@shot.' is not allowed as an instance variable name
```

I can't find any references to `@shot` in my code, htmlproofer works on other sites.

When running verbose execution stops at this stage, however the file it stops at is not constant.
 
```
Checking linkcheck on _site/years/12_13/red/index.html ...
Checking imagecheck on _site/years/12_13/committee/index.html ...
Checking imagecheck on _site/years/12_13/red/index.html ...
htmlproof 2.5.1 | Error:  `@shot.' is not allowed as an instance variable name
```

Build can be viewed here: https://travis-ci.org/newtheatre/history-project/builds/80719789

**Comment by gjtorikian** [comment]
This is a tricky one, but it looks like your HTML file is being built incorrectly.

To find this, I did a search for `shot.` on your HTML files. That led me to *the_pillowman/index.html*. If I open up that file, I see:

``` html
      <div class="show-photo-single debug-container">
        <a class="fancybox" rel="photos" href="/images/for_shows/pillowman_crew.jpg" title="Cast and Crew shot. From back left: Jess Courtney, Gareth Morris, Livvy Hobson, Dan O'Connor, Charlotte Ball, Jacob Hayes, James McAndrew, Nick Stevenson, Chelsea Jayne Wright, Emily Heaton. Bottom from left: Sam Haywood, Will Randall, Alex Hollingsworth">
          <img src="/images/resized/for_shows/pillowman_crew-300x.jpg" alt="Show photo" title Cast and Crew shot. From back left: Jess Courtney, Gareth Morris, Livvy Hobson, Dan O'Connor, Charlotte Ball, Jacob Hayes, James McAndrew, Nick Stevenson, Chelsea Jayne Wright, Emily Heaton. Bottom from Sam Haywood, Will Randall, Alex Hollingsworth >
          <div class="debug-abs-bottom-left" data-debug-toggle title="Photo type">photo</div>
          <div class="debug-abs-top-left" data-debug-toggle title="Photo image">pillowman_crew.jpg</div>
        </a>
      </div>
```

Do you see it? In the `img` tag, after `alt="Show photo"`, the `title` attribute is not properly building to `title="Cast and Crew shot...."`. That's where the error is coming from.

**Comment by wjdp** [comment]
Awesome, thanks for taking the time to look at this!

**Comment by wjdp** [comment]
Related, should htmlproofer throw a more useful error for events like this. The program doesn't even return error.

**Comment by gjtorikian** [comment]
Yeah, I think at the least it should tell you the file name. I'll make a note to fix that.
