### ISSUE TITLE
Rename `htmlproof` to `htmlproofer`

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/html-proofer#246]
This will be a breaking change.

**Comment by penibelst** [comment]
Do you want to talk about the future API changes?

**Comment by gjtorikian** [comment]
Sure, open issues if you have strong feelings.

**Comment by gjtorikian** [comment]
Closed by HTMLProofer 3.0: https://github.com/gjtorikian/html-proofer/releases/tag/v3.0.0
