### ISSUE TITLE
Incremental output

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#247]
The program can take a very long time to run.

I am requesting that all (most) output including errors be sent to STDOUT and sent without buffering.

On a large website, this command will take over 60 minutes without producing any output for me.

**Comment by penibelst** [comment]
Did you try the `verbosity` [option](https://github.com/gjtorikian/html-proofer/blob/master/README.md#logging)?

**Comment by fulldecent** [comment]
Works great, thanks! This gives me something to look at for those hours, and it stops Travis from complaining.
