### ISSUE TITLE
html-proofer should eat Typhoeus exceptions

### ISSUE THREAD

**Issue by getaaron** [gjtorikian/html-proofer#248]
In [`url_validator.rb`](https://github.com/gjtorikian/html-proofer/blob/704fd29c26abeae6c5748d705e7608af48b7295b/lib/html/proofer/url_validator.rb#L99-L103), `url_processor` calls this method in an `each_pair` loop:

```ruby
def queue_request(method, href, filenames)
  request = Typhoeus::Request.new(href, @typhoeus_opts.merge({ :method => method }))
  request.on_complete { |response| response_handler(response, filenames) }
  hydra.queue request
end
```

Typhoeus will raise an exception on a bad URL, such as `http://127.0.0.1:____`. When this happens, html-proofer will not test any future docs.

- Is it possible to wrap this in `begin…rescue`?
- Alternatively, can html-proofer validate a URL before passing it in?

I think a mangled URL shouldn't halt html-proofer.

I just started using html-proofer today, so if there's an option I'm missing or something else I'm overlooking, please let me know.

**Comment by gjtorikian** [comment]
There's no option to ignore this currently, but I agree that it should not explode everything. I'll make a fix. Thanks!
