### ISSUE TITLE
HTML5 allows omitting anchor href, html-proofer does not.

### ISSUE THREAD

**Issue by nkuehn** [gjtorikian/html-proofer#254]
Hi, 
it would be good if html-proofer would allow omitting the href attribute on <a> tags when doctype is HTML 5. 
The spec ( http://www.w3.org/TR/html5/text-level-semantics.html#the-a-element ) explicitly allows it:

> If the a element has no href attribute, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant, consisting of just the element's contents.

When implementing javascript driven links this behavior currently forces to use either href="#" (which spams the history and jumps to the top of the page) or href="javascript:;", which is an ugly workaround) and ignore these via href_ignore.

**Comment by gjtorikian** [comment]
I have implemented a fix for this: https://github.com/gjtorikian/html-proofer/compare/ignore-href-for-html5

I'm trying to think about how to best roll this out. I'm sure there are HTML5 users who *want* to be notified if an anchor is missing an href. I guess this will need to be a new option, but I'm not sure if it should default to following the spec or reporting the missing attribute.

**Comment by nkuehn** [comment]
+1, thanks!   Behavior is a tricky thing indeed. 

To me it looks like you're stuck between strictness (stricly adhering to the HTML spec) and backwards compatibility (existing users expect the proofer to find these things).  Configuration hell ahead, a new HTML validation rule could be  a way to do it.   You seem to have plans to change the `href_ignore` parameter anyways, maybe that's a chance to add a kind of special value that instructs the validation to ingnore completely missing href, too.

**Comment by gjtorikian** [comment]
Yeah, my main thinking is to add a new `strict` option as a catch-all for these sorts of things. I would probably then drop `check_html` since that would also fall under "strict spec checking."
