### ISSUE TITLE
Empty hash in URL

### ISSUE THREAD

**Issue by iBobik** [gjtorikian/html-proofer#255]
Should be `<a href="#">` really be reported as a non-existing hash?

It is often used for resetting hash in sites where hash is used to some changes in content, e.g. tabs and AJAX-loaded content.

Workaround is this parameter: `--href-ignore "#"`

**Comment by akoeplinger** [comment]
I agree: https://github.com/gjtorikian/html-proofer/issues/118 :) Maybe it's time to ignore this by default?

**Comment by iBobik** [comment]
Sorry, I did not found #118. Yes, default values should be friendly.

**Comment by gjtorikian** [comment]
How do you both feel about an implementation of https://github.com/gjtorikian/html-proofer/issues/254 (that is, `a` without `href`)?

**Comment by iBobik** [comment]
#254 is something different. `<a href=„#”` is needed for example to close
popup triggered by hash and many other frontend techniques.



Jan Pobořil

2015-11-03 19:30 GMT-06:00 Garen Torikian <notifications@github.com>:

**Comment by akoeplinger** [comment]
Yeah, I agree, that's something different.

**Comment by iBobik** [comment]
In other words, `<a>` is just general inline element like `<span>`, but <a
href=„#”>` is link to empty hash.



Jan Pobořil

2015-11-03 19:58 GMT-06:00 Alexander Köplinger <notifications@github.com>:

**Comment by gjtorikian** [comment]
> Sorry, I did not found #118. Yes, default values should be friendly.

My problem with `<a href="#">` is that it's too close to "dummy text" someone might write. For example, if we're going to use Bootstrap as an example, [here's some code from their docs](http://getbootstrap.com/css/#anchor-element) that uses `#` as a placeholder. 

Although I understand that ignoring `#` may seem like a sane default 98% of the time, the fact is, if you are intentionally adding `href="#"` in your code, I think proofer should explicitly be told to ignore that link, whether through the `data-proofer` attribute or through using `href-ignore`. The alternative is much worse, of someone accidentally adding `href="#"`, never realizing it, and having proofer pass.

Given that it's a common request, though, would not using `href-ignore` but acceptable, and instead a new option of `allow-hash-href`s be fine? Sort of like a shortcut to `href-ignore`, but just as a boolean.

**Comment by akoeplinger** [comment]
> Given that it's a common request, though, would not using href-ignore but acceptable, and instead a new option of allow-hash-hrefs be fine? Sort of like a shortcut to href-ignore, but just as a boolean.

That'd work for me.
