### ISSUE TITLE
git error

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#258]
When running html-proofer in a non-git directory, the following error is produced:

> Williams-iMac:Sites williamentriken$ htmlproof 
> fatal: Not a git repository (or any of the parent directories): .git

**Comment by fulldecent** [comment]
I think the error is caused here 

https://github.com/gjtorikian/html-proofer/blob/1aef3dcd9c1fec53b31bde99b7c63bc7c11473c9/html-proofer.gemspec#L15

**Comment by fulldecent** [comment]
Some advice here: https://stackoverflow.com/questions/2180270/check-if-current-directory-is-a-git-repository

**Comment by gjtorikian** [comment]
Gross! Sorry I'll fix this soon.

**Comment by gjtorikian** [comment]
I dug into this a bit and it looked like the problem was fixed in `bundler` versions 1.3 and higher.

Can you confirm you're on a newer bundler? `bundler -v` in your terminal should tell you what you're using.

**Comment by fulldecent** [comment]
I do not have bundler installed. Or if I do, I don't have the command line version available.

![screen shot 2015-11-05 at 11 11 06 pm](https://cloud.githubusercontent.com/assets/382183/10989221/82635ace-8412-11e5-8e80-b546e7a25f91.png)

**Comment by fulldecent** [comment]
Nice, thank you
