### ISSUE TITLE
Add "directory-index" setting

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#259]
I see many of these errors when running html-proofer:

  *  internally linking to /, which does not exist (line 28)

This is because a page links to `/` but the server serves this request with index.html.

A setting `directory-index` that accepts an array of values would fix this. A reasonable default for this parameter would be:

    index.html index.htm index.php index.asp index.pl

**Comment by gjtorikian** [comment]
We actually have this option, called `directory_index_file`; check the README for more information. Is it not working out for you? The default is *index.html*.

**Comment by fulldecent** [comment]
Ok, the problem was I have one is index.html and one is home.html.

I am too weird and will fix my setup to just use one directory_index_file.

Thank you
