### ISSUE TITLE
Using htmlproof with Jekyll's baseurl

### ISSUE THREAD

**Issue by nasht00** [gjtorikian/html-proofer#266]
I am using Jekyll to build my site.

All my images, links, etc, use a variable called `site.baseurl`. eg:

`<link href="{{site.baseurl}}/lib/bootstrap/css/bootstrap.css" rel="stylesheet">`

When generated it looks like:

`<link href="/MFPSamples/lib/bootstrap/css/bootstrap.css" rel="stylesheet">`

When htmlproof runs on it, I get:

`*  internally linking to /MFPSamples/lib/bootstrap/css/bootstrap.css, which does not exist (line 18)`

I tried to use `href-swap` but the new string value to give is not clear.
Using `--href-swap \/MFPSamples\/:` replaces with empty string, which means it translates to `lib/bootstrap/css/bootstrap.css`, which is a relative link, which is not always valid depending where you are.

Trying `--href-swap \/MFPSamples\/:/` gives an error `htmlproof 2.5.2 | Error:  undefined method `split' for /MFPSamples\/:/:Regexp`

**Comment by nasht00** [comment]
OK I found part of the answer:
`--href-swap \/MFPSamples:` seems to work around the issue.

However it does not seem to apply it to scripts.

**Comment by afeld** [comment]
> [`hrep-swap`] does not seem to apply it to scripts

See https://github.com/gjtorikian/html-proofer/issues/219 – https://github.com/jekyll/jekyll/issues/4122#issuecomment-159439360 was a good workaround in the meantime though.

**Comment by gjtorikian** [comment]
I can't make Proofer work with Jekyll's `{{ site.baseurl }}`, because I don't want to deal with parsing links and rewriting them to match the value in a specific *_config.yml* file. However, the change to get this working for `script`s is completed for Proofer 3.0. When that's out, this should be fixed. Keep track of #219 for more info on that.

**Comment by Merovex** [comment]
Adding a comment if anyone is looking for this in 2020. I have run a blog for the better part of 9 years, and completely overlooked the use of `{% site_url name-of-blog-post %}`, which when included in a markdown article will yield the correct URL. As of Jekyll 4.0, use of `post.url` does not need the basename to properly render. So, by removing the baseurl and fixing my links, I was able to quiet 193 false-positive links in my blog.
