### ISSUE TITLE
--url-swap keys can't contain colon

### ISSUE THREAD

**Issue by johnzeringue** [gjtorikian/html-proofer#293]
Looking at [bin/htmlproof](https://github.com/gjtorikian/html-proofer/blob/master/bin/htmlproof), it's obvious that something like shown [here](http://tongueroo.com/articles/getting-html-proofer-to-work-with-canonical-url-for-google-seo/) is not possible from the command line, because the command line client simply splits each key-value pair on `:`, taking just the protocol from any URI key and prefixing the intended value.

I propose using `\` as an escape character and supporting `\:` and `\\` as escape sequences. This allows for colons and backslashes in both keys and values. The command line equivalent of the Ruby code in the article would then be `htmlproof --url-swap http\://tongueroo.com: ./_site`.

@gjtorikian, if you're okay with this solution, I'd be glad to make a pull request.

**Comment by gjtorikian** [comment]
Sounds great to me!

It would be extremely helpful if you make this change against the up-and-coming 3.0 branch: https://github.com/gjtorikian/html-proofer/tree/proofer-three-oh

*A lot* of the internals have changed, compared to what's on `master`.

**Comment by udiboy1209** [comment]
Has this been fixed? In what version, and when will it be released. really need this feature !

**Comment by gjtorikian** [comment]
I was waiting for a PR from @johnzeringue, I don't think it is fixed yet.

**Comment by johnzeringue** [comment]
I'll work on it this afternoon. Sorry, I've been busy.

**Comment by gjtorikian** [comment]
No worries! Me too!

**Comment by udiboy1209** [comment]
@johnzeringue nice! do tag me in the PR you open so I can follow it :)!
