### ISSUE TITLE
Truly disable caching

### ISSUE THREAD

**Issue by Tuckie** [gjtorikian/html-proofer#294]
Why does html-proofer still create a a tmp directory & cache file when caching is not used?  Would it be possible only create & write to these when the `:cache` option is used?

**Comment by Tuckie** [comment]
Great, thank you!

**Comment by gjtorikian** [comment]
Closed by HTMLProofer 3.0: https://github.com/gjtorikian/html-proofer/releases/tag/v3.0.0

**Comment by Tuckie** [comment]
It's working great, thanks!
