### ISSUE TITLE
Recent Travis failures

### ISSUE THREAD

**Issue by lurch** [gjtorikian/html-proofer#299]
Hello,

We've got html-proofer integrated with https://github.com/raspberrypi/documentation but recently we're seeing an awful lot of Travis build failures, when it shouldn't be failing.
https://travis-ci.org/raspberrypi/documentation/builds
https://travis-ci.org/raspberrypi/documentation/pull_requests
(it seems to be failing when checking external links)

Not being familiar with html-proofer or the inner-workings of Travis, I dunno if this is a fault with html-proofer, or Travis? Anything we can do to mitigate the situation?

**Comment by wjdp** [comment]
Having a quick look I found a lot of attempted links to `Readme.md` - probably rather than `.html` and problems checking links on http://elinux.org

```
- ./_build/configuration/config-txt.md
  *  External link http://elinux.org/RPI_safe_mode failed: response code 0 means something's wrong
  *  External link http://elinux.org/RPiconfig failed: response code 0 means something's wrong
  *  External link http://en.wikipedia.org/wiki/Coordinated_Video_Timings failed: response code 0 means something's wrong
  *  External link http://en.wikipedia.org/wiki/Extended_display_identification_data failed: response code 0 means something's wrong
  *  External link http://en.wikipedia.org/wiki/Phase-locked_loop#Clock_generation failed: response code 0 means something's wrong
- ./_build/configuration/device-tree.md
  *  External link http://elinux.org/images/4/48/Experiences_With_Device_Tree_Support_Development_For_ARM-Based_SOC's.pdf failed: response code 0 means something's wrong
- ./_build/configuration/raspi-config.md
  *  External link http://elinux.org/RPi_raspi-config failed: response code 0 means something's wrong
- ./_build/hardware/raspberrypi/gpio/README.md
  *  External link http://elinux.org/RPi_Low-level_peripherals failed: response code 0 means something's wrong
- ./_build/hardware/raspberrypi/spi/README.md
  *  External link http://elinux.org/BCM2835_datasheet_errata failed: response code 0 means something's wrong
  *  External link http://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus failed: response code 0 means something's wrong
- ./_build/installation/installing-images/windows.md
  *  External link http://elinux.org/RPi_Easy_SD_Card_Setup failed: response code 0 means something's wrong
- ./_build/installation/noobs.md
  *  External link http://osmc.tv/ failed: response code 0 means something's wrong
- ./_build/remote-access/vnc/README.md
  *  External link http://elinux.org/RPi_VNC_Server failed: response code 0 means something's wrong
```

I've run in to similar problems checking LinkedIn links (see https://travis-ci.org/newtheatre/history-project/builds/105989100):

```
- ./_site/people/robyn_lawes/index.html
  *  External link https://www.linkedin.com/in/rml1007 failed: 999 No error
```

Which is a 999 rather than 0, neither of which are [valid or commonly used codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes). This may be an issue with websites blocking access to suspect User-Agent strings.

**Comment by lurch** [comment]
The lines mentioning README.md are just pointing out which files _contain_ the links, not which files are being linked _to_ ;-)  All our internal links are fine, it's only the external links which are failing.

> This may be an issue with websites blocking access to suspect User-Agent strings.

I guess if that was the cause, then **every** build would fail, whereas [we're seeing](https://travis-ci.org/raspberrypi/documentation/builds) some builds failing, and some builds passing, with no apparent reason for the different behaviours :-/

**Comment by gjtorikian** [comment]
I'm not quite sure if this is a Proofer problem or not. If there's been no change in Proofer, the change is either from Travis or from the erroring servers. It looks like these are coming from the same domains (`http://elinux.org`). I'll keep this issue open, but other than ignoring those links, I am not sure what a fix could be. 

The `wikipedia` ones can probably change to `https`; I've seen that fix the problem before. Usually it happens for servers that don't properly resolve from `http` to `https`.

**Comment by gjtorikian** [comment]
Could you try HTMLProofer 3.0 and reopen if this is still a problem? Thanks!

**Comment by lurch** [comment]
Any idea what's going on here? https://travis-ci.org/raspberrypi/documentation/builds/114788808

**Comment by gjtorikian** [comment]
@lurch Yep. In 3.0 the library was renamed to `require 'html-proofer'`. This is much more inline with other Ruby libraries.

**Comment by gjtorikian** [comment]
There are some release notes on this if it is helpful: https://github.com/gjtorikian/html-proofer/releases/tag/v3.0.0

Sorry for the inconvenience!

**Comment by lurch** [comment]
Well that's got us a bit further... but now there's a different error
https://travis-ci.org/raspberrypi/documentation/builds/114940114

**Comment by gjtorikian** [comment]
I highly recommend you change your Gemfile to use semantic versioning: https://robots.thoughtbot.com/rubys-pessimistic-operator

HTML-Proofer 3.0 intentionally broke a lot of syntaxes (all at once), so that I wouldn't need to break them again in the future (it's a three-year old project, so there was a lot of cruft).

I can see that [this line](https://github.com/raspberrypi/documentation/blob/7a8b1154f251214fee57b0dd0ef360b4b92bcfde/Rakefile#L37) probably needs changing to:

``` ruby
HTMLProofer.check_directory(BUILD_DIR, { :ext => ".md", :directory_index_file => "README.md" }).run
``` 

Have you tried running the tests locally before pushing up to Travis?

**Comment by lurch** [comment]
> I highly recommend you change your Gemfile to use semantic versioning:

Afraid I wouldn't know how to, or even what versions to select.

> I can see that this line probably needs changing to:

I tried that, but still get the error as last time https://travis-ci.org/raspberrypi/documentation/builds/114948053

> Have you tried running the tests locally before pushing up to Travis?

Afraid I wouldn't know how to. Travis-integration was added to https://github.com/raspberrypi/documentation by @penibelst
https://github.com/raspberrypi/documentation/commit/57d9dc873f25d5a6ec041703395680375f1a1f7f
and I've simply been doing my best to keep it working:
https://github.com/raspberrypi/documentation/issues/104
https://github.com/raspberrypi/documentation/commits/master/Rakefile

**Comment by lurch** [comment]
Fixed in https://github.com/raspberrypi/documentation/pull/323
Thanks!

**Comment by lurch** [comment]
Hmmm, https://travis-ci.org/raspberrypi/documentation/builds/114961185 only had 2 failures, but after I merged it https://travis-ci.org/raspberrypi/documentation/builds/115010505 now has 17 failures??

**Comment by markorapaic** [comment]
Hello, just came across these comments after I also received the dreaded `*  External link https://www.linkedin.com/in/markorapaic failed: 999 No error` - I found the solution by running `htmlproofer -help` - it was here I found the `--only-4xx` flag, which I added to the [jekyll instructions](https://jekyllrb.com/docs/continuous-integration/) I was using. This allowed me to by pass the error and build successfully - thought i'd just post this solution here incase anyone else encountered the same.
