### ISSUE TITLE
Do twice check on HTTP error

### ISSUE THREAD

**Issue by iBobik** [gjtorikian/html-proofer#310]
HTML proofer sometimes returns this error:

```
External link http://canikova.cz/ failed: response code 0 means something's wrong
```

It propably means linked website is hosted on some shitty hosting, so it sometimes not responds to request. But some websites do it often and it causes false alarm.

Feature request: If there is error on remote site, what about to try it once again a few seconds ago? If second try will be ok, there should not be error on output, so tests will pass.

**Comment by Tuckie** [comment]
This might be more flexible with `retry_attempts` and `retry_delay` parameters.

**Comment by fulldecent** [comment]
Perhaps this should be implemented upstream. A ticket is open at 

https://github.com/typhoeus/typhoeus/issues/182

I am not sure if retry should be in scope for implementing in this project.

**Comment by gjtorikian** [comment]
I agree. This is something that Typheous will need to support first.

**Comment by iBobik** [comment]
@gjtorikian When Typheous will start support it, will HTML proofer do it by default? If not and there will be needed some work, this issue should be left open.

**Comment by gjtorikian** [comment]
> When Typheous will start support it, will HTML proofer do it by default?

In theory, yes. HTML-Proofer [just blindly passes over](https://github.com/gjtorikian/html-proofer/blob/5d43b806a8eac86827e563eb47e553eb9bffaa54/lib/html-proofer/runner.rb#L12) the Typheous/Hydra config options. It doesn't do any validation there or extra checks. So if an option is made available for Typheous, passing it through should be fine.

**Comment by vsoch** [comment]
This issue is closed, but I'm hugely in support of retry parameters. Our builds are consistently failing on travis because of one spurious URL error.

**Comment by gjtorikian** [comment]
If so then the issue should be bumped on Typheous, as noted above. This gem depends on that one for external calls.
