### ISSUE TITLE
No support for multiple URLs in srcset

### ISSUE THREAD

**Issue by alexpls** [gjtorikian/html-proofer#313]
Part of the HTML 5.1 spec defines the `srcset` attribute on `img` elements where multiple URLs can be specified on one `img` to use in different situations (high pixel density displays, small monitors, etc).

An example of this taken from the [draft w3c spec](http://w3c.github.io/html/semantics-embedded-content.html) looks like:

``` html
<img src="/uploads/100-marie-lloyd.jpg"
      srcset="/uploads/150-marie-lloyd.jpg 1.5x, /uploads/200-marie-lloyd.jpg 2x"
      alt="" width="100" height="150">
```

As far as I can see html-proofer does not support multiple URLs defined inside a `srcset` attribute.

See the draft spec here: http://w3c.github.io/html/semantics-embedded-content.html, and note srcset is already supported in the majority of modern browsers already: http://caniuse.com/#search=srcset

If support for this is something you think is worth including on html-proofer let me know and I'd be happy to work on it and make a pull request!

**Comment by fulldecent** [comment]
I'd like to see a device with 1.5x pixel density.

Yes, I think this is valid and in-scope for the project.
