### ISSUE TITLE
Lots of noise, unclear how to quiet

### ISSUE THREAD

**Issue by bogosj** [gjtorikian/html-proofer#315]
Since the version bump I've noticed a ton of noise (lines 223-742)
https://travis-ci.org/rutherford-nj/www.rutherford-nj.com/builds/114124870

This was not here in previous builds:
https://travis-ci.org/KimBogosian/site/builds/113933279

**Comment by bogosj** [comment]
./script/cibuild contents were:
https://github.com/rutherford-nj/www.rutherford-nj.com/commit/1507f8d4e1d7e2189c104c5b63c7a7dd4910a2b4

**Comment by svendahlstrand** [comment]
Found the problematic line: https://github.com/gjtorikian/html-proofer/blob/master/lib/html-proofer/runner.rb#L103. I guess it could be logged with the debug level instead.

**Comment by gjtorikian** [comment]
Ugh so embarrassing. Removing ASAP.

**Comment by gjtorikian** [comment]
Removed in version 3.0.3. Sorry!

**Comment by bogosj** [comment]
Awesome, glad it wasn't me :)

**Comment by svendahlstrand** [comment]
Thanks @gjtorikian! :smile:
