### ISSUE TITLE
Build not works afer 3.0.3 

### ISSUE THREAD

**Issue by CGarces** [gjtorikian/html-proofer#316]
I have my Jekyll blog hosted at github integrated with codeship.com for Continuous Integration test.

My last build from 28 Feb. was Ok, but the build from today not works. I have changed a single line not related to the error.

The error is that the application not found the htmlproof executable.

```
/home/rof/.rvm/gems/ruby-2.2.0/gems/bundler-1.9.5/lib/bundler/rubygems_integration.rb:316:in `block in replace_bin_path': can't find executable htmlproof (Gem::Exception)
	from /home/rof/cache/bundler/bin/htmlproof:16:in `<main>'
```

The build at GitHub works. Only the one at codeship fails.

This is my gem file.
https://github.com/CGarces/CGarces.github.io/blob/master/Gemfile

```
source 'https://rubygems.org'
gem 'github-pages'
gem 'html-proofer'
gem 'jekyll-sitemap'
```

In the build information at https://codeship.com/projects/129605/builds/12806033

I see during the install

`Using html-proofer 3.0.3`

So html-proofer is installed... but not the command line tool?

**Comment by gjtorikian** [comment]
Yes, the tool was renamed to `bin/htmlproofer` to better match the name of the actually library. There are some release notes on this if it is helpful: https://github.com/gjtorikian/html-proofer/releases/tag/v3.0.0

Sorry for the inconvenience!
