### ISSUE TITLE
Replace Nokogiri with something that validates HTML5

### ISSUE THREAD

**Issue by episource** [gjtorikian/html-proofer#318]
# Description

html-proofer **3.0.4** reports `Unexpected end tag : address` when there's an unordered list inside `<address>`. It does not report an error when an ordered list is used instead. I also don't see a reason why unordered lists shouldn't be valid inside `<address>`. 

[W3C specifies](https://www.w3.org/TR/html5/sections.html#the-address-element) the address element's content model as:

> Flow content, but with no heading content descendants, no sectioning content descendants, and no header, footer, or address element descendants.

_Flow content_ includes `<ul>` and `<ol>`.
# Steps to reproduce
### 1. Input

``` html
<!DOCTYPE HTML>
<html>
    <head></head>
    <body>
        <address>
            <ul></ul>
        </address>
    </body>
</html>
```
### 2. htmlproofer

``` bash
$ htmlproofer --check-html _site/test.html
Running ["ScriptCheck", "LinkCheck", "ImageCheck", "HtmlCheck"] on _site/test.html on *.html...


Checking 0 external links...
Ran on 1 file!


- _site/test.html
  *  Unexpected end tag : address (line 7)
htmlproofer 3.0.4 | Error:  HTML-Proofer found 1 failure!
```

**Comment by episource** [comment]
This is due to the underlying nokogiri library not supporting html5. See also the upstream ticket sparklemotion/nokogiri#1348.

**Comment by gjtorikian** [comment]
> This is due to the underlying nokogiri library not supporting html5. See also the upstream ticket sparklemotion/nokogiri#1348.

Sadly, as this is the case, there's nothing the HTML checker here can do. Do you have any suggestions for a workaround I could implement? I'm coming up blank.

**Comment by episource** [comment]
[nokogumbo](https://github.com/rubys/nokogumbo) is a drop-in replacement for nokogiri with full html5 support - but sadly there's no validation support currently available. So this is no suitable alternative either.

It would be possible to separate html parsing and validation. In this case [validator.nu](https://github.com/validator/validator) could be used for validation. This is what I'm am doing currently: I disable html validation in html-proofer and run [validator.nu](https://github.com/validator/validator) as standalone step.

Concerning html-proofer I'd suggest adding a configuration option like `ignore_re` that permits specifying a list of regexes matching html validation / nokogiri error messages that shall be ignored.

**Comment by episource** [comment]
Now there's an active pull request adding error reporting / validation to nokogumbo:  [issue#19](nokrubys/nokogumbo#19), [pr#46](nokrubys/nokogumbo#46)

**Comment by peternewman** [comment]
The PR is in, but the issue isn't resolved.

Gumbo issue: https://github.com/google/gumbo-parser/issues/39

**Comment by fulldecent** [comment]
I like the larger scope of this issue: "Replace Nokogiri with something that validates HTML5."

I am sure people will report new issues if we don't change the title of this issue.

**Comment by gjtorikian** [comment]
This PR intended to do just that: https://github.com/gjtorikian/html-proofer/pull/362

But I could not accept it, because the replacement did not include line numbers in the errors: https://github.com/gjtorikian/html-proofer/pull/362#issuecomment-284108120

**Comment by fulldecent** [comment]
Hi everyone, just FYI, way way upstream there is a feature missing that we need to make html-proofer work with HTML5.

It is here https://github.com/sparklemotion/nokogiri/pull/1658

Referencing here just FYI so you know this is still alive and kicking.
