### ISSUE TITLE
Valid URL failing validation

### ISSUE THREAD

**Issue by themaninthesuitcase** [gjtorikian/html-proofer#323]
I've added a link with colons in it to a draft post on a jekyll site.  Currently this fails validation.  This seems to be down to the colons.  

The link in question is : https://overcast.fm/+CGRt2FEbw/1:17:15

I have researched it and it appears that these are valid characters in the position and the url works in Chrome, IE11 and Safari.

The error can be seen at this link : https://travis-ci.org/themaninthesuitcase/themaninthesuitcase.github.io/builds/118259215

```
- ./_site/2016/03/23/made-in-the-uk/index.html
  *  ​https://overcast.fm/+CGRt2FEbw/1:17:15 is an invalid URL (line 81)
- ./_site/index.html
  *  ​https://overcast.fm/+CGRt2FEbw/1:17:15 is an invalid URL (line 83)
htmlproofer 3.0.2 | Error:  HTML-Proofer found 2 failures!
```

Slightly off topic I am passing `--disable-external` so should this even be being validated or are external links still validated for format?

**Comment by gjtorikian** [comment]
> Slightly off topic I am passing --disable-external so should this even be being validated or are external links still validated for format

It shouldn't be validating external links. But I bet what's going on is that it in't recognizing URLs with `:`s as valid. I'll look into it.
