### ISSUE TITLE
More Working Examples of CLI Use

### ISSUE THREAD

**Issue by felicianotech** [gjtorikian/html-proofer#324]
I have the following command, `bundle exec htmlproofer jekyll/_site --allow-hash-href --check-favicon --check-html --empty-alt-ignore --http-status-ignore [999,401] --url-ignore "circleci.com"` that isn't working.

I can't seem to get `--url-ignore` or `--http-status-ignore` to work. I've tried several variations including with quotes, without quotes, with brackets, etc.

Most of the examples in the readme are via Ruby which doesn't help me much. Any ideas?

**Comment by gjtorikian** [comment]
Sorry it took so long to get to this! I've updated the README to show how these might work.

**Comment by felicianotech** [comment]
Thanks.
