### ISSUE TITLE
Rakefile for Jekyll uninitialized constant HTMLProofer

### ISSUE THREAD

**Issue by keegoid** [gjtorikian/html-proofer#326]
When I do this Travis CI says it doesn't know about the HTMLProofer object.

In .travis.yml:

```yml
script: bundle exec rake test
```

In Rakefile:

```ruby
require 'html-proofer'

task :test do
  sh "bundle exec jekyll build"
  HTMLProofer.check_directory("./_site").run
end
```

Also, how can I add a list of urls to ignore in the Rakefile? I know there's the url-ignore option, but don't know how to use it in the Rakefile. An example would be awesome.

Thanks for your help. I look forward to testing my project with html-proofer!
(I'm using a Rakefile because I also want to test code coverage with Codecov.)

**Comment by keegoid** [comment]
Oh, I think I see the problem. My code had:

```ruby
require 'html/proofer'
```

Could that be the issue?
I'm still stuck on how to ignore urls.

**Comment by gjtorikian** [comment]
Could I see your repository so that I might be able to offer more help? The link to the Travis CI build would also be helpful.

**Comment by keegoid** [comment]
Sure! I setup a branch for [testing html-proofer](https://github.com/keegoid/keegoid.github.io/tree/html-proofer).
Here's the [relevant test build](https://travis-ci.org/keegoid/keegoid.github.io/builds/120239204).

I've [switched to the bash method](https://github.com/keegoid/keegoid.github.io/blob/master/travis.sh) which works well with html-proofer, but it would be nice to know how to do it in a Rakefile as well.

**Comment by gjtorikian** [comment]
I wanted to look into this but it looks like the issue is fixed? At any rate, most of the links above have been removed, and _travis.sh_ has been removed.

Please reopen if this is still problematic.

**Comment by keegoid** [comment]
Thanks Garen, yes it appears to be fixed.

On Tue, May 17, 2016, 7:54 AM Garen Torikian <notifications@github.com>
wrote:

> Closed #326 <https://github.com/gjtorikian/html-proofer/issues/326>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gjtorikian/html-proofer/issues/326#event-662329640>
>
-- 
*Keegan Mullaney*
Programming and IT
Blog <http://keegoid.github.io/>  |  GitHub <https://github.com/keegoid>  |
Twitter <https://twitter.com/keegoid>  |  F4E5 B8C0
<https://keybase.io/keegoid>

Learning: Linux, Jekyll, Ruby, CI, Writing & Passive Income.

**Comment by kenman345** [comment]
Would love to know the fix.

**Comment by nadnoslen** [comment]
So I'm using `Ruby-2.3.7` & `Jekyll-3.8.3` -- had same problem

1. I didn't have a Rakefile in my Jekyll site; added one at the root of my project named `Rakefile`
1. Loaded `Rakefile` with the script found in this [README](
https://github.com/gjtorikian/html-proofer#using-with-jekyll)
1. Added `gem 'html-proofer'` to my Gemfile
1. **THE FIX FOR ME** had to add `gem 'rake'` to my Gemfile
1. `rake test` or `bundle exec rake test` now works

**Comment by johannesstricker** [comment]
I encountered the same error, but it was working fine locally and the error only occured on github actions. The fix was to add `gem 'rake'` to the Gemfile and run `bundle exec rake test` instead of `rake test`.
