### ISSUE TITLE
External Link test failing on Valid URL - ONLY on Travis server

### ISSUE THREAD

**Issue by ckreon** [gjtorikian/html-proofer#331]
So I have kind of a weird one here...

I have a Jekyll site that I verify with html-proofer on TravisCI before deployment.

Recently, a post was made to the site which contained a link to:  
http://whois.domaintools.com

Now - as far as I can tell, that's a perfectly valid link. I can visit it in a browser, and it even passes validation throught html-proofer in my local dev environment. But when I push that post up for deployment, the test fails on that link with this error:

```
[31m  *  External link http://whois.domaintools.com/ failed: got a time out (response code 0)
```

Any idea why this link would be specifically failing validation from the TravisCI servers?

EDIT: Here's the full log of the Travis build: https://s3.amazonaws.com/archive.travis-ci.org/jobs/130336308/log.txt

And here's the post in question causing the issue, the link has been removed so I'm showing it through the history view: https://github.com/ckreon/shadowlink-site/commit/fa0346662cbd5038823b354cffc239455436d3f0

**Comment by gjtorikian** [comment]
It might have been a purely temporary issue. The error message of `got a time out` implies that the server didn't respond in time. That could be Travis' fault (maybe the server running the command took to long to verify) or the fault of http://whois.domaintools.com/ (maybe it was overloaded and couldn't respond in time).

I'd suggest adding the link back to verify if it was a temporary issue.

**Comment by ckreon** [comment]
I re-enabled as you suggested, and oddly enough, it still fails.

I can verify that the link works fine in a normal browser, and that it passes html_proofer tests in a local environment. It's only failing on Travis CI...

https://travis-ci.org/ckreon/shadowlink-site/builds/146479987
