### ISSUE TITLE
How tu use url_ignore in command line?

### ISSUE THREAD

**Issue by jwillmer** [gjtorikian/html-proofer#333]
I try to exclude all relative urls and image alt tag tests but I can not figure out how to write it. (Without the ignore properties it works)

```
bundle exec htmlproofer ./_site --url_ignore [".*"] --alt_ignore [".*"]
```

The problem is that I can not test it on my Windows machine and travis-ci only outputs:

```
..exited with 1.
```

**Comment by peternewman** [comment]
I'd image the issue is going to be the escaping of the options. Have you tried turning up the logging with
`--log-level=:debug`

Also I've always used hyphens on the command line, I don't know if underscores work, so:
`bundle exec htmlproofer ./_site --url-ignore [".*"] --alt-ignore [".*"]`

**Comment by gjtorikian** [comment]
I _just_ updated the README to note this a few days ago: https://github.com/gjtorikian/html-proofer#using-on-the-command-line

Let me know if that doesn't help out and I'll try adding some more words!

**Comment by publicarray** [comment]
For future reference :`--url-ignore "/\.\//"` will ignore relative urls like `./file.html` and `../file.html` but not `/file.html` or `file.html`.
