### ISSUE TITLE
crawling sites

### ISSUE THREAD

**Issue by afeld** [gjtorikian/html-proofer#334]
The use case: I am trying to use the crawler to check for broken links on all pages of a live site. An example of what I tried:

```
$ htmlproofer www.aidanfeldman.com --as-links
Running ["ImageCheck", "ScriptCheck", "LinkCheck"] on ["www.aidanfeldman.com"] on *.html...


Checking 1 external link...
HTML-Proofer finished successfully.
```

There are multiple pages on that site, but `htmlproofer` seems to only be scanning the homepage, which I verified by looking at the logs. Is there a flag I'm missing, or is this not currently supported? Thanks!

**Comment by afeld** [comment]
Actually, I tried inserting a link to a fake domain and it still finished successfully...is `as-links` working at all?

**Comment by gjtorikian** [comment]
So `as-links` only checks whether or not links are valid. It does not crawl the site or check any of the data on the page. Crawling each link is probably out of scope for this project, but I think at least validating that images and other content on the links provided work probably makes sense.

As for the second question, here's what I tried:

```
➜  html-proofer git:(master) bin/htmlproofer www.aidanfeldman.com --as-links
Running ["ImageCheck", "LinkCheck", "ScriptCheck"] on ["www.aidanfeldman.com"] on *.html... 


Checking 1 external link...
HTML-Proofer finished successfully.
➜  html-proofer git:(master) bin/htmlproofer www.aidanfeldman.coasdasdadsadsadsadsasdasdasdm --as-links
Running ["ScriptCheck", "ImageCheck", "LinkCheck"] on ["www.aidanfeldman.coasdasdadsadsadsadsasdasdasdm"] on *.html... 


Checking 1 external link...
- 
  *  External link www.aidanfeldman.coasdasdadsadsadsadsasdasdasdm failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
htmlproofer 3.0.6 | Error:  HTML-Proofer found 1 failure!
```

I am not sure why it succeeded for you. Can you paste your command?

**Comment by fulldecent** [comment]
Recommending to close issue as out of scope. Recommend project scope at #422.
