### ISSUE TITLE
External links pointing to non-responsive servers cause stall

### ISSUE THREAD

**Issue by wjdp** [gjtorikian/html-proofer#340]
Checking an external link resulting in `Received a 0 for http://website/ in ./_site/page.html` caused a 10 minute stall in html-proofer.

Webserver is un-pingable, HTTP requests hang. Can html-proofer implement a timeout for these checks?

**Comment by gjtorikian** [comment]
Check this comment out: https://github.com/gjtorikian/html-proofer/issues/231#issuecomment-124820792

**Comment by wjdp** [comment]
Whoops, thanks though!
