### ISSUE TITLE
Travis and local runs of same version differ

### ISSUE THREAD

**Issue by davelab6** [gjtorikian/html-proofer#347]
https://travis-ci.org/sugarlabs/edit-fonts-activity/builds/143952694 is fails, but the same version succeeds locally:

    $ htmlproofer --version
    htmlproofer 3.0.6
    $ htmlproofer --disable-external _site/ --assume-extension 
    Running ["ImageCheck", "LinkCheck", "ScriptCheck"] on ["_site/"] on *.html... 
    Ran on 40 files!
    HTML-Proofer finished successfully.
    $

Any idea what's going on? : )

**Comment by nschonni** [comment]
Looking at the build, you didn't include the `files` directory, so the failures are because Jekyll hasn't copied it over to the `_site`. https://jekyllrb.com/docs/configuration/

**Comment by davelab6** [comment]
@nschonni ah yes, of course! Thank you so much for taking time to look into this for me, I super appreciate it!! :)
