### ISSUE TITLE
Relative links from index.html should fail

### ISSUE THREAD

**Issue by iBobik** [gjtorikian/html-proofer#348]
We have this files:
/index.html

```
<a href="/subdir">Subdir</a>
```

/subdir/index.html

```
<a href="file.pdf">File (will not work)</a>
<a href="/subdir/file.pdf">File (will work)</a>
```

/subdir/file.pdf

Relative links from index.html will not work, because browser seems url like /subdir. HTML Proofer checks all internal links without errors, but relative link like in example should fail.

**Comment by lurch** [comment]
AIUI, a link to "file.pdf" in the file "/subdir/index.html" *should* indeed resolve to "/subdir/file.pdf" - HTML links are relative by default. Unless of course you've got a "BASE HREF" directive in the HEAD of the page.

**Comment by gjtorikian** [comment]
I believe this was addressed.
