### ISSUE TITLE
Add setting for "internal" domains

### ISSUE THREAD

**Issue by Roang-zero1** [gjtorikian/html-proofer#349]
I've come across the issue that I have multiple links to my own domain with a full path (e.g. https://www.example.com/page2) which are basically internal, but html-proofer treats them as external.

Currently there is the option to use url-swap (from the master branch) and swap with the "https://www,example.com":"" regex.

Unfortunately my site will be multilingual so I would have to add a regex for each protocol and each domain connected to my site.

I would propose a configuration option, which allows for a set of urls which will be treated as internal, thereby removing the leading protocol and domain.

For example:
`htmlproofer --home-domains www.example.com, de.example.com`
`<a href="https://www.example.com/about">About</a>` would check `"/about"`
`<a href="http://de.example.com/about">About</a>` would also check `"/about"`

**Comment by gjtorikian** [comment]
Interesting. This shouldn't be too hard to implement, but I have a bit of a full plate right now because of work. 😓 

I'll keep this in mind if I have some free time but please ping me if it's been five months and I still haven't done anything. 😆
