### ISSUE TITLE
Array check in htmlproofer Line 51

### ISSUE THREAD

**Issue by Roang-zero1** [gjtorikian/html-proofer#352]
In the current [htmlproofer Line 51](https://github.com/gjtorikian/html-proofer/blob/3b5e23e1af56f9a54702ee5ab4ca75a6db18596f/bin/htmlproofer#L51) there is a check to see whether the option is an Array.

The value checked against is `option.return_type` which contains the class object, to check this the following code could be used:
` option.return_type == Object.const_get("Array")`

Alternatively the option itself can be checked with .is_a? Array:
`opts[option.config_key].is_a? Array`

**Comment by Roang-zero1** [comment]
For reference: The return_type value is assigned in [lib/mercenary/option.rb Line 17](https://github.com/jekyll/mercenary/blob/70c7c88e997558e890a5b9d190fd61227933a45a/lib/mercenary/option.rb#L17)

**Comment by gjtorikian** [comment]
Thank you!
