### ISSUE TITLE
Report if a link is going to redirect

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/html-proofer#353]

**Comment by jamietanna** [comment]
I'd be happy picking this up. Any thoughts on what output format you'd like for this, @gjtorikian?

**Comment by gjtorikian** [comment]
I think having it appear as an `INFO` log statement might be nice. As well, having an option like `--report-redirects` could also result in printing out the redirects, so that people who want to can also go back and fix redirected links into the right place.

**Comment by jamietanna** [comment]
From what it looks like, [typhoeus](https://github.com/typhoeus/typhoeus) would be handling the actual requests, so would that mean that we'd need to add the functionality to that?

**Comment by msh100** [comment]
It would be nice if this worked with https://github.com/jekyll/jekyll-redirect-from too. It would return a 200 but with a HTML meta redirect.

Maybe this could be more generalised and look for pages which link to pages with a certain string match in them.

**Comment by fulldecent** [comment]
I think checking redirect by HTTP code is in scope but anything else is out of scope.

What about javascript redirects? What about HTML pages with a big link, like this one 

https://aclsrecertificationonline.com/

**Comment by msh100** [comment]
I am not sure I agree, I test with local files - there's no way of testing HTTP status codes when you don't use HTTP. Maybe I'd agree if HTML proofer depended on HTTP.

**Comment by fulldecent** [comment]
We currently test broken links with HTTP.

**Comment by thbar** [comment]
Is there a trick to forbid 302 redirections or log them today?

For some context, I'm trying to detect broken links to GitHub wiki pages that do not exist. They result in `302` (which leads to a new page to create the missing page).

```
# OK
$ curl -I https://github.com/thbar/kiba/wiki/SQL-Bulk-Lookup
HTTP/1.1 200 OK

# I would like to raise in this case!
$ curl -I https://github.com/thbar/kiba/wiki/SQL-Bulk-Lookupx
HTTP/1.1 302 Found
```

I could restrict Wiki editing I presume, but wondering if this can be achieved today with some configuration maybe?

Thanks!

**Comment by gjtorikian** [comment]
HTML-Proofer accepts all [Typhoeus](https://github.com/typhoeus/typhoeus) config options so you could do something like:

```ruby
options = { typhoeus: { followlocation: false } }
HTMLProofer.check_directory("./_site", options).run
```

**Comment by gjtorikian** [comment]
Not sure why I was interested in adding this, but doesn't seem to be a whole lot of interest in it. Closing for now, will open if it's an enhancement people crave. It would only appear in the logs.
