### ISSUE TITLE
Scheme-less image links should always pass validation

### ISSUE THREAD

**Issue by Morendil** [gjtorikian/html-proofer#363]
Sometimes image tags are written in the following "scheme-less" form:

`  <img src="//server/uri">`

The effective value of the "scheme" part of such an URL will be whatever scheme has been used to download the enclosing page. This is apparently useful in some contexts. It cannot lead to mixed-content errors because it ensures the image content is served from a secure location whenever the page itself is served securely.

Prior to https://github.com/gjtorikian/html-proofer/commit/b39113ec80bd85691a1ed8aa6f62f74c4a718f2c the secure-images plugin correctly examined the raw `src` attribute of the `img` tag. That commit changed the check, to look at the `scheme` property of the `node` object; but the `node` constructor supplies "http" as a default value, so that commit results in checks failing that should pass.

I'll be submitting a unit test for this specific case, and reversion of the commit as a fix.

**Comment by fulldecent** [comment]
Please send a unit test if you have it.

**Comment by fulldecent** [comment]
Closing now as abandoned. Please reopen if you are still around.
