### ISSUE TITLE
.html extension not respected by html-proofer

### ISSUE THREAD

**Issue by kbariotis** [gjtorikian/html-proofer#364]
In a generated Jekyll site there is a file `press.html` in the root directory. Another file links to it by:

```html
<a href="/press">Press</a>
```

still html-proofer says:
```
*  internally linking to /press, which does not exist (line 109)
     <a href="/press">Press</a>
```

**Comment by gjtorikian** [comment]
Try passing in `assume_extension` as an option: https://github.com/gjtorikian/html-proofer#configuration

**Comment by kbariotis** [comment]
oh great @gjtorikian. that was it! Thank you.
