### ISSUE TITLE
Twitter Cards tags get flagged as erroneous

### ISSUE THREAD

**Issue by mkpankov** [gjtorikian/html-proofer#365]
Example:

```
  <meta name=”twitter:title” content=”Кто использует Rust | rustycrate.ru“ />
```

causes

```
bundle exec htmlproofer ./_site --log-level error --only-4xx --check-favicon --check-html --url-ignore /crates.io/,/files.gitter.im/,/fonts.googleapis.com/,/www.quora.com/,/is.gd/, /github.com/ruRust/rustycrate.ru/edit/master/ --file-ignore /yandex_6b9a121b20becc7c.html/,/googlea5495ce52829dd37.html/,/where-are-you-from.html/
- ./_site/adopters.html
  *  error parsing attribute name (line 50)
  *  error parsing attribute name (line 50)
  *  error parsing attribute name (line 50)
```

I expect html-proofer to not flag these tags, as they're an official way to add metadata for [Twitter Cards](https://dev.twitter.com/cards/types/summary) to work.

Full HTML is attached.
[html.zip](https://github.com/gjtorikian/html-proofer/files/601627/html.zip)

**Comment by gjtorikian** [comment]
Thanks! Will look into it.

**Comment by gjtorikian** [comment]
Sorry for taking some time to reply. It looks like the HTML you've provided is actually malformed. It seems that _just_ the Twitter cards are using so called "smart quotes," that look like this: “…”

![image](https://cloud.githubusercontent.com/assets/64050/20652284/4d1887de-b4ab-11e6-9c39-33884a71ed2f.png)

However, other attributes are using normal ASCII quotes, like this: "…"
![image](https://cloud.githubusercontent.com/assets/64050/20652285/525f5d8a-b4ab-11e6-932d-6a3cd17e7392.png)

Could you try changing the quotation marks on the Twitter cards and running the HTML Proofer again?

**Comment by mkpankov** [comment]
@gjtorikian right, thank you! that works
