### ISSUE TITLE
Invalid hash check is wrong for other pages + aria-hidden not supported

### ISSUE THREAD

**Issue by jeznag** [gjtorikian/html-proofer#367]
*PR to follow*
The hash link check will fail if the link is something like `/about#Team` (i.e. #Team on another page, About) because the code looks for the #Team ID on the current page rather than on the other page. 

Also, alt text should not be checked if aria-hidden is "true".

**Comment by jeznag** [comment]
Let me know if this seems ok and I'll add tests.

**Comment by fulldecent** [comment]
PR is merged (the relevant parts at least). Recommending to close issue.
