### ISSUE TITLE
Configurable HTMLProofer::Utils::STORAGE_DIR?

### ISSUE THREAD

**Issue by tisba** [gjtorikian/html-proofer#369]
It would be great, if you could specify the `HTMLProofer::Utils::STORAGE_DIR`. On our CI we fetch (when available) the cache manifest and copy that into place. It would be nice if you could overwrite this w/o monkey patching this constant.

Is this something you would accept a PR for?

**Comment by gjtorikian** [comment]
Yeah, that sounds totally fine to me. Bring the PR and I'll take a look!

**Comment by gjtorikian** [comment]
Did you want to open a PR for this?

**Comment by tisba** [comment]
Thanks for the reminder, I've opened up a PR.
