### ISSUE TITLE
data-proofer-ignore does not work on a parent element

### ISSUE THREAD

**Issue by klomontes** [gjtorikian/html-proofer#370]
I’m not sure if this is how it is intended to work or not but it seems like it should.

I have some scraped text loaded via liquid inside a `<div>` and I don’t want to check if links inside of it are valid or not since it is not the responsibility of the codebase I handle. I’ve put `data-proofer-ignore` on the parent div and htmlproofer still checks the links inside of it.

Is my assumption or implementation wrong? :)

**Comment by gjtorikian** [comment]
Yeah, seems like parent ignores should trickle down too.
