### ISSUE TITLE
Command line flags are slightly different compared to ruby config

### ISSUE THREAD

**Issue by VirenMohindra** [gjtorikian/html-proofer#374]
While testing on the cli for a Jekyll based site using travis-ci I realized that the flags are slightly different compared to the ruby configurations in the README.md.

The spaces between the flags are **dashes** instead of **underscores**, and I understand the reasoning behind this -- sometimes the underscores get eaten by a terminal border, hence the appropriate usage.

This works, but in the documentation nothing is specified: 
`htmlproofer ./_site --allow-hash-href --check-favicon --check-opengraph --check-html`

I think that it should be documented in the README.md so developers don't get confused. It is a quick fix and I don't mind sending in a PR.

Let me know, thanks.

**Comment by gjtorikian** [comment]
Closed via https://github.com/gjtorikian/html-proofer/pull/375
