### ISSUE TITLE
--url-ignore matching

### ISSUE THREAD

**Issue by ilg-ul** [gjtorikian/html-proofer#378]
In one of my sites, the proofer reported:

```
*  External link https://jekyllrb.com/ failed: response code 0 means something's wrong.
```

Initially I added `--url-ignore "https://jekyllrb.com/"`, but this was not useful.

Inspecting the input file, revealed the reference has no trailing `/`.

```
<p><a href="https://jekyllrb.com">Jekyll</a> is a simple, blog-aware, static site generator.</p>
```

Changing the command line to `--url-ignore "https://jekyllrb.com"`, silenced the error.

So, the problem is an inconsistency between the input file (without slash), the error message (without slash) and the option required to silence the error.

Suggestions:

- be sure the URL displayed in the error message is exactly the one that needs t be passed to `--url-ignore`
- if the `--url-ignore` path does not end in a slash, also try to match the one with a slash

**Comment by gjtorikian** [comment]
I like it! I've assigned this for future work.
