### ISSUE TITLE
Allow Typheous options to be set from `bin`/command line

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/html-proofer#379]

**Comment by fulldecent** [comment]
This will get ugly fast. I can't think of a clean way to specify arbitrary Ruby on the command line.

Here is another issue that can be solved with Typheous configuration: https://github.com/gjtorikian/html-proofer/issues/86

I recommend to create turn on wiki pages and create a page about Typheous hacks that people can use. This will require people to use Ruby but they can get what they need done and it does not clog up this project with implement everyone's favorite Typheous feature.

Also long term, if we take that approach then in the future we could look at the activity on that blog and make a better decision on implementing the command-link Typheous support discussed here (and reopen this issue).

**Comment by fulldecent** [comment]
* A 100% usable workaround is in the wiki
* In 6 months, nobody else has contributed to that wiki (there's a few TODOs outstanding)
* Nobody submitted a pull request
* It is questionable if this issue promotes project scope

**Recommendation: close issue**

Perhaps we can reopen the issue after somebody else cares to update the wiki into a rock solid page (address all TODO items). But for now it seems this is going nowhere.
