### ISSUE TITLE
Depends on development dependencies

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#380]
`html-proofer` or one of the things it depends on includes `minitest`. This appears to not be relevant to end users.

Perhaps dependency on `minitest` should be switched to a "development dependency".

**Comment by gjtorikian** [comment]
Not I! It's using `rspec` as a dev dependency: https://github.com/gjtorikian/html-proofer/blob/5059d5a4f3fc90d770a40ca1d3ea2974e3dae5ae/html-proofer.gemspec#L30

What's your `Gemfile.lock` perchance? Let's track the culprit down.

**Comment by fulldecent** [comment]
Thank you! This is my `Gemfile.lock`:

https://github.com/fulldecent/html-website-template/blob/master/Gemfile.lock

**Comment by gjtorikian** [comment]
It looks like `activesupport` (which I've brought in) does also bring in `minitest`: https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activesupport/activesupport.gemspec#L25

I suggest opening an issue on their repo to suss out why that isn't a development dependency!
