### ISSUE TITLE
Check that `<link>` and `<script>` external resources do use SRI

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#382]
Any `<link>` and `<script>` tags to external resources should use subresource integrity and CORS.

(I can provide resources to work on this issue. Just wanted to add the issue here to see if this project will be interested to accept such a change when it is available.)

**Comment by gjtorikian** [comment]
> I can provide resources to work on this issue. Just wanted to add the issue here to see if this project will be interested to accept such a change when it is available.

Heck yeah, that sound pretty amazing. I suspect it'd be a command-line flag / option, since it could potentially slow down external checks, I imagine. (Though to be honest I'm not sure how to check for CORS on an external resource. If it's not slow, it ought to be the default.)

**Comment by fulldecent** [comment]
I don't know how to implement yet, but this is checked WITHOUT network connectivity. It is very simple:

Examples:

    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

 > FAIL -- SRI and CORS not provided

    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="></script>

 > WARNING --  CORS not provided for external resource (I suppose we cannot mark this as a fail because this is a (rare) potential legitimate use for this)

    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    crossorigin="anonymous"></script>

 > FAIL -- Integrity is missing

    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>

 > PASS -- Integrity and CORS present

-----------

## Notes:

It may be desirable to verify that the external resource hashes to the value that we have. But that is NOT in scope for this issue. It will require network access and maybe caching.

The Google AMP project uses javascript URLs that change their content after they are published. This is incompatible with SRI. The AMP project usage in this situation is non-standard and promotes insecurity by design. Google's promotion of AMP in its search results is probably also illegal in the United States. We are correct in flagging AMP as an error by default. Further discussion on this topic is at https://github.com/ampproject/amphtml/issues/534

**Comment by gjtorikian** [comment]
Oh that's pretty easy to do. If you want to take a crack at it, go for it! Otherwise I don't mind adding it myself.

It isn't slow at all, but, I think it should still be a config option (default off), since I imagine many people don't have this configured at all.

**Comment by fulldecent** [comment]
If you could do this, please do go ahead, thank you. Please note that it is only necessary to check external links. Local links (`./xxx`) need not be checked.

**Comment by fulldecent** [comment]
Beautiful, thank you
