### ISSUE TITLE
Standardize output format, use STAT format

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#387]
**BLOCKER: https://github.com/fulldecent/structured-acceptance-test/issues/44**

Output of html-proofer is not designed to be machine readable. There is a simple output format that is machine readable which may be useful to consider.

https://github.com/fulldecent/structured-acceptance-test

This standard includes a machine-readable json output format which can be parsed by other tools and rendered in realtime in Atom and other editors. Additionally, that project includes Ruby classes for describing findings and outputting them. Out of the box it supports pretty output formats (with color) and JSON output formats.

https://github.com/fulldecent/structured-acceptance-test/tree/master/implementations/ruby

# Work scope

- [ ] Clearly define the output format of html-proofer findings (i.e. errors and warnings)
- [ ] Implement standardized StatModule as the in-memory format for findings
- [ ] Implement default output format matching existing html-proofer output from
- [ ] Create new option `--stat` which follows stat standardized output format

# Future scope

 - [ ] Propose and implement new and prettier standard output format

**Comment by fulldecent** [comment]
Please confirm if such a contribution would be welcome, I have resources available to help with this issue.

**Comment by gjtorikian** [comment]
Sure, if it can be done, I wouldn't mind accepting it.

A lot of non-technical users use this project, so I am very concerned about a big blob of JSON being the only thing letting you know what went wrong. I'd like to see what the machine-readable format would first look like before all the work is done for it. Alternatively, you can set a `machine-readable-output` flag if that's simpler to disambiguate.

**Comment by fulldecent** [comment]
Thank you, I will work on this. Please keep issue open, it will take a little while so I can get it right.

**Comment by fulldecent** [comment]
I have added a work scope to this issue.

@ilyalyo could you please review the above work scope.

**Comment by ilyalyo** [comment]
In htmlproofer we have class issue with following attributes:
:path, :desc, :status, :line, :content
We can match them with [STAT finding](https://github.com/fulldecent/structured-acceptance-test/blob/master/Stat-Output.md#full-featured-example) like this:
failure -> true (we don't have warnings, all findings in htmlproofer is errors)
rule -> ?
description -> desc
location.path -> path
location.beginLine -> line
location.endLine -> line

Rule is required attribute for STAT, so I think we should add it to issue class and update all addIssue method invocation.
Also, it's optional, but we can add attributes like beginLine, endLine, beginColumn, endColumn to hold relevant values.

**Comment by fulldecent** [comment]
Great implementation plan.

**Comment by fulldecent** [comment]
Closed. Not enough action.

If anybody is interested in getting your HTML Proofer output to be recognized automatically in GitHub Actions then let's work on https://github.com/fulldecent/structured-acceptance-test first and then integrate here afterwards.
