### ISSUE TITLE
Need relaxing option for empty alt check

### ISSUE THREAD

**Issue by nschonni** [gjtorikian/html-proofer#39]
Alt tags may be left empty for decorative images http://dev.w3.org/html5/alt-techniques/#secm3
It would be good if to have a similar whitelist as the href check to exclude known valid images like "logo.png" where the content is purely decorative. In the decorative case, an empty alt tag prevents screen readers from reading the file name as a fallback.

**Comment by LaurentGoderre** [comment]
actually, it should be `alt=""` because `alt=" "` is a non null alt and will not be ignored by assistive technologies
