### ISSUE TITLE
SRI/CORS check should ignore relative links

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#400]
# Test case

    echo '<script src="local.js"></script>' > test.html
    htmlproofer --check-sri --checks_to_ignore LinkCheck  .

# Expected outcome

No errors.

# Actual outcome

>   *  SRI and CORS not provided in: local.js (line 1)

# Discussion

`--check-sri` should only be active for links containing `//`, or more specifically, links that contain a host component.

---

References: #388 #382

**Comment by fulldecent** [comment]
CSS check is not flagging local CSS files, this is good. JS is failing. Sorry, updated test case to show actual broken behavior.

**Comment by fulldecent** [comment]
@ilyalyo Can you help with this one?

**Comment by ilyalyo** [comment]
@fulldecent yes, I can.
