### ISSUE TITLE
Can I configure parallel from the command line?

### ISSUE THREAD

**Issue by pauldambra** [gjtorikian/html-proofer#408]
I asked this question [on stackoverflow](http://stackoverflow.com/questions/42892839/can-i-configure-parallel-when-calling-html-proofer-from-a-script) originally....

I'm calling [html proofer][1] from a script like so

    #! /bin/bash
    
    set -eu
    
    bundle exec htmlproofer \
      _site \
      --file-ignore /amp/,/.git/ \
      --check-favicon \
      --check-html \
      --check-opengraph

I've added the [parallel gem][2] to my Gemfile and that makes no difference to run time.

Should it have done? Can I hook in parallel in the script?

Thanks!

  [1]: https://github.com/gjtorikian/html-proofer
  [2]: https://github.com/grosser/parallel

**Comment by pauldambra** [comment]
Ah, just forked and running locally. So, I can see that I can't already.

Also, that there's a single tags.html page that takes almost all of the time in the run because, I assume, it has 1177 internal links.

**Comment by gjtorikian** [comment]
Ugh, this is an issue also related to https://github.com/gjtorikian/html-proofer/issues/379.
 
I really need to make this happen.

**Comment by pauldambra** [comment]
No need to apologise! HTML proofer is awesome and there are always more things to build than time to build them :)

**Comment by fulldecent** [comment]
We currently do not have command line support for parallel configuration.

BUT I have fully documented how to configure this "advanced" feature using Ruby. And there are copy/pastable usage guides for Travis.

> https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis

**Comment by fulldecent** [comment]
@pauldambra Could you please confirm if wiki is helpful enough for you to make it work the way you like?

**Comment by pauldambra** [comment]
I'm calling the CLI in a bash script. I could call out to a ruby script from there so can probably use that... Shall I try that (can't be today unfortunately) and then I can PR against the wiki page of I can think of any improvement for my use-case?

**Comment by fulldecent** [comment]
@pauldambra yes please, this would be most helpful.

Technical note, you are able to directly edit the wiki, no PR required.

**Comment by tiagoboldt** [comment]
My 2 cents, for the sake of keeping usage simple and clutter free, it would be very much useful if parallel could be used from the command line.

**Comment by pauldambra** [comment]
I've just converted my bash script to a ruby script. So...
