### ISSUE TITLE
Documentation for external checker

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#415]
Is there an example or documentation of how we can create an external checker that will be used by html-proofer?

We have implemented a checker that ensures all `mailto:` links have body and message parameters. This is in our company's style guide policies. I do not think this will be useful for the main `html-proofer` project so I'd like to publish it as an extension. We have implemented it here https://github.com/fulldecent/html-proofer-mailto-awesome/pull/1

However I think the way we have implemented (a complete copy of html-proofer with the new feature added) it is not correct and I'm seeking guidance.

**Comment by fulldecent** [comment]
Is there anyone you can recommend to help here?

**Comment by gjtorikian** [comment]
I'm not sure if this is what you are asking, but would https://github.com/gjtorikian/html-proofer#custom-tests be helpful?

**Comment by fulldecent** [comment]
Perfect, thank you.

**Comment by fulldecent** [comment]
OK, so I have a custom module. How do I add run proofer using Ruby and make it include my custom  test (among the other tests)?

**Comment by gjtorikian** [comment]
Assuming a `Rakefile`, and your custom test is in `test/support/foo.rb`, you should just be able to do:

``` ruby
require 'html-proofer'
require 'test/support/foo'
HTMLProofer.check_directory('./output').run
```

**Comment by fulldecent** [comment]
Hmm, that seems weird how `HTMLProofer` learns that the `MailToOctocat` class exists and decides to use it.

**Comment by gjtorikian** [comment]
The way HTML-Proofer works is it just iterates over all the subclasses of `HTMLProofer::Check`.
