### ISSUE TITLE
empty_alt_ignore option doesn't do anything

### ISSUE THREAD

**Issue by LeonardMH** [gjtorikian/html-proofer#416]
I am using Ruby 2.3.3 with html-proofer v3.6.0. I have my rakefile set up as suggested in the README but with an additional parameter:

```ruby
require 'html-proofer'

task :build do
    system("bundle exec jekyll build")
end

task :test => :build do
  options = {
      :assume_extension => true,
      :empty_alt_ignore => true
  }

  HTMLProofer.check_directory("./_site", options).run
end
```

The `empty_alt_ignore` option seems to be getting ignored when I run `rake test`, example output from one of my pages:

```
- ./_site/understanding-i2c.html
  *  image /assets/posts/understanding-i2c/i2c-ack-bit.gif does not have an alt attribute (line 146)
  *  image /assets/posts/understanding-i2c/i2c-bus-pullups.gif does not have an alt attribute (line 90)
  *  image /assets/posts/understanding-i2c/i2c-complex-sequence.gif does not have an alt attribute (line 266)
  *  image /assets/posts/understanding-i2c/i2c-seven-bit-addressing.gif does not have an alt attribute (line 179)
  *  image /assets/posts/understanding-i2c/i2c-start-stop.gif does not have an alt attribute (line 129)
```

I also tried running the `htmlproofer` tool with the following options:

```
htmlproofer --assume-extension --empty-alt-ignore ./_site
```

But I still get the same output that is littered with empty alt attribute errors. Is there something I'm doing wrong here? Is there another way to get the result I want?

FWIW I plan to fix the empty alt attribute issues soon, but there are broken links and other things like that which I am trying to focus on first so I'm hoping to ignore these less critical issues.

**Comment by gjtorikian** [comment]
Sorry for the delay in my reply.

Hmm, that's odd. Can I clone your repo somewhere, or, could you send me the `understanding-i2c.html` that is failing? I want to test against the actual file to see what could be wrong.

**Comment by LeonardMH** [comment]
Sure, my site is [here on GitHub](https://github.com/LeonardMH/michaelhleonard.com) generated with Jekyll. You should just be able to run `bundle install` and then `rake test` to build the site and run html-proofer.

I have since addressed this issue on my end by updating my image template to always assign an alt tag. Check out commit `45f5fe5ac747f377d3e017b356295411e76d6f05`, I just re-verified that I can reproduce this issue on that commit.

I've attached the [understanding-i2c.html](https://github.com/gjtorikian/html-proofer/files/966416/understanding-i2c.txt) from that commit if you don't want to deal with the hassle of building the site. It's saved as a .txt, since GitHub doesn't allow HTML uploads.

**Comment by ceri-richmond** [comment]
+ 1
