### ISSUE TITLE
Any way to add wildcards to --url-ignore in the command line?

### ISSUE THREAD

**Issue by VirenMohindra** [gjtorikian/html-proofer#418]
Is there any way you can ignore a whole domain since I have a lot of links originating from one domain and would like to ignore that entirely.

**Comment by gjtorikian** [comment]
You could use a regular expression in those cases, instead of strings. Does that help?

**Comment by VirenMohindra** [comment]
I'm finding it difficult to pass it through the command line.

My regex is 
`([-a-zA-Z0-9^\p{L}\p{C}\u00a1-\uffff@:%_\+.~#?&//=]{2,256})(\bweb.archive|redd.it|youtu.be|youtube){1}(\:[0-9]*)?(\/[-a-zA-Z0-9\u00a1-\uffff\(\)@:%,_\+.~#?&//=]*)?([-a-zA-Z0-9\(\)@:%,_\+.~#?&//=]*)?`

how can I add this as a parameter to the flag?

my command is -

`sh "bundle exec htmlproofer --allow-hash-href --check-favicon --check-opengraph --check-html --check-img-http --timeframe 15d --enforce-https --check-external-hash --url-ignore ([-a-zA-Z0-9^\p{L}\p{C}\u00a1-\uffff@:%_\+.~#?&//=]{2,256})(\bweb.archive|redd.it|youtu.be|youtube){1}(\:[0-9]*)?(\/[-a-zA-Z0-9\u00a1-\uffff\(\)@:%,_\+.~#?&//=]*)?([-a-zA-Z0-9\(\)@:%,_\+.~#?&//=]*)? ./_site"`

which you can see here - 

https://github.com/TrumpTracker/trumptracker.github.io/blob/master/Rakefile#L53

**Comment by gjtorikian** [comment]
Oh, damn! I love the idea of this project so much.

I made a PR in https://github.com/TrumpTracker/trumptracker.github.io/pull/141 to address this. Let's move the conversation over there!
