### ISSUE TITLE
Invalid hash check

### ISSUE THREAD

**Issue by 2ndalpha** [gjtorikian/html-proofer#419]
For some reason all anchors which link to itself fail, example:

```
linking to #lines-changed, but lines-changed does not exist (line 1)
<a href="#lines-changed" class="title" id="lines-changed">Lines changed</a>
```

**Comment by gjtorikian** [comment]
Hmm, according to https://github.com/gjtorikian/html-proofer/pull/424, this already works.

@2ndalpha, could you provide some more information here on how you've configured HTML Proofer?

**Comment by fulldecent** [comment]
Worksforme, closing. @2ndalpha could you please send more information and a test case we can run if you are still having this problem? I'll be happy to reopen the issue then and investigate. Thank you.
