### ISSUE TITLE
I'm looking for maintainers!

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/html-proofer#422]
I mentioned this [on Twitter](https://twitter.com/gjtorikian/status/857344555506700288), but, as a project, I feel that `html-proofer` has done everything I want and need it to do. Certainly it has its bugs, but it's a decent enough program as it is.

However, decent is not good enough! I'm looking for maintainers who can commit (heh) to reviewing and merging pull requests. I really only have two requirements:

1. The program doesn't bloat to doing all sorts of "other" things, like checking spelling/grammar, or ensuring well-formatted nesting, etc.
2. That you have experience running or collaborating on other open source projects.

I'll grant anyone interested the ability to push to the repo. I'll hold onto releasing new versions unless that becomes burdensome too. 

I'm really looking forward for some help to close out the existing issues and implementing any new features marked with [`future`](https://github.com/gjtorikian/html-proofer/issues?q=is%3Aissue+is%3Aopen+label%3Afuture) (which is my code for, "I believe in this and want it too.").

Thank you in advance!

**Comment by fulldecent** [comment]
Please write an actual project scope statement (or document) to describe what should and should not be in the project, link or paste it to README.md. Here is a recommended start:

> HTML Proofer wants to help you test your HTML files for accuracy. In scope for this project is any well-known and widely-used test for HTML document quality. A major use for this project is continuous integration -- so we must have reliable results. And if necessary we should be able to trace this program's detection of HTML errors back to documented best practices or standards.

> **Third-party modules.** We want this product to be useful for continuous integration so we prefer to avoid subjective tests which are prone to false positive results, for example spell checkers, indentation checkers, etc. If you want to work on these items please see https://github.com/gjtorikian/html-proofer#custom-tests and consider implementing as a third-party module. Also feel free to list your module on our wiki, but do not discuss it on our issues.

Please add me as a committer. I do not plan to commit much nor work as a maintainer, but this will give me special access for issues.

**Comment by gjtorikian** [comment]
That's a good idea. I will do that.

**Comment by Floppy** [comment]
I'm a big fan of html-proofer, and use it a lot. However, I don't have much spare time and already plenty of projects to fit in them, so I can't commit to regular feature development myself. BUT I'll happily help review and merge PRs.

**Comment by gjtorikian** [comment]
Good enough for me! Granted~!

**Comment by Floppy** [comment]
Now we're trying to share the burden around a bit, should we set up a [code owners](https://github.com/blog/2392-introducing-code-owners) file, and set up things like "review required" for PRs? I'm happy to do that if you want.
