### ISSUE TITLE
Favicon check failing on Ruby built from source.

### ISSUE THREAD

**Issue by PhilThurston** [gjtorikian/html-proofer#425]
A page exactly like this:
```
<!DOCTYPE html>
<html>
<head>
  <title>Redirect</title>
  <link rel="shortcut icon" href="../assets/img/favicon/favicon.ico">
  <meta http-equiv="refresh" content="0; url=https://yourdomain.com/">
</head>
<body>
  Nothing to see here, <a href="https://yourdomain.com/">click here if you weren't redirected.</a>
</body>
</html>
```
never passes favicon checks using `htmlproofer --check-favicon _site`

While it does pass when installing ruby via yum or apt-get on normal distros if it is an image built from ruby source for example.
docker ruby:2.3 and ruby:2.4 both have been tested and are failing. This is using the exact same gem files on all machines.

My skills are not in ruby but I can only surmise that this is some inconsistency between the docker images and stable version from mainteam distros.

**Comment by gjtorikian** [comment]
I do not maintain the Docker distributions; it looks like that comes from https://github.com/18F/html-proofer-docker. I would suggest opening an issue for them.
