### ISSUE TITLE
[feature request] Config option to ignore certain HTTP errors

### ISSUE THREAD

**Issue by JarLowrey** [gjtorikian/html-proofer#426]
LinkedIn always gives a 0 error code, I'm only concerned with 400, 300, 500, etc - ones that show the linked website is down. For those websites that always ignore the ping, can we get an option to not print the error message?

**Comment by gjtorikian** [comment]
You may find the `http_status_ignore` option useful. You can pass in `[0]` to simply ignore those status codes.

**Comment by JarLowrey** [comment]
Sorry I missed it!
