### ISSUE TITLE
Enable project wiki

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#427]
Please enable the project wiki.

Proposed index.md:

---
# HTML Proofer Wiki

This wiki exists to document best practices with HTML Proofer and discuss extensions to the project which are out of scope of the project itself.

## Links

* Extensions ("custom classes")
* How to make an extension
* How to configure Typhoeus
---

**Comment by gjtorikian** [comment]
Done!

**Comment by fulldecent** [comment]
Awesome, I have added a bunch of pages. Some are an ugly starting point, but still useful.
