### ISSUE TITLE
limit memory for travis builds

### ISSUE THREAD

**Issue by stephengroat** [gjtorikian/html-proofer#429]
I'm trying to check quite a few external links (around 1700) on [travis](https://travis-ci.org/2factorauth/twofactorauth/jobs/228089055). I'm getting error 137, which i think is out of memory.

other than limiting concurrency with `hydra`, are there any other ways to limit memory usage?

**Comment by stephengroat** [comment]
just bumping to see if i can get any advice, have no idea what's going on.

**Comment by gjtorikian** [comment]
Out of curiosity, how did you settle on `12` for Hydra's max concurrency? 

The best advice I can give is to set it to an absurdly low number, like, 5, and see how high you can go before it crashes. ☹️

**Comment by stephengroat** [comment]
I just went with my favorite number (the truth doesn't sound very scientific of me)

I started trying to reconfigure, got it to finish with `1`, started stepping it up and added `typhoeus: { ssl_verifypeer: false, ssl_verifyhost: 0 }` and now get a `segfault` https://travis-ci.org/stephengroat/twofactorauth/jobs/232602544

**Comment by gjtorikian** [comment]
Haha, amazing. I can't do anything about the sefaults I'm afraid, that's either a Travis problem (something on the box?) or a Typhoeus problem (something in the C library that's busted?).

**Comment by stephengroat** [comment]
i'm closing this with the other typhoeus issues that have been found
