### ISSUE TITLE
Set the timeout value from the commandline.

### ISSUE THREAD

**Issue by NicolasWebDev** [gjtorikian/html-proofer#435]
htmlproofer is really good, but right now using it for a jekyll-based blog is somewhat burdensome, because it times out quite frequently on valid websites, because the timeout value is set too low by default.

`External link https://www.goodreads.com failed: got a time out (response code 0)`

I have it in a git pre-commit hook, and to make it pass, I have to repeat it 3 or 4 times.

So it would be nice to be able to have a CLI option, to set the timeout value.

**Comment by fulldecent** [comment]
Thank you for sharing. At this time, addition CLI configurations are out of scope for this project.

Please see the wiki for advanced configuration options. This is easy to do. If it is not perfectly easy to do and dead-simply to figure out then let's update the wiki.

https://github.com/gjtorikian/html-proofer/wiki

However, if you are proposing to change the default value that would be in-scope and we would appreciate a PR for that and some benchmarking and discussion.

**Comment by NicolasWebDev** [comment]
@fulldecent, would you mind sharing why it is out of scope?

Indeed I know that it can be done using html-proofer as a library, I am myself used to Ruby, but it would be really practical for people not fluent in Ruby, or working on projects where ruby dependencies would like to be avoided. In these cases the CLI is really good and practical.

I understand that you do not have a lot of time right now to work on the project, but I thought that it would be nice to put that on some kind of wishlist, that's why I opened the issue.

**Comment by fulldecent** [comment]
Please see the project scope documented here: https://github.com/gjtorikian/html-proofer#project-scope

More discussion on the motivation for setting it are here: #422 

The main issue is that there will always be more issues opened for new command line options, whereas Ruby configuration solves this problem permanently and exhaustively. Personally I hate using Ruby as /just one more language/ in a non-Ruby project. The solution is copy-pasteable recipes in our Wiki file. And then also creating a project scope at the top of the readme to make it clear and avoid hard feelings.

Lastly, and more specifically to you, I am going off of the author's comment that adding external link checking to this project was perhaps a mistake. The motivates the policy that the feature is ok to have, and configuring it from Ruby is ok, but adding command lines options is not wanted.

**Comment by NicolasWebDev** [comment]
Thanks for the clarification, even though it still seems a shame to me to prevent non-ruby users to have access to this nice tool.

**Comment by fulldecent** [comment]
Please do check out the wiki and let us know if it is helpful.

Personally I am also definitely NOT a Ruby person. Wiki copy-paste is how I survive.

**Comment by gjtorikian** [comment]
It's on the roadmap but with one maintainer (me) I haven't had a chance yet to go through and implement it.

**Comment by NicolasWebDev** [comment]
Hi @gjtorikian, if it is on the roadmap, don't you think it would be better to keep it open? If you would like to sort it in the issues, you can put a tag on it like 'wishlist' or 'later'.

I do understand you are the unique maintainer, but there is no rush in solving that. I can personally use the ruby, like @fulldecent advised me.

**Comment by gjtorikian** [comment]
I didn't close it, and wouldn't have if I had gotten to the issue first.

On the other hand, https://github.com/gjtorikian/html-proofer/issues/408 and https://github.com/gjtorikian/html-proofer/issues/379 are duplicates of this issue, which I would've probably closed this for that reason. 😅

**Comment by NicolasWebDev** [comment]
Yep, you are right, I did not know it involved Typheous, that's why I did not know they were related.

Thanks for the hard work.
