### ISSUE TITLE
Allow using GET instead of HEAD

### ISSUE THREAD

**Issue by akshayrawat** [gjtorikian/html-proofer#440]
Some sites respond with a blank body for a `HEAD` request. This causes a `html-proofer` validation failure (blank body) which then does not fallback to `GET`.

 **html-proofer (3.7.2)**

**Comment by gjtorikian** [comment]
Could you provide a sample URL where you see this?

By default, if a `HEAD` fails, a `GET` should be issued as well: https://github.com/gjtorikian/html-proofer/blob/094247901b4632180dab6a8e4c984b85fc8531c0/lib/html-proofer/url_validator.rb#L87

**Comment by akshayrawat** [comment]
```
Connected to ecorp.sos.ga.gov (63.247.80.171) port 443 (#0)
Connected to icis.corp.delaware.gov (167.21.84.160) port 443 (#1)
Server aborted the SSL handshake
Closing connection 0
TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
Server certificate: icis.corp.delaware.gov
Server certificate: Entrust Certification Authority - L1K
Server certificate: Entrust Root Certification Authority - G2
HEAD /Ecorp/EntitySearch/NameSearch.aspx HTTP/1.1
Host: icis.corp.delaware.gov
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

HTTP/1.1 200 OK
Date: Fri, 07 Jul 2017 21:02:54 GMT
Server: Microsoft-IIS/7.5
X-Frame-Options: SAMEORIGIN
Cache-Control: private
Content-Length: 50544
Content-Type: text/html; charset=utf-8
X-AspNet-Version: 2.0.50727
X-Powered-By: ASP.NET
Set-Cookie: ASP.NET_SessionId=fbz4psyaje5imoz11pl34q45; path=/; HttpOnly

Connection #1 to host icis.corp.delaware.gov left intact
Ran on 1 file!


- ./html_proofer_build/articles/How do I find out if a company name is available in a given state.html
  *  External link https://ecorp.sos.ga.gov/BusinessSearch failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL connect error

```

@gjtorikian URL: https://ecorp.sos.ga.gov/BusinessSearch

You'll see that this returns a blank response for `HEAD`, and a proper response for `GET`. But `html-proofer` doesn't seem to attempt a `GET` in this scenario.

**Comment by fulldecent** [comment]
```sh
➜  Desktop echo '<a href="https://ecorp.sos.ga.gov/BusinessSearch">a' > a.html
➜  Desktop htmlproofer a.html                
Running ["LinkCheck", "ImageCheck", "ScriptCheck"] on a.html on *.html... 


Checking 1 external link...
Ran on 1 file!


HTML-Proofer finished successfully.

**Comment by gjtorikian** [comment]
Possibly stale, please reopen if that's not the case!

**Comment by aandis** [comment]
I think fixing this could be useful because apps can choose to return different responses to `HEAD` and `GET`. As an example, the following curl request gets stuck in a loop because the page redirects back to itself :facepalm:  - 

`curl -I -X HEAD https://esos.nv.gov/EntitySearch/OnlineEntitySearch -L`

So while checking that link, proofer eventually [times out](https://github.com/typhoeus/typhoeus/issues/337) with a response code `302`. A `GET` request to the same page works - 

`curl  -I -X GET https://esos.nv.gov/EntitySearch/OnlineEntitySearch -L`

 So having the flexibility to pass the request method type to use can be helpful.
