### ISSUE TITLE
Favicon checks and redirect pages

### ISSUE THREAD

**Issue by Floppy** [gjtorikian/html-proofer#446]
When running favicon checks on a site that includes page redirects that use the jekyll redirect_from plugin, those redirect pages don't include favicons, so the tests fail.

I'm not sure how this would be best fixed:

1. Improve the redirect gem to include favicons (seems like a pointless addition)
2. Make html-proofer ignore certain checks on redirect-only pages
3. Something else I've not thought of

Any thoughts, anyone? I'll do a fix, but I'm just not sure which approach to take.

**Comment by gjtorikian** [comment]
I'm not sure I follow the issue, sorry. So:

* There's a site with favicons
* The favicon check is enabled
* There's a Jekyll 301 page
* The favicon check fails?

**Comment by Floppy** [comment]
Yep, that's pretty much it. And the check *should* fail, because the redirect pages indeed don't have a favicon in.

Unfortunately that means you have to turn off favicon checking for any site that uses jekyll redirects if you want html-proofer to pass. Maybe that's the price, but I was wondering if there was a sensible workaround we could think of.

**Comment by gjtorikian** [comment]
https://github.com/gjtorikian/html-proofer/issues/446 is the best I got. ☹️

**Comment by Floppy** [comment]
Nice one, thanks for taking a look! I've got an idea to make #448 a little more robust, to basically look for no body tag and a zero-time meta refresh. I'll send a PR.

**Comment by gjtorikian** [comment]
Ohhh that's even better!

**Comment by Floppy** [comment]
Done in #452
