### ISSUE TITLE
Replaced 'colored' with 'colorize'

### ISSUE THREAD

**Issue by Floppy** [gjtorikian/html-proofer#449]
https://github.com/defunkt/colored is unmaintained, and not updated for 8 years now. https://github.com/fazibear/colorize is an alternative that's being looked after.

**Comment by fulldecent** [comment]
I have used colorize in other projects and it works just fine. This should be a simple replacement.

**Comment by mvz** [comment]
FYI, colorize is licensed under the GPL 2+ so not really a great choice for an MIT-licensed project.

**Comment by gjtorikian** [comment]
Oh no, thanks for bringing that up.

I'll switch to https://github.com/sickill/rainbow.
