### ISSUE TITLE
Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by agoncal** [gjtorikian/html-proofer#456]
Hi,

Sorry, I'm totally new to Ruby, gems and so on. When I install the gem (using `gem install html-proofer`) I get the following : 

```
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

$ gem install html-proofer
Fetching: mercenary-0.3.6.gem (100%)
Successfully installed mercenary-0.3.6
Fetching: mini_portile2-2.3.0.gem (100%)
Successfully installed mini_portile2-2.3.0
Fetching: nokogiri-1.8.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.8.1
Fetching: colorize-0.8.1.gem (100%)
Successfully installed colorize-0.8.1
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.4.0/gems/ffi-1.9.18/COPYING
```

I can see it's a permission denied, so I tried several things (even a `chmod 777`) but this does not work. 

Anything I have to do to install the gem and be able to use html_proofer as a [command line](https://github.com/gjtorikian/html-proofer#using-on-the-command-line) ?

Thanks

**Comment by Floppy** [comment]
If you're installing it globally, you'll need to use `sudo gem install html-proofer`. That shold do it. However, if you're using Ruby for other things too, I highly recommend using [rbenv](https://github.com/rbenv/rbenv) to manage different versions and install without `sudo`.

**Comment by agoncal** [comment]
Simple as that !

Thanks
