### ISSUE TITLE
Invalid URL error

### ISSUE THREAD

**Issue by robgarza** [gjtorikian/html-proofer#465]
Here is the HTML code in my file:

    <a href="https://www.azbn.gov/Documents/education/7.%20REFRESHER%20PROGRAMS/Refresher%20Course%20List.pdf">here</a>

The link works fine, but, HTML proofer reported this error:   

> *   https://www.azbn.gov/Documents/education/7.%20REFRESHER%20PROGRAMS/Refresher%20Course%20List.pdf is an invalid URL (line 183)

**Comment by robgarza** [comment]
@ilyalyo can you help please?

**Comment by fulldecent** [comment]
^ Confirmed broken

**Comment by robgarza** [comment]
Here is another example of a link that works fine but is reported as an error by HTML proofer:

Here is the code in my file:

    <a href="https://ibn.idaho.gov/IBNPortal/BoardAdditional.aspx?Board=IBON&BureauLinkID=150">the Board's FAQ Additional page.</a>

Here is the error message:

> *  General FAQs link: https://ibn.idaho.gov/IBNPortal/BoardAdditional.aspx?Board=IBON&BureauLinkID=150 is an invalid URL (line 189)

**Comment by robgarza** [comment]
Here is the code in my file

     <a href="http://mbon.maryland.gov/Documents/refresh_course.pdf">Link for approved refresher courses</a>

Here is the error message:

> *   http://mbon.maryland.gov/Documents/refresh_course.pdf is an invalid URL (line 173)

**Comment by ilyalyo** [comment]
@robgarza ok, I'll take this one

**Comment by ilyalyo** [comment]
I could reproduce this bug with ruby 2.2.5.
With ruby 2.4.1 issue is gone.

**Comment by robgarza** [comment]
It would appear that with ruby 2.4.1 the issue still was present for the following build:
https://travis-ci.com/fulldecent/mtssites/builds/62283720?utm_source=github_status&utm_medium=notification
![image](https://user-images.githubusercontent.com/19188985/34746513-46c973e0-f562-11e7-84f0-da5b5ce74b2e.png)
![image](https://user-images.githubusercontent.com/19188985/34746527-4e0d5eaa-f562-11e7-8d2e-b129c6037412.png)

**Comment by ilyalyo** [comment]
@robgarza turned out that all links marked as invalid were actually broken, they had space as a first character.
Private repository:
build with errors: https://travis-ci.com/fulldecent/mtssites/builds/62283720?utm_source=github_status&utm_medium=notification
commit with fixes: 
https://github.com/fulldecent/mtssites/commit/4e8774216da185e04cb02065484b273c91562a4c#diff-45dfa3e6ff44ff658e74e9077808eefa
After this commit builds doesn't have such errors

**Comment by gjtorikian** [comment]
solved
