### ISSUE TITLE
... possible to enforce terminal `/` for URLs that point to a directory?

### ISSUE THREAD

**Issue by bcreane** [gjtorikian/html-proofer#467]
For a URL that points to a directory (with an implied `/index.html` appended), is it possible for `html-proofer` to flag URLs that don't end in a `/`?

For example, assuming the site has `/some_directory/index.html`, is it possible to flag the second URL as a problem/warning:
```
  <a href="/some_directory/"> this is NOT an error </a>
  <a href="/some_directory"> flag this as an error </a>
```
The use-case is Google App Engine -- the easiest way to serve a Jekyll-generated website is to match URL regexes, and append `index.html` when there's a terminal `/`. But its easy to forget to append those `/`!

**Comment by gjtorikian** [comment]
Does [setting the `assume_extension: true` option](https://github.com/gjtorikian/html-proofer#using-with-jekyll) help your use case?

**Comment by bcreane** [comment]
Hi @gjtorikian - looks like `asume_extension: true` has no effect on whether `htmlproofer` requires a terminal `/` for directories.

**Comment by gjtorikian** [comment]
If this is still an issue, please reopen! HTMLProofer does have a [`unslashed_directory?`](https://github.com/gjtorikian/html-proofer/blob/5dd9fee6137dddf2533263603978c14fd77ce1d1/lib/html_proofer/attribute/url.rb#L140) that already can tell if a directory is missing a slash. But I'm not quite sure what the error is (GAE's server won't serve a file that leads to a directory unless the link ends in a slash?)
