### ISSUE TITLE
Add option for empty href

### ISSUE THREAD

**Issue by surdu** [gjtorikian/html-proofer#468]
I would be nice to have and option similar to `allow_hash_href` but to disallow empty hrefs.

**Comment by iBobik** [comment]
Could you please describe a few use-cases where is it needed?

**Comment by surdu** [comment]
I had generated html and the href was generated using a variable that was empty.

Also, forget to add href to an url ?

**Comment by iBobik** [comment]
Correct me if I am wrong, but isn't it default now? I expected that if I write something like: `<a href="">` html-proofer will fail on it.

**Comment by surdu** [comment]
I'll have to dust-off the project and take a look.

**Comment by gjtorikian** [comment]
In [the upcoming 4.x release](https://github.com/gjtorikian/html-proofer/issues/669) `allow_missing_href` now exists for this

**Comment by gjtorikian** [comment]
For added context: HTML5 spec actually allows for missing hrefs, but I feel like more often than not this omission would be human error. So we go against the spec by default, but you can pass the flag in if you really want to allow missing hrefs.
