### ISSUE TITLE
Advice on how to adjust links when checking locally

### ISSUE THREAD

**Issue by peterhartman** [gjtorikian/html-proofer#471]
I am trying to check the output of my static site generator. I cannot work out how to "fix" the link error I am getting though. Locally the files are in `dist/unauth`, when they are served the server adds a` /one/help/` to the base so I am getting a bunch of false errors of the type:
```
internally linking to /one/help/unauth/prism/prism.css, which does not exist (line 15)
<link rel="stylesheet" href="/one/help/unauth/prism/prism.css">
```

I have tried `--url-swap` with no luck:
`htmlproofer --url-swap "\/one\/help\/unauth\/:\/" dist/unauth`

**Comment by gjtorikian** [comment]
Can you try `bin/htmlproofer <PATH> --url-swap "dist/unauth:/one/help/dist/unauth"`?

I tested this locally and that should work. The options for `url-swap` are a bit wonky, but basically you don't need to do `/` escaping or anything else in the original regexp.

**Comment by peterhartman** [comment]
Sadly no luck...

`prism.css` is on my file system here:
`dist/unauth/prism/prism.css`

The href link is:
`/one/help/unauth/prism/prism.css`

I have tried:
`htmlproofer dist/unauth --url-swap "dist/unauth:/one/help/unauth"`
and
`htmlproofer dist/unauth --url-swap "/one/help/unauth:dist/unauth"`
and
`htmlproofer dist/unauth --url-swap "/one/help/unauth:unauth"`

With no luck.

**Comment by gjtorikian** [comment]
There isn’t, but I think it’s a good feature request to have. I had to clone this repo down and manually insert `puts` statements to see how the original URL changed.

**Comment by gjtorikian** [comment]
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) has been completely rewritten  and this is no longer a problem. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️ 4.x should be out within the month.
