### ISSUE TITLE
403 on  https://www.oracle.com domain with Travis only

### ISSUE THREAD

**Issue by henri-tremblay** [gjtorikian/html-proofer#483]
It seems related to #197 but since it is fixed, no idea what is happening.

I am linking links such as https://www.oracle.com/code-one/index.html. If I run htmlproofer locally, everything is alright.

But when running on Travis with the exact same command (`bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html`), it fails (403 No Error). You can see such a failure here: https://travis-ci.org/henri-tremblay/henri-tremblay.github.io/builds/410649162

Of course, doing a cURL works as well.

Version 3.9.1 is used.

Any idea of what is going on?

**Comment by henri-tremblay** [comment]
Yes. However, the build finally passed right after... After having failed for a week. No idea why. I will try if it goes back to failing. Right now the default is a Mozilla look alike no?

**Comment by gjtorikian** [comment]
Yes, the default is Mozilla look-alike, but with some html-proofer info attached to it: `"Mozilla/5.0 (compatible; HTML Proofer/#{VERSION}; +https://github.com/gjtorikian/html-proofer)"`

So it's possible that that site banned any UA string which also said `html-proofer`?

I'm curious to know what you changed the UA to to get it to work. 

As well it may simply be that something on Oracle's end is screwed up. 😆

**Comment by henri-tremblay** [comment]
I haven't changed anything. It just passed. But failing again today. I will try to play with the user agent

**Comment by henri-tremblay** [comment]
Is there a way to do it through command line? I'm currently doing `bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html`

**Comment by adamdmharvey** [comment]
As awareness as we ran into a similar "intermittent issue" on our site, although not with HTTP 403.  It could be possible that Oracle is returning that as an abuse mechanism.  In our case, we were hitting GitHub with requests and our first pipeline run html-proofer ran fine. But if you ran the pipeline a second time in less than 5 minutes, we began to receive HTTP 420 Too Many Requests errors indicating we'd hit their abuse limit.  So it's possible HTTP 403 in your case is Oracle saying, "hang on computer user agent, you look like a spider crawling me, back off, i'm going to block any more requests for an hour".

Just a thought!

**Comment by Floppy** [comment]
Are you using the `libcurl4-openssl-dev` package on travis as mentioned in https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis? Not sure if it's relevant in this case, but it resolved some strange connection errors on Travis a while back.

**Comment by fulldecent** [comment]
I think https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis is the issue.

I started that one, but I'd like some help to get the same thing for GitHub Actions. That's a separate task if anyone's interested.

Either way closing this issue for now. Can reopen if evidence is found that it is not the libcurl4-openssl-dev issue.
