### ISSUE TITLE
Reported results are not consistent 

### ISSUE THREAD

**Issue by codedbypm** [gjtorikian/html-proofer#485]
Hi,

I started using htmlproofer after I saw it mentioned in the Jekyll official guide. 
I love the idea of proofing my HTML but I noticed that when Travis runs it, results are not consistent. Some links are reported sometimes good and sometimes not (even without changes in the source code).
Is anyone experiencing the same? Is there a way to fix this random behaviour? 
Thanks

Paolo

**Comment by gjtorikian** [comment]
Hi, do you have an example of output where the links are sometimes good and sometimes not?

**Comment by codedbypm** [comment]
Last one I got was this 

https://www.knab.nl/ failed: response code 0 means something's wrong. It's possible libcurl couldn't connect to the server or perhaps the request timed out. Sometimes, making too many requests at once also breaks things.


Most of the times  the above url doesn’t give any problem. Not sure if there is something wrong in my setup or not.

**Comment by codedbypm** [comment]
This is the repo where my code is. I use Jekyll, build with Travis and publish on github pages 

https://github.com/codedbypm/codedby.pm

**Comment by fulldecent** [comment]
Can you please link to the two subject Travis outputs so we can analyze further?

**Comment by fulldecent** [comment]
Closing not actionable. Can reconsider to reopen with more evidence.
