### ISSUE TITLE
Is it possible to map an external URL pattern to make it appear local?

### ISSUE THREAD

**Issue by pete-woods** [gjtorikian/html-proofer#489]
I'm generating my blog using Hugo and testing with htmlproofer on the CLI.

In some places Hugo generates absolute URLs for some links, and htmlproofer tries to validate these as external URLs. So if I add a new post in the blog, the index's reference to it fails, as it checks against my live blog deployment, instead of checking the local filesystem.

It'd be great if I could tell htmlproofer that e.g. `https://pete-woods.com` was the external path of my site, and to treat URLs starting with that path as internal.

**Comment by pete-woods** [comment]
Currently I have to do
```
--url-ignore='/pete-woods.com/'
```

**Comment by StaphSynth** [comment]
I'm having the same issue in Jekyll. The Jekyll SEO plugin uses absolute URLs which causes the build to fail because the page doesn't exist in production yet.

**Comment by pete-woods** [comment]
Just having a browse through the source, while I have a bit more time:
`p.option 'internal_domains', '--internal-domains domain1,[domain2,...]', Array, 'A comma-separated list of Strings containing domains that will be treated as internal urls.'`

**Comment by pete-woods** [comment]
That switch worked for me.
