### ISSUE TITLE
Ignore invalid URLs inside template elements

### ISSUE THREAD

**Issue by aarongustafson** [gjtorikian/html-proofer#492]
[HTML templates](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) are used for JavaScript and often contain placeholders or empty attributes. HTML proofing rules for links, images, etc. should not be run in there.

**Comment by Floppy** [comment]
Interesting, I'd not come across this tag before. From the MDN page:

> While the parser does process the contents of the `<template>` element while loading the page, it does so only to ensure that those contents are valid; the element's contents are not rendered, however.

presumably html-proofer should do the same, though I'm not clear on what "valid" means in this case.

**Comment by gjtorikian** [comment]
I'm also not familiar with this tag! @aarongustafson could you show me a real-world HTML snippet where html-proofer is erroneously interfering with tags inside of a `<template>`?

**Comment by gjtorikian** [comment]
no response
