### ISSUE TITLE
Checking anchors isn't working for me

### ISSUE THREAD

**Issue by plaindocs** [gjtorikian/html-proofer#493]
Apologies for the quasi support nature of this issue.

I'm having trouble checking (internal) anchors in the Travis CI docs, even with `check_external_hash: true`. 

Most of the internal links are relative, due to netlify preview urls, so not sure that the internal domain setting is doing anything. 

A lot of them are case changes only (such as https://github.com/travis-ci/docs-travis-ci-com/pull/2050/files ) 

If you have any ideas on what I'm doing wrong that would be awesome. 

```
desc 'Runs the html-proofer test'
task :run_html_proofer => [:build] do
  HTMLProofer.check_directory(
    './_site',
    internal_domains: ['docs.travis-ci.com'],
    check_external_hash: true,
    check_html: true,
    connecttimeout: 600,
    allow_hash_ref: true,
    only_4xx: true,
    typhoeus: {
      ssl_verifypeer: false, ssl_verifyhost: 0, followlocation: true
    },
  ).run
end
```

**Comment by gjtorikian** [comment]
https://github.com/travis-ci/docs-travis-ci-com/pull/2050 is a passing build. Could you show me a failing build where this is occurring?

**Comment by plaindocs** [comment]
Hey @gjtorikian 

Thanks for the ping back.

I'm made a PR reverting that fix:

https://github.com/travis-ci/docs-travis-ci-com/pull/2052

The link from the home page is (which does not exist):

https://5bbe13adfdd72a52fbcf4c30--musing-lamport-7fb66c.netlify.com/user/notifications/#Changing-the-email-address-for-build-notifications 

And the actual anchor (which does exist) is: 

https://5bbe13adfdd72a52fbcf4c30--musing-lamport-7fb66c.netlify.com/user/notifications/#changing-the-email-address-for-build-notifications

htmlproofer does not report any errors: 

https://travis-ci.org/travis-ci/docs-travis-ci-com/builds/439683402#L646
