### ISSUE TITLE
Add support for Open Graph entries

### ISSUE THREAD

**Issue by brunogirin** [gjtorikian/html-proofer#494]
The [Open Graph protocol](http://ogp.me/) specifies metadata properties that allow services to process the page in a smarter way. For instance, this is how Facebook or Twitter will identify what image to use when that page is posted in a comment. This protocol is used heavily with blogs. Some of those properties have URL values. It would be good to validate those.

Example HTML snippet:

```html
<meta property="og:url" content="https://example.com/" />
<meta property="og:type" content="website" />
<meta property="og:title" content="My great blog post" />
<meta property="og:image" content="https://example.com/assets/myimage.jpg" />
```

In the example above, the `og:url` and `og:image` both specify a URL so it would be good to check them to ensure they are not broken. A broken URL will typically only be visible when someone reference the page on social media so may go undiscovered for some time.

**Comment by gjtorikian** [comment]
Hi, by default this is disabled, but if you pass `check_opengraph: true` to your script (or `--check-opengraph` through the command line) this ought to work.

Hope this helps!

**Comment by brunogirin** [comment]
Thanks @gjtorikian I didn't realise it was already possible to do so! That will teach me to RTFM, sorry about the query.
