### ISSUE TITLE
OpenGraphCheck fails to check og:image

### ISSUE THREAD

**Issue by brunogirin** [gjtorikian/html-proofer#510]
When having an OpenGraph meta tag with property `og:image`, OpenGraphCheck fails to validate the `content` of the tag.

Example: with the following tab in the `head` of a web page:

```
<meta property="og:image" content="https://www.imby.bio/assets/img/blog/2019-02-01-heralding-spring-small.jpeg">
```

I would expect OpenGraphCheck to identify that there is a typo in the content URL (it should be 2019-03-01 rather than 2019-02-01). However, it failed to pick it up.

**Comment by vllur** [comment]
I think there can be implemented check for such links, but these can be quite difficult due to sometimes occurring connection problems with curl.

Imo this should come with switch in the task for having the ability to turn it off painlessly, or something similar, to prevent possible headaches.

**Comment by gjtorikian** [comment]
@brunogirin Did you run this check with the [`--check_opengraph`](https://github.com/gjtorikian/html-proofer#configuration) flag on?

It defaults to off. This is the second issue on a month around this though so I'm now thinking I should set it to default on... anyway, let me know if it was a problem with the argument, or if that argument wasn't included. Thanks!

**Comment by brunogirin** [comment]
@gjtorikian yes, I ran it with the flag on, the output while running is:

```
Running ["ScriptCheck", "OpenGraphCheck", "ImageCheck", "LinkCheck"] on ["_site"] on *.html...
```

**Comment by gjtorikian** [comment]
`--check-opengraph` is for the command-line, while `check_opengraph` is if you are using the tester through your code directly. Sorry, I believe I mixed those up in my earlier comment!

I'm able to reproduce this problem and am looking into it. Sorry for the trouble!

**Comment by gjtorikian** [comment]
Hmm. Could you tell me a little bit more about how you ran the command? Something like `bin/htmlproofer --check-opengraph spec/html-proofer/fixtures/opengraph/image-broken.html` is showing that the image is (correctly) broken.

If it's possible to share the entire HTML file, that would also be helpful.

**Comment by brunogirin** [comment]
@gjtorikian I ran `htmlproofer` on a Jekyll site so the final command is: `bundle exec htmlproofer _site --only-4xx --allow-hash-href --check-opengraph`

The HTML file is this blog post albeit with an incorrect `og:image` `meta` tag: https://www.imby.bio/gardening/2019/02/26/heralding-spring.html

**Comment by gjtorikian** [comment]
Hrm, I still cannot actually reproduce this (when I thought I had reproduced it earlier, I was mistaken).

What does `bundle exec htmlproofer -v` spit out?

**Comment by brunogirin** [comment]
htmlproofer 3.10.2

Is there a way to trace what checks it does for each file? The `-t` options seems to only report on failure whereas it would be good to have verbose output that shows what test each file triggers.

**Comment by gjtorikian** [comment]
Sure, you can set log level to get more debug output:

```
--log-level <level>  Sets the logging level, as determined by Yell. One of `:debug`, `:info`, `:warn`, `:error`, or `:fatal`. (default: `:info`)
```

**Comment by brunogirin** [comment]
A recent upgrade to v3.10.2 fixed that issue so I will close it. Thank you for this great tool!
