### ISSUE TITLE
Checks external hashes fails for GitHub code snippets

### ISSUE THREAD

**Issue by arturoherrero** [gjtorikian/html-proofer#511]
Hi there!

Thank you very much for this tool. I'm configuring html-proofer for my website and I'm getting errors with some links to GitHub code snippets.

For those that are not familiar with that feature, here's a post explaining it: https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet

You can test it with any file of this repository, eg:
https://github.com/gjtorikian/html-proofer/blob/master/Rakefile#L14-L29

It doesn't seem to have consistent behavior with the cache option. Some times if the cache it's enabled only fails for the first time but after that, it doesn't complain. In case of testing, please disable any caching option.

Thanks.

**Comment by gjtorikian** [comment]
I can't reproduce this: https://travis-ci.org/gjtorikian/html-proofer/builds/503333182

Could you share the HTML file you're using, or the error message output?

**Comment by arturoherrero** [comment]
This one is failing for me (not actually failing because I have a `rescue` block in the Rakefile):
https://travis-ci.org/arturoherrero/arturoherrero.com/builds/503367980
