### ISSUE TITLE
PRE blocks ignored

### ISSUE THREAD

**Issue by geeknoid** [gjtorikian/html-proofer#514]
Seems that html-proofer does not check links in PRE blocks, as per:

https://github.com/gjtorikian/html-proofer/blob/19c55fdbf4cd2d35c037ffc864681f4d7b2c0a3d/lib/html-proofer/check.rb#L59

I understand why it skips over CODE blocks, but it seems incorrect that it skips over PRE blocks. PRE just says that the content is preformatted, but doesn't say indicate any other semantic change for its content. In my case, I've actually got anchor tags inside PRE blocks and I just realized that they're not being validated when I thought they were.

Thanks.

**Comment by gjtorikian** [comment]
I hear what you're saying, but it's tough to accept `pre` as anything but code, as most syntax highlighters now abuse it for showing code. GitHub, for example, renders blocks with this markup:

```html
<div class="highlight highlight-source-ruby">
<pre>
<span class="pl-k">def</span> 
<span class="pl-en">wow</span>
</pre>
</div>
```

That is, people have embedded semantic meaning into the tag.

If you feel strongly about it please feel free to reopen, as I'm having some doubts myself. But to keep a tidy repo I will have to close this issue.

**Comment by jamietanna** [comment]
As an FYI the way I got around this was to [monkey patch the library](https://gitlab.com/jamietanna/jvt.me/commit/5b028ac3cdfe363318da8ed8eb45b05cd9a690ea) by replacing the original implementation of `HTMLProofer::Check#remove_ignored` with my own:

```ruby
module HTMLProofer
  class Check
    # Monkey patch so we don't remove <pre>, <code>, or <tt> elements
    def remove_ignored(html)
      html
    end
  end
end
```

**Comment by gjtorikian** [comment]
That works too!
