### ISSUE TITLE
Using html-proofer on collections of Jekyll posts

### ISSUE THREAD

**Issue by StudioSpindle** [gjtorikian/html-proofer#515]
Perhaps a bit off topic for just html-proofer, since it seems to be a combination with jekyll. But perhaps someone has experience with this combination.

We're running into a problem where normal pages are working fine, however collection pages are not found by html-proofer. 

example error:
```
- ./_site/blog/choose-a-datasource.html
  *  internally linking to /blog/choose-a-datasource, which does not exist (line 82)
     <a href="/blog/choose-a-datasource" class="current">Choose a data source</a>
```

In the following Travis report the collection articles with 'blog' are not found:
https://travis-ci.org/semi-technologies/semi-website/builds/514826595#L1065

However, in the source folder the the page does exist: 
https://github.com/semi-technologies/semi-website/tree/permalinks/_blog

And a jekyll build succesfully builds them into `./_site`.

(As stated in the [config](https://github.com/semi-technologies/semi-website/blob/permalinks/_config.yml#L9) this should indeed output `/blog/choose-a-datasource`.)

Perhaps this has something to do with the collection folder is in the root of the project, but it's prefixed with an underscore?

**Comment by StudioSpindle** [comment]
Turned out the cause were trailing slashes behind URL's `/`.

**Comment by gjtorikian** [comment]
https://github.com/gjtorikian/html-proofer#using-with-jekyll may also have helped, unsure if you saw that.
