### ISSUE TITLE
Add ability to customize the output to hook into reporting tools

### ISSUE THREAD

**Issue by jamietanna** [gjtorikian/html-proofer#516]
It'd be cool to have GitLab CI's [Coverage](https://docs.gitlab.com/ee/ci/yaml/#coverage) functionality determine how many links are passing/failing.

However, we'd need to allow the output to for instance say:

```
1234 / 1256 links resolved
```

**Comment by fulldecent** [comment]
Closing as out of scope. (We do have a scope statement https://github.com/gjtorikian/html-proofer#project-scope) This is currently possible with "advanced" Ruby configuration.

Would consider this in scope if there is a specific, documented, industry-standard output formatting for reporting tools.

An effort for that is started here https://github.com/fulldecent/structured-acceptance-test
