### ISSUE TITLE
Add ability to only check one of internal/external links

### ISSUE THREAD

**Issue by jamietanna** [gjtorikian/html-proofer#517]
It'd be helpful to be able to be able to switch between only verifying internal or external links.

For instance, I'd link to have two key checks within my pipelines:

- Internal links are well-formed
- External links are well-formed, but are allowed to fail

**Comment by gjtorikian** [comment]
You can set `disable_external: true`, and this will ensure the well-formedness, but not perform an external link check.

**Comment by jamietanna** [comment]
Ah thanks, I missed that in the docs!
