### ISSUE TITLE
Add ability to dump output to a file

### ISSUE THREAD

**Issue by altcointrading** [gjtorikian/html-proofer#521]
For the commandline tool. 

Standard bash like `>` or `2>&1` doesn't work.

**Comment by hungbui20384** [comment]
Ok

**Comment by gjtorikian** [comment]
I think this issue might be outdated. Regardless, I'm working on [the next version](https://github.com/gjtorikian/html-proofer/issues/669) of HTML Proofer and verified that the ` &> links.log` redirection works.
