### ISSUE TITLE
html-proofer failed to pick up html validation errors

### ISSUE THREAD

**Issue by Raza403** [gjtorikian/html-proofer#526]
**Test Case** 
https://github.com/Raza403/test

In `index.html` there are
- [ ] Couple of divs without closing tags
- [ ] A `<p>` element without closing tag
- [ ] One stray `<hr>` tag, which is after `</html>`

**And build tested with `html-proofer` is passing here**
https://travis-ci.com/Raza403/test/builds/120699310

The same code was run through https://validator.nu and following errors are found.
![1](https://user-images.githubusercontent.com/20680336/61590037-078efc00-abcc-11e9-9280-51b758693273.png)

**Comment by fulldecent** [comment]
Thank you @Raza403 can you please enable Travis on that repository so we can see the output?

**Comment by fulldecent** [comment]
Thank you, Travis link is in here

**Comment by gjtorikian** [comment]
Thanks, seems dependent on https://github.com/gjtorikian/html-proofer/pull/362.

**Comment by gjtorikian** [comment]
Should be fixed by https://github.com/gjtorikian/html-proofer/pull/362

**Comment by fulldecent** [comment]
FYI going forward please create issues like this by adding test cases to this project rather than creating a separate project
