### ISSUE TITLE
Timerizer dependency conflicts with ActiveSupport

### ISSUE THREAD

**Issue by cpruitt** [gjtorikian/html-proofer#535]
We're running issues at GitHub with the 3.12.0 HTMLProofer update, specifically with the new dependency on Timerizer introduced in https://github.com/gjtorikian/html-proofer/pull/534.

On one hand this is an important update because it removes the dependency on ActiveSupport `< 6.0`, which is necessary for Rails 6.0. On the other hand, it swaps the ActiveSupport dependency for Timerizer which is not playing very nice with ActiveSupport.

## The Problem

We're running into issues that appear to stem from `html-proofer` requiring `timerizer` after ActiveSupport has been loaded. This leads to Timerizer shadowing ActiveSupport integer helpers. (Incidentally, `timerizer` defines helper methods on `Integer` whereas `activesupport` defines them on `Numeric`, so coercing to float will still use the AS helper methods). Example:

```ruby
1.minute.class
# => ActiveSupport::Duration

require 'timerizer'
# => true

1.minute.class
# => Timerizer::Duration

1.to_f.minute.class
# => ActiveSupport::Duration
```

In a Rails app we really don't want Timerizer in the mix anyway as we want to ensure Rails' Activesupport is being used, but it's particularly a problem because Timerizer does not correctly compare durations with integers. So any comparisons made against the return value of a helper method (even if assigned to a variable and used somewhere later down the road) will raise an exception:

```ruby
1.minute.class
# => ActiveSupport::Duration
1.minute > 1
# => true

require 'timerizer'
# => true

1.minute.class
# => Timerizer::Duration
1.minute > 1
# ArgumentError: comparison of Timerizer::Duration with 1 failed
```

## So then...

I'm wondering if Timerizer can be a soft dependency of HTMLProofer so that it's not loaded into a Rails app unless specifically required. (We definitely want to avoid loading it.) Additionally, it seems like it would make sense for HTMLProofer to use ActiveSupport if it's available and fall back to requiring Timerizer otherwise.

Given that Timerizer is intended as an alternative to ActiveSupport's time helpers, and given that an app that uses ActiveSupport probably shouldn't also use that alternative (because of the conflicts) I think it's probably pretty important to keep it out unless explicitly required by the app itself.

**Comment by gjtorikian** [comment]
Ugh, I thought this might happen. 

Since the portion of the time parsing that I actually need is small, and I don't like pulling in dependencies that aren't necessary, I just went ahead and implemented the duration math myself. Thanks for the report!
