### ISSUE TITLE
Error:  undefined method `xpath' for nil:NilClass

### ISSUE THREAD

**Issue by nickoe** [gjtorikian/html-proofer#544]
With the latest version of htlm-proofer 3.14.0 I get this error for my site. For example my command and output is as follows:

```
htmlproofer ./public --external_only --only_4xx --url-ignore "/www.digikey.com/"
Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["./public"] on *.html... 
htmlproofer 3.14.0 | Error:  undefined method `xpath' for nil:NilClass
The command "htmlproofer ./public --external_only --only_4xx --url-ignore "/www.digikey.com/"" exited with 1.
Done. Your build exited with 1.
```

https://travis-ci.org/KiCad/kicad-website/builds/613212365

**Comment by gjtorikian** [comment]
Sorry about that, there was a typo in one of the methods being used. A bugfix will be pushed shortly.

**Comment by nickoe** [comment]
@gjtorikian Thank you for the quick fix and release. I will go back to using latest release again.
