### ISSUE TITLE
Is it possible to weaken the nokogumbo dependency to version 1.4 and above?

### ISSUE THREAD

**Issue by dleidert** [gjtorikian/html-proofer#546]
Hi there,

the latest release changed from nokogiri to nokogumbo >= 2.0. We are using version 1.4 because of several dependencies. Is there any way to "weaken" the versioned dependency on nokogumbo to version 1.4 and above?

Regards, Daniel

**Comment by gjtorikian** [comment]
There unfortunately is not. In https://github.com/gjtorikian/html-proofer/pull/362 we waited for 2+ years for a feature in 2.0.0 to land. I would always recommend the other dependencies to run the latest and greatest!
