### ISSUE TITLE
html-proofer failed to pick up html validation errors

### ISSUE THREAD

**Issue by Raza403** [gjtorikian/html-proofer#547]
Test Case @ https://github.com/Raza403/test
In `index.html` there are
- A couple of `divs` without closing tags.
- A `p` element without closing tag.
- One stray `hr` tag which is after `</html>` tag.

Build tested with `html-proofer` version 3.15.0 is passing this, link below
https://travis-ci.com/Raza403/test/builds/142460902

The same code was run through https://validator.nu and the following errors were found.
![1](https://user-images.githubusercontent.com/20680336/71548678-69515e80-29d3-11ea-9027-28d40f107204.png)

**Comment by gjtorikian** [comment]
Thanks for the report.

The parser relies on [nokogumbo](https://github.com/rubys/nokogumbo), so a report should be filed for that repo/project. 

Keep in mind that HTML5 has _very_ lax parsing rules; if you open that file up in a browser you can see that the page can still render. In fact, nokogumbo itself rewrites the page to look like this:

```html
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE html>
<html lang="en"><head>
    <title>Test case for html-proofer not catching all errors in html.</title>
  </head>

  <body>
      <div class="container">
        <p>Container  without end tag</p>
          <div class="wrapping">
            <p>wrapping  without end tag and  tag without end tag.
  


</p><hr/>
</div></div></body></html>
```

Still, I generally agree that if errors like these can be reported by the parser, it would be best.
