### ISSUE TITLE
Possible to add a delay from command line?

### ISSUE THREAD

**Issue by pschloss** [gjtorikian/html-proofer#558]
I really appreciate html-proofer - thanks! I have a Jekyll site that I've built to hold a wiki with a mixture of internal and external links. When I run html-proofer, I get dinged with a bunch of 429 errors. Most of these are to github. I've read through #131, but I'm not really sure what to do with that information to add a pause for each external url. I know I can ignore 429's, but I'd also like to know that those links are good. Can anyone help me with the syntax for adding a wait time?

**Comment by gjtorikian** [comment]
Since #577 proofer has supported setting `before_request`, which is called before every external request. For your use case you could so something like:

```ruby
proofer = HTMLProofer.check_directory(item, opts)
proofer.before_request do |request|
  sleep 3 # wait 3 seconds before checking next URL
end
proofer.run
```

hope this helps
