### ISSUE TITLE
invalid attribute name `;' (NameError)

### ISSUE THREAD

**Issue by m-reuter** [gjtorikian/html-proofer#559]
I am getting the following error (both locally and on travis):

bundle exec htmlproofer ./_site

htmlproofer 3.15.1 | Error:  invalid attribute name `;'
Traceback (most recent call last):
	45: from /path/.rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
...
/path/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/html-proofer-3.15.1/lib/html-proofer/element.rb:17:in `attr_reader': invalid attribute name `;' (NameError)

Could this be a bug in element.rb ?

**Comment by gjtorikian** [comment]
Is it possible to get a copy of your site so I can reproduce this locally?

**Comment by m-reuter** [comment]
sure: https://github.com/Deep-MI/Deep-MI.github.io

**Comment by gjtorikian** [comment]
Thanks, the latest release (3.15.2) should fix this.

**Comment by m-reuter** [comment]
thanks for the fast solution!
