### ISSUE TITLE
Can't install html-proofer with ruby v2.7

### ISSUE THREAD

**Issue by torn4dom4n** [gjtorikian/html-proofer#561]
I try install `html-proofer` on windows 10 with `ruby` v2.7. An error occurred while installing `nokogiri (1.10.9)`.
![image](https://user-images.githubusercontent.com/27698189/80244235-cd8ae300-8692-11ea-8062-abc732155628.png)

**Comment by gjtorikian** [comment]
It says right there the problem is with the [Nokogiri](https://github.com/sparklemotion/nokogiri) project reqiruing Ruby versions < 2.7.dev, and you are using 2.7.1. 

A quick search in their issues shows the problem: https://github.com/sparklemotion/nokogiri/issues/2025
