### ISSUE TITLE
Cache does not support Norwegian characters

### ISSUE THREAD

**Issue by Sankra** [gjtorikian/html-proofer#563]
I tried to use HTMLProofer on my [Norwegain site](https://pappaperm.com/). The tool itself runs without error, but the cache struggles with Norwegian characters it seems:

<img width="762" alt="undefined-conversion-error" src="https://user-images.githubusercontent.com/634968/80857126-d01ba880-8c4f-11ea-9f0e-551ef4762319.png">

I used the following config:

```ruby
options = {
    :assume_extension => true,
    :check_favicon => true,
    :check_opengraph => true,
    :check_html => true,
    :check_img_http => true,
    :only_4xx => true,
    :http_status_ignore => [ 403 ],
    :cache => { :timeframe => '12h' },
    :parallel => { :in_processes => 8 }
}
HTMLProofer.check_directory("./_site", options).run
```

HTMLProofer runs successfully with `cache => { :timeframe => '12h' }` removed.

**Comment by gjtorikian** [comment]
Hi there--the latest version of HTML-Proofer is 3.15.3, and you're running 3.11.1. Could you try upgrading and seeing if that resolves it? Some changes to the cache functionality took place between those two.

**Comment by Sankra** [comment]
Sorry for the late reply, but the problem is present in 3.15.3 too.

<img width="762" alt="Screenshot 2020-05-05 at 09 03 20" src="https://user-images.githubusercontent.com/634968/81041959-61d52100-8eaf-11ea-8e5e-388dc09771af.png">

**Comment by gjtorikian** [comment]
I've [tested this](https://github.com/gjtorikian/html-proofer/compare/no-norwegian) with a link to https://pappaperm.com/innlegg/idiotmarkedsføring.html, but there are no errors. Can you think of any other URL which might be causing an error?

**Comment by riccardoporreca** [comment]
Possibly related encoding "issue" (in the way URL are defined, not with HTMLProofer): https://github.com/gjtorikian/html-proofer/issues/662#issuecomment-979507172

**Comment by gjtorikian** [comment]
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) has been completely rewritten  and this is no longer a problem. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️ 4.x should be out within the month.
