### ISSUE TITLE
img width="280px" should throw Error

### ISSUE THREAD

**Issue by thisconnect** [gjtorikian/html-proofer#564]
```
<!doctype html>
<meta charset="utf-8">
<title>asdf</title>
<img width="280px" height="120px" src="file.jps" alt="drawing" >
```

Using html-proofer 3.15.3 it is all good, but
validator.w3.org/nu does complain about `width="280px"` 

https://validator.w3.org/nu/#textarea

### expected 
something like 
Error: Bad value 280px for attribute width on element img: Expected a digit but saw p instead.

**Comment by gjtorikian** [comment]
[HTML Validation is performed by Nokogumbo](https://github.com/gjtorikian/html-proofer#html), and so the issue should be opened there.

**Comment by thisconnect** [comment]
@gjtorikian there is an interesting reply by @stevecheckoway

> I hope html-proofer isn't relying on Nokogumbo to do that validation because it never has and is unlikely to do so in the near future, if ever. Although I agree that functionality would be very useful.

See https://github.com/rubys/nokogumbo/issues/147

**Comment by gjtorikian** [comment]
Ok, I will look into this in a week or so. I'm working on a dissertation at the moment.

**Comment by thisconnect** [comment]
> Ok, I will look into this in a week or so. I'm working on a dissertation at the moment.

Thank you so much ❤️  !  no rush.

**Comment by gjtorikian** [comment]
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) won't have HTML checking at all anymore. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️
