### ISSUE TITLE
button in anchor should throw an error

### ISSUE THREAD

**Issue by thisconnect** [gjtorikian/html-proofer#565]
A button inside an anchor, doesn't make much sense and throws an error in w3's validator
https://validator.w3.org/nu/#textarea

Error: The element button must not appear as a descendant of the a element.

Would be nice if html-proofer would catch and error too.

### minimal example
```html
<!doctype html>
<title>no button in anchor</title>
<meta charset="utf-8">
<a href="https://base.shiftcrypto.ch/">
    <button class="button primary shadow">View documentation</button>
</a>
```

**Comment by fulldecent** [comment]
Please cite relevant specification in WHATWG if possible.

**Comment by thisconnect** [comment]
That's the only thing I found

> The a element can be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g., buttons or other links).

https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

**Comment by gjtorikian** [comment]
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) won't have HTML checking at all anymore. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️
