### ISSUE TITLE
href attribute on elements other than anchor & link elements should error

### ISSUE THREAD

**Issue by thisconnect** [gjtorikian/html-proofer#566]
https://validator.w3.org/nu/#textarea errors with

Error: Attribute href not allowed on element span at this point.

```html
<!DOCTYPE html>
<meta charset="utf-8">
<title>href on other elements than anchors</title>
<span href="#test">test</span>
```

❤️

**Comment by gjtorikian** [comment]
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) won't have HTML checking at all anymore. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️
