### ISSUE TITLE
External embeds

### ISSUE THREAD

**Issue by penibelst** [gjtorikian/html-proofer#57]
Inspired by the discussion with @parkr about privacy I want to propose an optional checking for external embedded resources: images, styles, scripts, … External embeds lack many things.
1. **Reliability** — External servers come, go, and stay. The best current example was published lately: [Don’t Use jquery-latest.js](http://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/).
2. **Speed** — Every external connection means a new time consuming connection opening.
3. **Privacy** — if you respect your visitors, you don’t let them be tracked.

High quality websites only serve from own hosts. If I migrate an old website, first thing I do is to collect all embedded resources. Then I can really control what happens on _my_ website.

The option also would help big teams with many authors to take care, because lazy authors sometimes embed images from Tumblr instead of uploading to own server.

Scenario:
- We serve from `www.example.com`
- Our assets are `assets.example.com`

The option must check all external resources, (e. g. `http://code.jquery.com/jquery-latest.min.js`) except your own external server.

How would you design such an option?

**Comment by penibelst** [comment]
Related:
* Tool: [Request Map Generator](http://requestmap.webperf.tools/)
* Explanation: [How to find the third-parties on your site](http://webperf.ninja/2015/find-third-party-assets/)
* Author: [Simon Hearne](http://simonhearne.co.uk/)

**Comment by parkr** [comment]
Are you still working on this?

**Comment by fulldecent** [comment]
@penibelst Are you recommending to flag all external links as error? I.e. same result as `git grep //`?

**Comment by fulldecent** [comment]
Recommending to close issue as abandoned
