### ISSUE TITLE
Fail if no files are checked

### ISSUE THREAD

**Issue by asbjornu** [gjtorikian/html-proofer#570]
If, for some reason, the directory HTMLProofer is set to check is empty, HTMLProofer finishes with exit code `0`, writing the following to `stdout`:

> Ran on 0 files!

It would be neat if this could be configured as a failure condition with something like `--minimum-files-checked=<number>` so a CI/CD build fails if no files are produced during `jekyll build`, for instance.

**Comment by gjtorikian** [comment]
Sorry but I will have to close this out as I don't think it should be core to HTMLProofer. If the directory is empty, it seems to me that the thing that should've built the files (in this case, Jekyll) should be checked, not the proofer.
