### ISSUE TITLE
Allow for not checking all URLs

### ISSUE THREAD

**Issue by reesericci** [gjtorikian/html-proofer#571]
@gjtorikian I think it would be useful to have a flag that says "don't check any urls for validity" because all of my URLS work but work in a weird way that html-proofer doesn't like.

**Comment by Floppy** [comment]
What's the wierd way? What doesn't html-proofer like about them? If they're navigable, html-proofer really ought to be able to check them correctly...

**Comment by reesericci** [comment]
It's just really hard to explain.

Reese Armstrong
"The best at everything, ever."
reesericci@nyctech.cloud (https://link.getmailspring.com/link/3F0A9FB8-0DB6-4ED2-A2B9-996C2D37D754@getmailspring.com/0?redirect=mailto%3Areesericci%40nyctech.cloud&recipient=cmVwbHkrQUVWT1BEVTIzS081UVFQNjdEVk9TTlY1QkY0RTdFVkJOSEhDTk1IRTZVQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by reesericci** [comment]
@Floppy Basically, the links are only navigable/created once the site is deployed. (Using Jekyll)

**Comment by Floppy** [comment]
Ah, gotcha. You might be interested in https://github.com/Floppy/jekyll-test, which is a pre-built configuration for testing jekyll sites locally with html-proofer?

**Comment by reesericci** [comment]
I already have all my code in place. Is there any way to add a CLI flag to disable the checking of URLs? Something like `--disable-url-checking`

**Comment by reesericci** [comment]
@Floppy I already have all my code in place. Is there any way to add a CLI flag to disable the checking of URLs? Something like `--disable-url-checking`

**Comment by Floppy** [comment]
I'm sure such a thing would be possible, but personally I'm undecided whether or not it would be a good design decision. @gjtorikian do you have any thoughts?

**Comment by reesericci** [comment]
Any updates?

**Comment by reesericci** [comment]
@Floppy anything?

**Comment by Floppy** [comment]
Not from me I'm afraid; need to get Garen's thoughts on it, I think.

**Comment by Floppy** [comment]
As a workaround, could you use the `http_status_ignore` option to ignore 404s? That would probably have the same effect as not checking in the first place...

**Comment by Floppy** [comment]
Ah! You can do this using `--checks_to_ignore LinkCheck` - that should do it.

**Comment by gjtorikian** [comment]
Yeah, `checks_to_ignore` is the way to go.

Keep in mind there are options for working with Jekyll, too: https://github.com/gjtorikian/html-proofer#using-with-jekyll
