### ISSUE TITLE
NameError: invalid attribute name `6'

### ISSUE THREAD

**Issue by miteshgala** [gjtorikian/html-proofer#572]
Hi Everyone,
I am getting the error below when running html proofer on my Jekyll site:

Running ["LinkCheck", "OpenGraphCheck", "ScriptCheck", "FaviconCheck", "ImageCheck"] on ["_site/"] on *.html... 
rake aborted!
NameError: invalid attribute name `6'

I have looked and looked but can not seem to find a way to get past this error.  I searched for the string "6 but it's so nondescript that there are thousands of results.

Any help is appreciated.

**Comment by Floppy** [comment]
I suspect that somewhere in your site you have an HTML attribute called `6`, which isn't allowed. Try searching for `6=`, that might do it? If not, I'd suggest taking a copy of your site, and removing files until you have a minimal set that causes the error. Then you can post that here if it's still not obvious.

**Comment by gjtorikian** [comment]
Attribute parsing has been completely removed in [the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669). I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️
