### ISSUE TITLE
A single doublequote in a div element should error

### ISSUE THREAD

**Issue by thisconnect** [gjtorikian/html-proofer#573]
A single lonely double quote in a `<div">` should error

https://validator.w3.org/nu/#textarea

- Warning: Element name div" cannot be represented as XML 1.0.
- Error: Element div" not allowed as child of element body in this context. (Suppressing further errors from this subtree.)

### minimal example

```html
<!doctype html>
<meta charset="utf-8">
<title>A double quote in a div element</title>
<div"></div>
```

**Comment by gjtorikian** [comment]
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) won't have HTML checking at all anymore. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️
