### ISSUE TITLE
An image as direct child of ul should error

### ISSUE THREAD

**Issue by thisconnect** [gjtorikian/html-proofer#574]
An image element as a direct child of an (un)ordered list should error.

https://validator.w3.org/nu/#textarea

- Error: Element img not allowed as child of element ul in this context. (Suppressing further errors from this subtree.)

### minimal example

```html
<!doctype html>
<meta charset="utf-8">
<title>An image as direct child of ul</title>
<ul><img></ul>
```

**Comment by gjtorikian** [comment]
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) won't have HTML checking at all anymore. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️
