### ISSUE TITLE
htmlproofer 3.16.0 | Error:  undefined method `match?' for /^javascript:/:Regexp

### ISSUE THREAD

**Issue by asarkar** [gjtorikian/html-proofer#582]
I have a blog built on [Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/) Jekyll gem hosted on Netlify. Until htmlproofer 3.15.3, it was working, but with 3.16.0, I get the following error while building:
```
htmlproofer 3.16.0 | Error:  undefined method `match?' for /^javascript:/:Regexp
```

Attached is a comparison of two builds using the two different versions of htmlproofer.
[htmlproofer.pdf](https://github.com/gjtorikian/html-proofer/files/5266709/htmlproofer.pdf)

**Comment by gjtorikian** [comment]
Huh, what version of Ruby are you running? Regexp _definitely_ has [a method called `match?`](https://ruby-doc.org/core-2.7.2/Regexp.html#method-i-match-3F) and that code has been there for a while.

**Comment by asarkar** [comment]
@gjtorikian Did you see the attached version comparison? Ruby 2.3.6, and that hadn't changed between builds that worked and that broke.

**Comment by gjtorikian** [comment]
Ah, that explains it. 

Ruby 2.3 was end of lifed on March 31, 2019. This project does not support unmaintained versions of Ruby. Your Ruby version doesn't support this `match?` method, which was added [about two months ago](https://github.com/gjtorikian/html-proofer/blame/0c57c0fd2ca698654280fda92ce5d09e6028f721/lib/html-proofer/element.rb#L108)

Either you will need to pin to an older version of this project, or, more recommended, upgrade your Ruby to get additional security + performance features!

**Comment by asarkar** [comment]
But how do you explain it working before?

**Comment by gjtorikian** [comment]
Because the code using the newer `match?` method was only added two months ago.
