### ISSUE TITLE
root-folder option when HTMLProofer to run on a directory

### ISSUE THREAD

**Issue by Baltazardoung** [gjtorikian/html-proofer#587]
When running HTMLProofer on a directory, it is not possible to use the `--root-folder` option. Which is a shame when you only want to validate a sub-folder.

In our use case, we build documentation from several GitLab projects included as git submodules and use a CI to validate them.

When a project contains a link to another project, and we run HTMProofer on the single project folder:

```shell
PROJECT_DIR=/documentation-from-my-project
htmlproofer "site${PROJECT_DIR}" --disable-external --empty-alt-ignore
```

We have an error like "`internally linking to /documentation-from-other-project/file, which does not exist`".

For performance reasons within merges requests, we would like to be able to validate the only files concerned by a project before validating all the documentations from all the projects.

At present, therefore, we are forced to implement something of the form

```shell
find "site${PROJECT_DIR}" -type f -name *.html -exec htmlproofer --root-folder site --disable-external --empty-alt-ignore {} >/dev/null 2>failed.log  \;
sed -i '/\/usr\/local\/bundle\//d' failed.log
cat failed.log
[ ! -s failed.log ]
```

We would like to be able to do simply:

```shell
htmlproofer --root-folder site --disable-external --empty-alt-ignore "site${PROJECT_DIR}"
```

If this is too complex, would it be, at a minimum, possible to run htmlproofer once, passing several files with something like:

```shell
find "site${PROJECT_DIR}" -type f -name *.html -exec htmlproofer --root-folder site --disable-external --empty-alt-ignore -- {} +
```

Thanks a lot,

**Comment by gjtorikian** [comment]
I'm looking at the code how `root_dir` is implemented and there isn't anything explicitly preventing it from being used with directories (despite what the help text says). So I may be misunderstanding the problem you are facing:

* You have a directory `site`
* `site` has a subdirectory called `documentation-from-my-project`
* From the `site` directory, you want to run htmlproofer across the files in `documentation-from-my-project`
* _but_ you want the relative files in `documentation-from-my-project` to have `site` prepended to them? that is, if an `href` says something like `/other-project/a.html`, that file does in fact exist at `site/other-project/a.html`

Is that right?

**Comment by Baltazardoung** [comment]
yes, it's that right

See the below screenshot to describe this issue (use `root-folder` option on `site/A/index.html` and only on `site/A/`) :

![html-proofer1](https://user-images.githubusercontent.com/13434663/99162127-600bd600-26fa-11eb-8123-20e2a96394a9.jpg)

**Comment by gjtorikian** [comment]
You know what, you were completely right! I found the bug and, hopefully, https://github.com/gjtorikian/html-proofer/pull/594 will resolve it soon.

**Comment by Baltazardoung** [comment]
Thanks you for this fix :-) .
