### ISSUE TITLE
3.17.1 broke something

### ISSUE THREAD

**Issue by iBobik** [gjtorikian/html-proofer#595]
When html proofer was updates from 3.17.0 to 3.17.1 today in my CI tests started failing on internal linking (<a>, <link>, …). External links are checked correctly.

Executing it like this:
```
htmlproofer \
        --empty-alt-ignore \
        --url-ignore "/www.facebook.com/" \
        --url-swap "https?\:\/\/(www\.example\.com):" \
        dist
```
in Docker image klakegg/html-proofer

**Comment by gjtorikian** [comment]
Can you show me the some of the source files? What the internal link looks like, or the directory structure?

3.17.1 _did_ change how internal links are checked (cf #587) but the test suite passed, so it's possible some other behavior was not being tested.

**Comment by tisba** [comment]
We're running into the same problem with 3.17.1.

We execute HTML proofer via Ruby like this:

```ruby
  HTMLProofer.check_directory("build/", {
    url_ignore: url_ignore,
    trace: true,
    typhoeus: {
      headers: {
        "Accept-Encoding" => "gzip, deflate",
        "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
      }
    },
    cache: {
      timeframe: "2w",
      storage_dir: ENV["HTML_PROOFER_CACHE_DIR"]
    }
  }).run
```

Same observable problem: Internal links are reported as broken, external ones appear okay.

**Comment by gjtorikian** [comment]
@tisba Same question: can you please `cat` or otherwise show what the HTML of a broken link on a page looks like, followed by the directory structure? I'm looking to set up a test file a la https://github.com/gjtorikian/html-proofer/blob/main/spec/html-proofer/fixtures/links/broken_internal_link.html

**Comment by gjtorikian** [comment]
Ok. I was able to recreate the problem. Working on a fix.

**Comment by gjtorikian** [comment]
https://github.com/gjtorikian/html-proofer/pull/597 should sort this; waiting for CI and will release 3.17.2 right after.

**Comment by gjtorikian** [comment]
If I could get external confirmation that this fixed this issue, please let me know!

PS If you or your company are finding this tool useful, please consider sponsoring it. ✌️

**Comment by tisba** [comment]
I can confirm, 3.17.2 has resolved the issue 👍
