### ISSUE TITLE
Links to Twitter profiles are treated as broken even though they aren't

### ISSUE THREAD

**Issue by Stex** [gjtorikian/html-proofer#619]
Probably related to https://github.com/gjtorikian/html-proofer/issues/283

When linking to a twitter profile, the link is detected as broken due to what seems to be a recent update to twitter's web client:

```
❯ curl https://twitter.com/jack
HTTP/2 400
cache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0

...

<body>
  <div class="errorContainer">
    <img width="46" height="38"
      srcset="https://abs.twimg.com/errors/logo46x38.png 1x, https://abs.twimg.com/errors/logo46x38@2x.png 2x"
      src="https://abs.twimg.com/errors/logo46x38.png" alt="Twitter" />
    <h1>This browser is no longer supported.</h1>
    <p>
      Please switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center.
    </p>
    <p class="errorButton"><a href="https://help.twitter.com/using-twitter/twitter-supported-browsers">Help Center</a>
    </p>
    <p class="errorFooter">
      <a href="https://twitter.com/tos">Terms of Service</a>
      <a href="https://twitter.com/privacy">Privacy Policy</a>
      <a href="https://support.twitter.com/articles/20170514">Cookie Policy</a>
      <a href="https://legal.twitter.com/imprint">Imprint</a>
      <a href="https://business.twitter.com/en/help/troubleshooting/how-twitter-ads-work.html">Ads info</a>
      © 2021 Twitter, Inc.
    </p>

  </div>
</body>
```

**Comment by gjtorikian** [comment]
Wow yeah, confirmed by a simple `curl` as well.

The only thing you can do is [change the user-agent](https://github.com/gjtorikian/html-proofer#user-agent) to something resembling a real browser, like `"Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0"`.

**Comment by moozer** [comment]
If am reading [the list of command line options](https://github.com/gjtorikian/html-proofer/blob/main/bin/htmlproofer) correctly, setting the header must be done e.g. by using a Rakefile like in the [travis CI example](https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis), correct?
