### ISSUE TITLE
Internal links cache seems to remove cached external links

### ISSUE THREAD

**Issue by riccardoporreca** [gjtorikian/html-proofer#620]
It looks like when detecting URL changes in the cache for internal links (introduced in #590), external links are removed from the cache according to the logic in 
https://github.com/gjtorikian/html-proofer/blob/3bb8d353e0420d79fc97cf06b40081495b871343/lib/html-proofer/cache.rb#L74

Minimal example html
```bash
echo '<!doctype html>
<html>
<head><title>Example</title></head>
<body>
<a href="https://github.com/gjtorikian/html-proofer">The amazing HTMLProofer</a>
</body>
</html>' > example.html
```

The cache is populated correctly is only external links are checked
- ```ruby
  require 'html-proofer'
  HTMLProofer.check_file("example.html", {
      :extension => ".html",
      :external_only => true,
      :links_only => true,
      :cache => { :timeframe => '1d', :storage_dir => '.htmlproofer-cache' },
      :log_level => {:debug => true},
  }).run
  ## Checking scriptcheck on example.html ...
  ## Checking linkcheck on example.html ...
  ## Checking imagecheck on example.html ...
  ## Adding 0 links to the cache...
  ## Removing 0 links from the cache...
  ## Checking 0 external links...
  ## ETHON: started MULTI
  ## ETHON: performed MULTI
  ## Ran on 1 file!
  ```
- ```bash
  cat .htmlproofer-cache/cache.log 
  {"https://github.com/gjtorikian/html-proofer":{"time":"2021-02-06 17:48:34 +0100","filenames":["example.html"],"status":200,"message":""}}

If however to the full link check including internal links (which are not even there), the external link is removed
- ```ruby
  require 'html-proofer'
  HTMLProofer.check_file("example.html", {
      :extension => ".html",
      :links_only => true,
      :cache => { :timeframe => '1d', :storage_dir => '.htmlproofer-cache' },
      :log_level => {:debug => true},
  }).run
  ## Checking scriptcheck on example.html ...
  ## Checking linkcheck on example.html ...
  ## Checking imagecheck on example.html ...
  ## Adding 0 links to the cache...
  ## Removing 0 links from the cache...
  ## Checking 0 external links...
  ## ETHON: started MULTI
  ## ETHON: performed MULTI
  ## Adding 0 links to the cache...
  ## Removing https://github.com/gjtorikian/html-proofer from cache check
  ## Removing 1 link from the cache...
  ## Found 0 internal links in the cache...
  ## Ran on 1 file!
  ```
- ```bash
  cat .htmlproofer-cache/cache.log
  {}
  ```

**Comment by riccardoporreca** [comment]
I guess 
https://github.com/gjtorikian/html-proofer/blob/3bb8d353e0420d79fc97cf06b40081495b871343/lib/html-proofer/cache.rb#L74
would need to know which are the links (internal vs. external) to in scope of detecting changes.

Or is it perhaps easier to go for independent caches, one for internal, one for external? They could still be written to a single `cache.log` file like:
```json
{
  "external": {"https://github.com/gjtorikian/html-proofer":{"time":"2021-02-06 17:48:34 +0100","filenames":["example.html"],"status":200,"message":""},
  "internal": {"[...]"}
}

**Comment by gjtorikian** [comment]
Yeah, I'm very unhappy with how the caching is set up. At the least I would want to introduce versioning, to account for "schema" changes like this. 

Thank you for the minimum example. I'll cobble a fix together while looking towards the future for a longer term fix.

**Comment by riccardoporreca** [comment]
Cool, thanks @gjtorikian for the quick fix! Agree on the need for some care and fresh thoughts on the caching setup, including versioning.

Keep up with the great work on HTMLProofer!
