### ISSUE TITLE
By default Middleware ignores all URLs

### ISSUE THREAD

**Issue by ExMember** [gjtorikian/html-proofer#621]
By default `HTMLProofer::Middleware.options[:url_ignore]` returns an array with only one regex: `/.*/`.

This regex matches all non-empty URLs. As a result, all URLs are ignored and options like `enforce_https` and `check_img_http` have no effect.

The comment indicates that the intent is to skip local files. A better option would probably be to use a regex that would match URLs that start with a backslash and indicate a relative link, for example. `/^\//`.

https://github.com/gjtorikian/html-proofer/blob/main/lib/html-proofer/middleware.rb#L25

**Comment by gjtorikian** [comment]
Woof, good catch. Thanks.
