### ISSUE TITLE
Add caching note for GitHub Actions

### ISSUE THREAD

**Issue by fulldecent** [gjtorikian/html-proofer#639]
Currently we have a caching note fr Travis.

Let's add one for GitHub Actions above that.

**Comment by fulldecent** [comment]
Some more notes and discussion:

https://github.com/actions/cache/issues/574

**Comment by fulldecent** [comment]
Fixed at d13a5b6ef440cc1ee6cd03593e0e6b8b68e68fe9

**Comment by gjtorikian** [comment]
Thank you, but please do a PR next time.

**Comment by fulldecent** [comment]
Got it, my bad.
