### ISSUE TITLE
Replace --external_only with --external-only in docs and usage

### ISSUE THREAD

**Issue by MichaelCurrin** [gjtorikian/html-proofer#641]
I'm using the latest version of the gem.

All the flags use a dash to join words, except for external only, which feels strange.

```
...
            --extension <ext>  The extension of your HTML files including the dot. (default: `.html`)
            --external_only  Only checks problems with external references
            --file-ignore file1,[file2,...]  A comma-separated list of Strings or RegExps containing file paths that are
...
```

Both flags are accepted  already -`--external-only` and `--external_only`. So then this is only a cosmetic change and not a functional change.

This could be adjusted for consistency here and in the docs.

https://github.com/gjtorikian/html-proofer/blob/249d506670281905ee1a1e95e7a922bfe9ab1dbc/bin/htmlproofer#L36

Happy to help with a PR if needed.

Thanks

**Comment by gjtorikian** [comment]
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) only has `disable-external` now. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️
