### ISSUE TITLE
Passing hydra options from CLI is broken

### ISSUE THREAD

**Issue by bmesuere** [gjtorikian/html-proofer#644]
I can't seem to set the max_concurrency of hydra using the cli. I'm using `--hydra_config '{"max_concurrency": 5}'` which throws an error: `The option: max_concurrency is invalid`.

After printing the internal options hash, it seems that merging the values failed: `{:max_concurrency=>50, "max_concurrency"=>5}`.

The cause of this seems to be that `symbolize_names` is set to false on line 92 (and 91) of the htmlproofer bin file. If I set that value to true, everything works as expected.

Am I using a wrong syntax for setting the max_concurrency or is this a bug?

**Comment by gjtorikian** [comment]
Sorry about that. A patch release fixing this should be out soon.
