### ISSUE TITLE
links without html suffix claimed to be broken

### ISSUE THREAD

**Issue by matkoniecz** [gjtorikian/html-proofer#654]
`<a href="page_linked_without_using_html_prefix">page_linked_without_using_html_prefix</a>` where `page_linked_without_using_html_prefix.html` exists is claimed to be broken

To reproduce

```
git clone https://github.com/matkoniecz/dead_links_testing_site
cd dead_links_testing_site/
htmlproofer index.html 
```

```
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on index.html on *.html... 


Checking 2 external links...
Ran on 1 file!


- index.html
  *  image test png with space.png does not have an alt attribute (line 0)
  *  image test_png_with_zażółć_gęślą_jaźń.png does not have an alt attribute (line 0)
  *  image test_png_without_space.png does not have an alt attribute (line 0)
  *  internally linking to page_linked_without_using_html_prefix, which does not exist (line 0)
     <a href="page_linked_without_using_html_prefix">page_linked_without_using_html_prefix</a>

HTML-Proofer found 4 failures!
```

Note that page_linked_without_using_html_prefix link actually works when deployed - for example at https://matkoniecz.github.io/dead_links_testing_site/

Is it supposed to be not working and github pages is using some weird magic? Note, I deployed it also locally ( for example using https://github.com/matkoniecz/website-checklist/blob/master/validators.md#checking-local-html-files method)  and it also worked.

**Comment by gjtorikian** [comment]
See if it works with the `--assume-extension` CLI option: https://github.com/gjtorikian/html-proofer#using-with-jekyll

**Comment by matkoniecz** [comment]
Yes, it worked! Thanks, I missed it!
