### ISSUE TITLE
External links cache not updated for failures (next-gen)

### ISSUE THREAD

**Issue by riccardoporreca** [gjtorikian/html-proofer#683]
Using the GitHub "next-gen" version of html-proofer, if a failure is detected and cached, it is not updated if the link is OK upon a re-run, which implies the link will be always checked

Example:
```sh
echo '<!doctype html>
<html>
<head><title>Example</title></head>`
<body>
<a href="https://github.com/gjtorikian/html-proofer">The amazing HTMLProofer</a>
</body>
</html>' > example.html
```
Create a cache with a failure
```sh
echo \
'{"version":2,"internal":{},"external":{"https://github.com/gjtorikian/html-proofer":{"time":"2022-01-02 20:41:00 +0100","found":false,"status_code":0,"message":"error","metadata":[{"filename":"example.html","line":5}]}}}' \
> example_cache/cache.json
```
Running several times, the link is always re-checked successfully (`Received a 200 for https://github.com/gjtorikian/html-proofer`) because the cache file is not updated
```sh
htmlproofer --cache '{"timeframe": "1d", "storage_dir": "example_cache"}' --log-level debug example.html
```

**Comment by riccardoporreca** [comment]
I guess the `if @cache_log[:external][url].nil?` is preventing the update 

https://github.com/gjtorikian/html-proofer/blob/3bb780267f650ec5a968642808b5dd566927fb0c/lib/html_proofer/cache.rb#L77

**Comment by gjtorikian** [comment]
Thank you so so much for finding this. ❤️
