### ISSUE TITLE
External cache key trainling / issues (4.0.0.rc1)

### ISSUE THREAD

**Issue by riccardoporreca** [gjtorikian/html-proofer#689]
Cache keys for external links seem to always include or exclude trailing `/`

```sh
echo '
<!doctype html>
<html>
<head><title>Example</title></head>
<body>
<a href="https://github.com">Domain only, no trailing "/"</a>
<a href="https://rubygems.org/">Domain only, trailing "/"</a>
<a href="https://github.com/gjtorikian">No tailing "/"</a>
<a href="https://github.com/riccardoporreca/">Trailing "/"</a>
</body>
</html>
' > example.html
```

```sh
rm -rf tmp/.htmlproofer
htmlproofer example.html --cache '{"timeframe": "1d"}' --log-level debug
# [...]
# Found 0 external links in the cache
# Adding https://github.com/ to external cache
# Adding https://rubygems.org/ to external cache
# Adding https://github.com/gjtorikian to external cache
# Adding https://github.com/riccardoporreca to external cache
# Adding 4 new external links to the cache
# Removing 0 outdated external links from the cache
# Checking 4 external links
# ETHON: started MULTI
# Received a 200 for https://rubygems.org/
# Received a 200 for https://github.com
# Received a 200 for https://github.com/gjtorikian
# Received a 200 for https://github.com/riccardoporreca/
# ETHON: performed MULTI
# [...]
cat tmp/.htmlproofer/cache.json | ruby -e \
  "require 'json'; puts JSON.pretty_generate(JSON.parse(ARGF.read)['external'].keys)"
# [
#   "https://rubygems.org/",
#   "https://github.com/",
#   "https://github.com/gjtorikian",
#   "https://github.com/riccardoporreca"
# ]
```
However, the trailing `/` is not treated consistently when 'pruning' the cache in a second run, although the links are not re-checked (they seem to be correctly found in the cache, regardless of the presence of `/`)
```sh
htmlproofer example.html --cache '{"timeframe": "1d"}' --log-level debug
# [...]
# Found 4 external links in the cache
# Adding 0 new external links to the cache
# Removing https://github.com/ from external cache
# Removing https://github.com/riccardoporreca from external cache
# Removing 2 outdated external links from the cache
# Checking 0 external links
# [...]
cat tmp/.htmlproofer/cache.json | ruby -e \
  "require 'json'; puts JSON.pretty_generate(JSON.parse(ARGF.read)['external'].keys)"
# [
#   "https://rubygems.org/",
#   "https://github.com/gjtorikian"
# ]
```
A third run would then re-check them since they disappeared from the cache

**Comment by riccardoporreca** [comment]
Maybe I see what is happening: the detected URLs are cleaned consistently when determining additions and adding to the cache:
https://github.com/gjtorikian/html-proofer/blob/c9634c65fcb2acb5329f91596fcf31023baa3bd3/lib/html_proofer/cache.rb#L95-L98
https://github.com/gjtorikian/html-proofer/blob/c9634c65fcb2acb5329f91596fcf31023baa3bd3/lib/html_proofer/cache.rb#L68-L74
but are not cleaned when determining deletions, with the code cleaning the cache key instead of `urls_detected`:
https://github.com/gjtorikian/html-proofer/blob/c9634c65fcb2acb5329f91596fcf31023baa3bd3/lib/html_proofer/cache.rb#L123-L129

**Comment by gjtorikian** [comment]
Guh, thanks for catching this.

In html-proofer 3.x, Typheous, which is responsible for the link checking, did [a lot of wacky mangling to the URL](https://github.com/gjtorikian/html-proofer/blob/1bab3a1a18e95a10378371ddf000df9bea01740e/lib/html-proofer/cache.rb#L146-L153), which made storing the "true" URL in the cache very difficult. When I revisited this section, the tests suite passed as before (I actually haven't made very many changes between 3 and 4 to the tests themselves), so I just assumed the problem went away. I'll add a test for this section and see what's up.
