### ISSUE TITLE
Problems with internal link cache re-checking logic (4.0.0.rc3)

### ISSUE THREAD

**Issue by riccardoporreca** [gjtorikian/html-proofer#695]
Cached internal broken links are not re-checked

```bash
rm -rf example_site
mkdir -p example_site
echo '
<!doctype html>
<html>
<head><title>Example</title></head>
<body>
<a href="/missing.html">Missing internal link</a>
</body>
</html>
' > example_site/index.html
```

Running first with empty cache
```bash
rm -rf tmp/.htmlproofer
bundle exec htmlproofer example_site --log-level debug --cache '{"timeframe": "1d"}'
# [...]
# Adding /missing.html to internal cache
# Adding 1 new internal link to the cache
# Removing 0 outdated internal links from the cache
# Checking 1 internal link
# Ran on 1 file!
#
#
# For the Links > Internal check, the following failures were found:
#
# * In example_site/index.html (line 5):
#
#   internally linking to /missing.html, which does not exist
#
#
# HTML-Proofer found 1 failure!
```

Run again: the broken link is not re-checked

```bash
rm -rf tmp/.htmlproofer
bundle exec htmlproofer example_site --log-level debug --cache '{"timeframe": "1d"}'
# Found 1 internal link in the cache
# Adding 0 new internal links to the cache
# Removing 0 outdated internal links from the cache
# Checking 0 internal links
# Ran on 1 file!
#
#
# HTML-Proofer finished successfully.
```

**Comment by riccardoporreca** [comment]
I have been investigating this, which is primarily caused by overriding the metadata, which loses the `found` information (confirmed by `found` being `null` in cache.json after the second round above)

https://github.com/gjtorikian/html-proofer/blob/8107f0cc336d27157f68223ba0467a57d2ce1601/lib/html_proofer/cache.rb#L97-L111

I am trying to propose a fix following my investigations

**Comment by riccardoporreca** [comment]
See PR #696 

Note that there is still one main flaw even after the proposed fix, which re-checks an internal url if not all cached checks were OK:

https://github.com/gjtorikian/html-proofer/blob/287bd2d52c69b23ce579eeb8e13b1a12a1103f46/lib/html_proofer/cache.rb#L104

This is not enough, since a relative URL that was OK for all the files previously checked and cached does not provide any guarantee against e.g. the same URL being OK for a new file (for instance, this could happen if a file is moved and the relative urls in it would not be updated). This is very related to https://github.com/gjtorikian/html-proofer/issues/671#issuecomment-1003456160

**Comment by riccardoporreca** [comment]
I have created a new branch off the one of PR #696, where I could add a test for the problem mentioned in https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008201940

**Comment by riccardoporreca** [comment]
@gjtorikian, I took a bit of liberty (and fun) to investigate a possible rethinking of internal links cache keys, by using a combined key including the relevant "context" used for checking them. This was also largely inspired by your considerations in https://github.com/gjtorikian/html-proofer/issues/671#issuecomment-1003456160 and https://github.com/gjtorikian/html-proofer/issues/671#issuecomment-1003731357 

You can find this drafted in a branch: https://github.com/riccardoporreca/html-proofer/compare/feature/695-fix-internal-cache-metadata-check...riccardoporreca:feature/695-investigate-internal-cache-key-metadata

The approach seems to work, although it has downsides in the JSON cache, where keys become less readable.
The failing tests are only for the cache, since the test expectations and data are not aligned. I only aligned the newly-introduced test revealing the issue.

**Comment by gjtorikian** [comment]
> The approach seems to work, although it has downsides in the JSON cache, where keys become less readable.
> The failing tests are only for the cache, since the test expectations and data are not aligned. I only aligned the newly-introduced test revealing the issue.

Gotcha. Thanks for the explanation. I'm far less concerned about a human-readable version of the cache.

**Comment by gjtorikian** [comment]
I need to look at this one a bit more carefully, because I bungled up your branch with a force push. There are a couple of tests still failing but in general I think what you've done makes sense.

**Comment by riccardoporreca** [comment]
> There are a couple of tests still failing but in general I think what you've done makes sense.

Indeed, I did not want to fix tests before knowing if the approach would be something workable at your end. I think it is important to align all test cache files to the new structure: tests checking if a link is added because it was failed in the cache or the cache expired might pass for the wrong reason of the key not being in the cache

Let me know if I can help with this...

**Comment by gjtorikian** [comment]
I just remembered I dropped this—will try to make time for it this weekend.
