### ISSUE TITLE
Issue with internal links re-checking logic / cache keys

### ISSUE THREAD

**Issue by riccardoporreca** [gjtorikian/html-proofer#702]
_Dedicated issue to follow up on what originally pointed out in https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008201940_ and re-discussed in https://github.com/gjtorikian/html-proofer/pull/699#issuecomment-1050361464_

Even with PR #699 (cleaning up an original PR #695), there is still one main flaw in the logic for re-checking cached internal links, given the code re-checks an internal url if not all cached checks were OK:

https://github.com/gjtorikian/html-proofer/blob/85c7aa07cf9d9a0c5fd46c15daeec043856c0ccf/lib/html_proofer/cache.rb#L101-L106

This is not enough, since a relative URL that was OK for all the files previously checked and cached does not provide any guarantee against e.g. the same URL being OK for a new file (for instance, this could happen if a file is moved and the relative urls in it would not be updated). This is also related to https://github.com/gjtorikian/html-proofer/issues/671#issuecomment-1003456160

**Comment by gjtorikian** [comment]
I'm not able to reproduce this, which might mean my fixture setup is wrong. Here is what I have:

* A folder with two files: a.html, b.html
* a.html links to b.html
* The cache sees this link as valid
* Next, I add a new folder with a single file in it: folder/c.html
* c.html points to b.html
* This link is correctly stored in the cache as "not found"

What am I missing?

**Comment by riccardoporreca** [comment]
Apologies for the long silence @gjtorikian, I wanted to have a fresh look but never got to it and eventually forgot!

Let me try to squeeze it this weekend

**Comment by gjtorikian** [comment]
No worries! I also forget. 😅 

Mostly I am eager to release the next major version of html-proofer, but not if it means the cache log needs to change to support this case. (I already changed the format, I don't want to have to change it again so soon after release!)

**Comment by riccardoporreca** [comment]
@gjtorikian, I am actually looking forward to a new release, and I fully agree on the point of fixing this (potential) issue as part f the major caching refactoring with the upcoming 4.x

In any case THIS is the weekend I will have time to dig things out, will be working mostly off line while travelling but we should have something by weekend-end.

**Comment by riccardoporreca** [comment]
@gjtorikian, I can confirm the issue, reproduced as follows

```bash
rm -rf example_site
mkdir -p example_site
touch example_site/existing.html
echo '
<!doctype html>
<html>
<head><title>Example</title></head>
<body>
<a href="existing.html">Missing internal link</a>
</body>
</html>
' > example_site/index.html
```

Running first with empty cache

```bash
rm -rf tmp/.htmlproofer
bundle exec htmlproofer example_site --log-level debug --cache '{"timeframe": "1d"}'
# [...]
# Found 0 internal links in the cache
# Adding existing.html to internal cache
# Adding 1 new internal link to the cache
# Removing 0 outdated internal links from the cache
# Checking 1 internal link
# Ran on 2 files!
# HTML-Proofer finished successfully.
```

Add a new file with broken relative link

```bash
mkdir -p example_site/broken
cp example_site/index.html example_site/broken
```
Run again: the broken link is not re-checked, because the cache was hit

```bash
bundle exec htmlproofer example_site --log-level debug --cache '{"timeframe": "1d"}'
# [...]
# Found 1 internal link in the cache
# Adding 0 new internal links to the cache
# Removing 0 outdated internal links from the cache
# Checking 0 internal links
# Ran on 3 files!
# HTML-Proofer finished successfully.
```

The same would apply and be even worse if one would just move the file `mv example_site/index.html example_site/broken`

Also note that the cache file is not updated with the new location:

```bash
cat tmp/.htmlproofer/cache.json | ruby -e   "require 'json'; puts JSON.pretty_generate(JSON.parse(ARGF.read)['internal'])"
{
  "existing.html": {
    "time": "2022-06-04 10:45:18 +0200",
    "metadata": [
      {
        "source": "example_site",
        "current_path": "example_site/index.html",
        "line": 6,
        "base_url": "",
        "found": true
      }
    ]
  }
}
```

**Comment by riccardoporreca** [comment]
I can revamp the change I originally proposed as discussed in https://github.com/gjtorikian/html-proofer/pull/699#issuecomment-1050361464

**Comment by riccardoporreca** [comment]
@gjtorikian, the [CI GitHub Actions workflow](https://github.com/gjtorikian/html-proofer/actions/workflows/ci.yml) seem to be vastly broken since 2565ad4, which was a pretty massive commit... I guess we want to have this fixed before assessing any other changes.

**Comment by gjtorikian** [comment]
Okay, I can finally reproduce this 😌 I see exactly what's happening. I hope to get a fix out later today or tomorow.

**Comment by riccardoporreca** [comment]
Thanks, let me know if I can still help to revamp the changes I initially proposed with the "composite" cache key including context for the internal links, along the lines of what I tried at some point to summarize in https://github.com/gjtorikian/html-proofer/pull/699#issuecomment-1050361464. Otherwise I will be happy to help with reviewing the changes
