### ISSUE TITLE
Add JUnit-compatible `Reporter`

### ISSUE THREAD

**Issue by jamietanna** [gjtorikian/html-proofer#703]
To allow HTMLProofer to be able to hook in more easily + visualise errors in tools like GitHub/GitLab/Jenkins, it'd be great to have a JUnit report produced when checking i.e. a directory.

I'd be happy to help out with contributing this, or letting someone else pick it up if they're interested.

**Comment by gjtorikian** [comment]
This won't be part of core, sorry. The purpose of extracting out the reporter in html-proofer 4.0 is to enable third-parties to write their own reporting.

If there's information missing that isn't currently exposed that JUnit needs, then I would certainly include that. But experience has shown that maintaining formats for other consumers puts way too much of a burden on little ol' me.
