### ISSUE TITLE
Allow separate internal/external cache timeframe

### ISSUE THREAD

**Issue by riccardoporreca** [gjtorikian/html-proofer#708]
Internal links are generally a separate conceptual beast compared to external ones, meaning that external links might turn broken (sometimes just temporarily) due to upstream issues whereas internal links might become broken due to actual mistakes with things under our control, e.g. removing pages or restructuring the website.
For this reason, one might want to cache external links with a longer time-frame (smoothing temporary issues) and use a shorter time-frame for internal ones (to capture mistakes as they appear), or even disable the internal cache altogether (especially for small websites, internal cache does not really add much).

What about allowing a configuration like this?

```
{ cache: { timeframe: {internal: '1d', external:'30d' } }
```

A single "global" timeframe (as currently)

```
{ cache: { timeframe: '30d' } }
```

could still be supported and propagated internally to the two cache types.

This would be already very useful, a natural extension could be enabling only one cache type, e.g. enabling only external cache with stg like:

```
{ cache: { timeframe: {external: '30d' } }
```

**Comment by riccardoporreca** [comment]
@gjtorikian, this is something I was thinking about a few months ago while thinking at the new version 2 cache, maybe not for the first 4.0.0 release but a nice extension for the near future

**Comment by gjtorikian** [comment]
I like it! Since this is a config change it would definitely be a breaking release, so I can get it in for 4.0.

**Comment by riccardoporreca** [comment]
Great, thanks @gjtorikian 🎉 !
