### ISSUE TITLE
Config section of README seems to be out of sync with actual CLI options

### ISSUE THREAD

**Issue by hoosierbenzo** [gjtorikian/html-proofer#713]
The [Configuration](https://github.com/gjtorikian/html-proofer#configuration) section of the README.md does not align to the actual CLI options.

For example, `ignore_files` does not work in the CLI. Instead you must use `file-ignore`.

Perhaps I'm misunderstanding the purpose of this README section, but it was confusing to me when adopting this gem.

I'd be happy to submit a PR to update the README, i.e. replace the table in Configuration with the CLI options from the latest version.

Can anyone confirm if that would be correct course of action?

**Comment by gjtorikian** [comment]
The current `main` branch is for the unreleased next major version, 4.0. Sorry, I should've specified that.

The README/config for the latest published release is at https://github.com/gjtorikian/html-proofer/tree/b048be82e4867cb5442966e7f68efeb0a2639b17

**Comment by gjtorikian** [comment]
(https://github.com/gjtorikian/html-proofer/pull/674 also has the proposed changelog)
