### ISSUE TITLE
From time to time I get response code 0 with Stream error in the HTTP/2 framing layer

### ISSUE THREAD

**Issue by cadamini** [gjtorikian/html-proofer#716]
Hey, I am using html-proofer with Jekyll and want to test external links on a site hosted on AWS. 

I am running the script on about 900 files. Sometimes, the tests run OK and the script returns "HTML-Proofer finished successfully." but sometimes, I get the following error which I cannot understand: 

> External link https://mysite.com/... failed: **response code 0**

The error message from the server is: `Stream error in the HTTP/2 framing layer`.

```
HTMLProofer
    .check_directory(
      './_site', disable_external: false, parallel: { in_processes: 4 }
    ).run
```

I also tried to add `enforce_https: false, log_level: :debug` to my script. 

Any hints?

**Comment by gjtorikian** [comment]
> that most links are interpreted as external links


Interesting. Could you share your site with me? Maybe I can take a look.

**Comment by cadamini** [comment]
The repo is private but the HTML is public, I assume that it is related to the Jekyll link tag usage. I can try to provide a test repo but will test your auggestions firat.

**Comment by cadamini** [comment]
Ok, I found the reason for the external links. The page is using https://github.com/jekyll/jekyll-redirect-from and all old links redirected to the current name of a page are listed as an external link.

**Comment by cadamini** [comment]
Could a delayed redirect be the problem here? All affected pages follow the pattern above - this might be related to my local server and might go away when the base URL is the server on which I host the stuff.

**Comment by cadamini** [comment]
I wonder if this is related to the user agent as discussed [in this project](https://github.com/wpscanteam/wpscan/issues/1537). 

My test results: Both, the additional typhoeus and heydra options and reducing the numbers for `parallel: { in_processes: 2 }` and `hydra: { max_concurrency: 10 }` seemed to have helped here. The errors appear much less frequent.

```
HTMLProofer
    .check_directory(
      './_site', disable_external: false, parallel: { in_processes: 2 }, typhoeus:
        { followlocation: true, connecttimeout: 10, timeout: 30 }, hydra: { max_concurrency: 10 }
    ).run
```

I have now constantly one valid error 0 for a real external page. I still cannot explain why but that's OK. Can you? 

I hope this will help somebody else in the future.

**Comment by gjtorikian** [comment]
Could you remove `parallel: { in_processes: 2 }` and try again? As well, set  `hydra: { max_concurrency` to, let's say, 20?

I think I inadvertently misled you earlier: `parallel` is only used when reading files off of disk; but `max_concurrency` is used when making external requests to check links.

My theory is `in_processes: 2` actually isn't fixing anything, so if you remove it with the current config everything should still work.

Similarly, I think that if `max_concurrency` were raised, the problems would return. Right now [its default is 50](https://github.com/gjtorikian/html-proofer/blob/2565ad4e1e83439b0bacb5c1df32a9006c84ba72/lib/html_proofer/configuration.rb#L39), so perhaps I should lower it to something more reasonable.
