### ISSUE TITLE
Linking to directories without a trailing slash in 4.0.0

### ISSUE THREAD

**Issue by brockfanning** [gjtorikian/html-proofer#718]
Hello, it seems that version 4.0.0 is more strict about linking to directories without a trailing slash than 3.19.4 was. Whereas in 3.19.4 it allowed it when there was an "index.html" file in the directory, 4.0.0 is throwing an error. For example, see [this failing test run upgrading 4.0.0](https://github.com/open-sdg/open-sdg-site-starter/runs/7291763235?check_suite_focus=true#step:7:71821) and then a [passing test run after reverting to 3.19.4](https://github.com/open-sdg/open-sdg-site-starter/runs/7291824738?check_suite_focus=true#step:7:46).

I'm not sure if this is a bug - maybe it was an intentional change? But I didn't see anything obvious about it in the changelog, so I thought I would post this here in case it's helpful. Feel free to close this if that change was intentional.

**Comment by gjtorikian** [comment]
Hey! Thanks so much for this issue report. This was definitely _not_ intentional. And, unfortunately, the test which should have tested this feature was also broken in v3.x. 😅


4.0.1 corrects this problem.
