### ISSUE TITLE
CHANGELOG.md says Unreleased but 4.0 is out

### ISSUE THREAD

**Issue by tbm** [gjtorikian/html-proofer#721]
The top of CHANGELOG.md says "Unreleased" but 4.x appears to be out.

**Comment by gjtorikian** [comment]
That's just a placeholder which is generated by [the changelog generation script](https://github.com/gjtorikian/html-proofer/blob/main/script/changelog). As far as I know it can't be changed as it comes from [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator).
