### ISSUE TITLE
srcset width/pixel density descriptors cause missing image error

### ISSUE THREAD

**Issue by fallax** [gjtorikian/html-proofer#724]
The [spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source#attr-srcset) for the srcset attribute says:

> A list of one or more strings, separated by commas, indicating a set of possible images represented by the source for the browser to use. Each string is composed of:
> 
> -    One URL specifying an image.
> -    A width descriptor, which consists of a string containing a positive integer directly followed by "w", such as 300w. The default value, if missing, is the infinity.
> -    A pixel density descriptor, that is a positive floating number directly followed by "x". The default value, if missing, is 1x.
> 
> Each string in the list must have at least a width descriptor or a pixel density descriptor to be valid.

However when a width descriptor or pixel density descriptor is used, for example:

```
<html>
<body>
    <img
        srcset="test.webp 1.5x"
        alt="test"
        width="100"
        height="150"
        />
</body>
</html>
```

html-proofer says ```internal image test.webp 1.5x does not exist``` even if test.webp is present.

Additionally, most tests for srcsets (e.g. /spec/html-proofer/fixtures/images/multiple_srcset_success.html) do not include either a width descriptor or pixel density descriptor, which the spec for the attribute says it must have. I'm guessing this is why this issue has crept in?

**Comment by gjtorikian** [comment]
Whoops, thanks for the excellent report and repro case. 4.1 should fix this and adds some more checks for more legitimate `srcset` attributes.

**Comment by fallax** [comment]
Thanks for the quick fix - this has allowed us to upgrade :)
