### ISSUE TITLE
Warn/Failure if unknown configuration option is provided

### ISSUE THREAD

**Issue by mmoayyed** [gjtorikian/html-proofer#730]
Thank you for this great tool.

A number of options seem to have changed in the most recent release, 4.1.0, such as `ignore_urls`. Those that are migrating from older versions to the new are not warned about the change in names/options, and so builds begin to fail without details. If options are changed or renamed, the tool should either issue warnings, or should stop/fail the process with a clear error message.

**Comment by gjtorikian** [comment]
If you would like to [sponsor me](https://github.com/sponsors/gjtorikian) I can certainly add this feature.

Until then, there is [an UPGRADING guide](https://github.com/gjtorikian/html-proofer/blob/main/UPGRADING.md).
