### ISSUE TITLE
`erstiebegrüßung.html` causing problems on macOS

### ISSUE THREAD

**Issue by asbjornu** [gjtorikian/html-proofer#771]
As mentioned in https://github.com/gjtorikian/html-proofer/pull/767#pullrequestreview-1121660724, the file `spec/html-proofer/fixtures/links/erstiebegrüßung.html` is causing major issues for me on macOS 11.7. I've attempted to do [everything mentioned in this post](https://www.git-tower.com/help/guides/faq-and-tips/faq/unicode-filenames/mac), but the file is still deleted and re-added at random and makes other Git operations such as rebase, impossible.

Perhaps a viable solution to the problem is to remove the file from Git and instead generate the file in the specs? If you agree with this, I'm happy to provide a PR @gjtorikian.

**Comment by gjtorikian** [comment]
Sure, a PR would help, thanks.

**Comment by asbjornu** [comment]
Cool, #772 submitted.
