### ISSUE TITLE
Document tree depth limit exceeded 

### ISSUE THREAD

**Issue by Digital-Grinnell** [gjtorikian/html-proofer#778]
I upgraded the `htmlproofer` install today on my M1 Mac (arm64) running Monterey (macOS 12.6 (21G115)) and I can run the command line app one time, but all subsequent runs produce output like this: 

```
╭─mcfatem@MAC02FK0XXQ05Q ~/GitHub/rootstalk ‹develop●›
╰─$ htmlproofer ./public > rootstalk-htmlproofer.out
/Users/mcfatem/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/html5/document.rb:82:in `parse': Document tree depth limit exceeded (ArgumentError)
	from /Users/mcfatem/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/html5/document.rb:82:in `do_parse'
```

Only once I restart the Mac can I run it successfully again.  So I'm guessing this isn't really a "tree depth limit" issue?  Maybe a memory leak somewhere?

**Comment by gjtorikian** [comment]
This appears to be an issue with the `nokogiri` gem unable to parse your HTML, and so I suggest you open an issue with them: https://github.com/sparklemotion/nokogiri

**Comment by Digital-Grinnell** [comment]
I agree, thanks for the suggestion.  I'm able to process the same HTML using `klakegg/html-proofer:3.19.2` and Docker, so I suspect the issue is with my M1 Mac or a resource limit on that machine.  In any event, since I found a viable way to reliably run `htmplproofer` I'm going forward again.  It's a great tool!  Thanks!
