### ISSUE TITLE
Changelog of a different project

### ISSUE THREAD

**Issue by MikkCZ** [gjtorikian/html-proofer#782]
https://github.com/gjtorikian/html-proofer/commit/966820f8f3b75ed4cd851c62e1d2e59bbb2ae2c2 has overwritten changelog with information from a different repository (https://github.com/gjtorikian/tailwind_merge). It's a regression from https://github.com/gjtorikian/html-proofer/commit/7cf2aa30db124aba93047fdd9cd53efd4ed904eb.

**Comment by gjtorikian** [comment]
Whoops! A copy pasta error I’ll fix ASAP.
