### ISSUE TITLE
`data-proofer-ignore` does not silence "Input contains noncharacter"

### ISSUE THREAD

**Issue by l0b0** [gjtorikian/html-proofer#785]
Example:

```
- ./public/test/verify-html/consistent-fonts-in-firefox.html
  *  135:33: ERROR: Input contains noncharacter U+10FFFE.
— “<span data-proofer-ignore="">􏿾</span>” — instead of an icon.</li>
                                ^ (line 135)
```

Is this intended? I've removed the offending section as a workaround.

Running htmlproofer 3.18.8.

Thank you for this project!

**Comment by gjtorikian** [comment]
I'm not sure I can do much about this, as html-proofer expects the incoming file(s) to be UTF-8 encoded. This character is marked as [`Supplementary Private Use Area-B`](https://unicode-explorer.com/b/10FF80)—a "non-character"—and so its representation is undefined.

Unfortunately html-proofer is not designed to sanitize/clean up HTML text; that should be done prior to using this tool. To fix this, I imagine html-proofer would have to scrub these sorts of "unexpected code paths," which is a bit outside the scope of the project.

Feel free to reopen this issue if you disagree with a compelling usecase for why this should be preserved.
