### ISSUE TITLE
Error for http only sites

### ISSUE THREAD

**Issue by RichardLitt** [gjtorikian/html-proofer#799]
I get the following error:

```
* At ./_site/projects/access-land/index.html:70:

  http://accessland.org is not an HTTPS link
```

For that site, there is no HTTPS enabled. Should this be flagged?

**Comment by riccardoporreca** [comment]
@RichardLitt, the [`enforce_https` option](https://github.com/gjtorikian/html-proofer#configuration) can be used to control this.

For the command line (`htmlproofer --help`):

```
        --[no-]enforce-https         Fails a link if it's not marked as `https` (default: `true`).
```

**Comment by RichardLitt** [comment]
I think that's different than failing of the link doesn't have an HTTPS equivalent. Right now, the flag itself is an error, because the link is correct.

**Comment by riccardoporreca** [comment]
@RichardLitt let me try to clarify the behavior.

The way html-proofer behaves w.r.t `enforce_https` is just detecting a failure for any http:// link, regardless of whether it or its https:// counterpart exists (is accessible).
If you do not want html-proofer to detect such failures, and instead just do the check of whether the link as specified exists, just disable this behavior via  `--no-enforce-https`.

Linking here an old issue #314 with some discussions around http:// links having https:// alternative, which is not something html-proofer is meant to check.

**Comment by RichardLitt** [comment]
Got it! Thank you.

**Comment by gjtorikian** [comment]
As well, if you'd prefer to keep HTTPS checks _on_ for everything, but _off_ for this one link, you could:

* Add [`data-proofer-ignore`](https://github.com/gjtorikian/html-proofer#ignoring-content) to the element; this will ignore it from _all_ the checks
* Ignore the URL with [`ignore_urls`](https://github.com/gjtorikian/html-proofer#regular-expressions); this will ignore it from all the link checks, eg., if this link is broken, it also wouldn't be reported.
