### ISSUE TITLE
Error during deployment with scheme format

### ISSUE THREAD

**Issue by 0-Kaustubh-0** [gjtorikian/html-proofer#807]
Hello!

I'm getting an error during the deployment of my website on Github actions, which has something to do with `htmlproofer`:

```
KaustubhSinha.github.io/vendor/bundle/ruby/3.2.0/gems/addressable-2.8.5/lib/addressable/uri.rb:913:in `scheme=': Invalid scheme format: 'Link to article' (Addressable::URI::InvalidURIError)
htmlproofer 4.4.3 | Error:  Invalid scheme format: 'Link to article'
```

I'm not a programmer and am using `jekyll` to host a webpage for my engineering portfolio. I would greatly appreciate any help I can get as CI/CD is beyond my cup of tea.

Thank you.

**Comment by gjtorikian** [comment]
Two things stand out:

* htmlproofer's latest version is `5.0.8`, not `4.4.3`. Can you update this?
* Judging by the error message, I would guess that the HTML is incorrectly written as `<a href="Link to article">`. Can you share your portfolio, or the line that contains the text "Link to article" ?

`Invalid scheme format` means that a URL link is not using `http` or `https`, so there is almost certainly a typo somewhere.

**Comment by 0-Kaustubh-0** [comment]
Thank you Garen! 

* I'm unsure how to update the htmlproofer version. Perhaps I'll need to pull to my repo? (This whole jekyll bundle was created by someone else)
* You mentioning `<a href="Link to article">` immediately cleared my question as I knew where the problem was. I encountered some other similar errors but they are resolved and my website is published! :smile:

**Comment by gjtorikian** [comment]
Glad to hear it!
