### ISSUE TITLE
Configuration by file?

### ISSUE THREAD

**Issue by rhwood** [gjtorikian/html-proofer#843]
Is it possible to use a config file for html-proofer?

I'd really like to be able to just run the command and not think about the need to match arguments with the CI checks for the command (since I can't run the CI checks locally while editing my site).

**Comment by gjtorikian** [comment]
It's possible to define your own YAML file and read that into the config, as discussed here: https://github.com/gjtorikian/html-proofer/issues/175

But otherwise, no, there's no file config provided. I'd accept a PR should someone wish to add the feature, though.
